EXPLANATIONS = {
    "starter.phonics": {
        "title": "自然拼读 Phonics",
        "one_liner": "掌握字母发音规则，看到单词就能读出来",
        "steps": ["认识26个字母", "学习元音发音", "学习辅音发音", "组合拼读练习"],
        "example": "c-a-t -> /k/ + /ae/ + /t/ -> cat",
        "tip": "每天练习10分钟，2周内掌握所有基础音",
    },
    "starter.greetings": {
        "title": "问候表达 Greetings",
        "one_liner": "学会打招呼、道别和礼貌回应",
        "steps": ["基础问候语", "自我介绍", "感谢与回应", "告别表达"],
        "example": "Hello! I'm Li. Nice to meet you.",
        "tip": "微笑+语调上扬会更友好",
    },
    "starter.numbers": {
        "title": "数字与时间 Numbers & Time",
        "one_liner": "能读写数字、时间和日期",
        "steps": ["1-20基础数字", "整十与组合数", "时间表达", "日期与星期"],
        "example": "7:30 -> seven thirty",
        "tip": "先熟悉整十数，再学20-99组合",
    },
    "starter.daily": {
        "title": "日常用语 Daily Phrases",
        "one_liner": "覆盖家庭、学校与常见场景",
        "steps": ["家庭物品", "学校用品", "点餐用语", "常用请求"],
        "example": "I would like a sandwich, please.",
        "tip": "把常用短句写在卡片上随身复习",
    },
    "elementary.grammar": {
        "title": "基础语法 Basic Grammar",
        "one_liner": "掌握be动词和一般现在时",
        "steps": ["主谓一致", "否定与疑问", "名词复数", "基础时态"],
        "example": "She goes to school every day.",
        "tip": "第三人称单数记得加-s",
    },
    "elementary.dialog": {
        "title": "简单对话 Simple Dialogs",
        "one_liner": "能完成点餐、问路、自我介绍",
        "steps": ["点餐对话", "问路表达", "自我介绍", "购物对话"],
        "example": "A: How much is this? B: It's five dollars.",
        "tip": "准备3-5个万能句型反复练",
    },
    "elementary.routines": {
        "title": "生活场景 Daily Routines",
        "one_liner": "描述日常作息与习惯",
        "steps": ["起床与上学", "交通与出行", "作息时间", "频率副词"],
        "example": "I usually get up at 7 a.m.",
        "tip": "频率副词通常放在实义动词前",
    },
    "elementary.questions": {
        "title": "提问句型 Question Forms",
        "one_liner": "熟练使用Wh-问题和一般疑问句",
        "steps": ["Do/Does结构", "Wh-疑问词", "be动词疑问句", "常用提问"],
        "example": "Where does she live?",
        "tip": "疑问句牢记助动词提前",
    },
    "intermediate.precision": {
        "title": "精准表达 Precision",
        "one_liner": "用可验证的事实代替模糊的泛化陈述",
        "steps": ["识别泛化表达", "加入具体数字", "限定时间范围", "明确主语范围"],
        "example": "X Students learn better -> Grade 10 scores rose 12% after 4 weeks",
        "tip": "问自己：这个说法能被证明吗？范围是什么？",
    },
    "intermediate.structure": {
        "title": "段落结构 Paragraph Structure",
        "one_liner": "写出清晰、有逻辑的段落",
        "steps": ["主题句", "支撑证据", "解释与例子", "总结句"],
        "example": "Topic -> Evidence -> Explanation -> Conclusion",
        "tip": "每段只讲一个中心观点",
    },
    "intermediate.logic": {
        "title": "逻辑连接 Logical Linking",
        "one_liner": "让句子之间关系清晰有力",
        "steps": ["因果连接", "转折对比", "举例说明", "递进补充"],
        "example": "It was raining, so we stayed inside.",
        "tip": "连接词用少而准，不要堆砌",
    },
    "intermediate.reading": {
        "title": "阅读理解 Reading Skills",
        "one_liner": "快速抓主旨与细节",
        "steps": ["主旨判断", "细节定位", "推断含义", "段落标题"],
        "example": "Main idea: Cities add bike lanes to reduce traffic.",
        "tip": "先读题再定位段落",
    },
    "upper.argument": {
        "title": "议论文表达 Argumentation",
        "one_liner": "形成观点并用证据支持",
        "steps": ["提出清晰观点", "提供数据证据", "加入反方观点", "有效反驳"],
        "example": "Claim -> Evidence -> Counter -> Rebuttal",
        "tip": "至少准备一条反方观点以提升说服力",
    },
    "upper.academic": {
        "title": "学术词汇 Academic Vocabulary",
        "one_liner": "用更正式的词汇表达观点",
        "steps": ["常见学术动词", "名词化表达", "正式替换词", "避免口语化"],
        "example": "show -> demonstrate; use -> utilize",
        "tip": "用词正式但不要生硬",
    },
    "upper.style": {
        "title": "地道表达 Natural Style",
        "one_liner": "避免中式表达，提升自然度",
        "steps": ["常见搭配", "简洁表达", "语域选择", "礼貌措辞"],
        "example": "I look forward to hearing from you.",
        "tip": "多背搭配，减少直译",
    },
    "upper.presentation": {
        "title": "演讲表达 Presentations",
        "one_liner": "结构化表达，抓住听众注意",
        "steps": ["开场吸引", "结构预告", "数据讲解", "总结与Q&A"],
        "example": "Today I'd like to share three key findings...",
        "tip": "每个部分用一句话过渡",
    },
    "advanced.critical": {
        "title": "批判思维 Critical Thinking",
        "one_liner": "评估证据、识别偏差与逻辑漏洞",
        "steps": ["检查证据质量", "识别样本偏差", "区分相关与因果", "提出限制"],
        "example": "Correlation doesn't imply causation.",
        "tip": "写出一个限制比写出三个观点更有力",
    },
    "advanced.complex": {
        "title": "复杂结构 Complex Structures",
        "one_liner": "掌握高级从句与倒装结构",
        "steps": ["定语从句", "分词结构", "倒装句型", "名词化"],
        "example": "Not only did she finish, but she also won.",
        "tip": "先写简单句，再升级为复杂句",
    },
    "advanced.rhetoric": {
        "title": "风格塑造 Rhetorical Style",
        "one_liner": "用修辞与节奏提升表达力度",
        "steps": ["平行结构", "重复强调", "修辞问句", "对比反衬"],
        "example": "We need action, action, action.",
        "tip": "强调用一次就够，别滥用",
    },
    "advanced.synthesis": {
        "title": "综合写作 Synthesis",
        "one_liner": "整合多来源信息形成观点",
        "steps": ["识别共同点", "比较差异", "整合证据", "得出结论"],
        "example": "Together, the studies indicate...",
        "tip": "每一段至少引用两条来源",
    },
    "ielts.listening": {
        "title": "听力专项 Listening",
        "one_liner": "锁定关键信息并识别干扰项",
        "steps": ["预读题干", "抓关键词", "识别更正", "检查拼写"],
        "example": "A: It's 13B... sorry, 13D.",
        "tip": "注意转折和更正词",
    },
    "ielts.reading": {
        "title": "阅读专项 Reading",
        "one_liner": "快速定位与同义替换",
        "steps": ["扫读找主旨", "定位细节", "识别同义", "时间管理"],
        "example": "question: increase -> text: rise",
        "tip": "不要逐词翻译",
    },
    "ielts.writing": {
        "title": "写作专项 Writing",
        "one_liner": "掌握Task 1/2结构与评分点",
        "steps": ["理解题型", "搭建结构", "使用数据", "语法多样性"],
        "example": "Overall, sales rose while costs fell.",
        "tip": "先写结构，再填内容",
    },
    "ielts.speaking": {
        "title": "口语专项 Speaking",
        "one_liner": "流利、连贯、有内容",
        "steps": ["扩展回答", "使用连接词", "适度停顿", "自我纠正"],
        "example": "In my view, public transport is essential because...",
        "tip": "每个回答至少包含理由",
    },
}
