LEVELS = [
    {
        "id": "starter",
        "name": "Starter",
        "name_zh": "零基础",
        "cefr": "A0-A1",
        "desc": "字母发音·基础词汇·日常问候",
        "emoji": "🌱",
        "color": "#4facfe",
        "target": "完全零基础，第一次学习",
    },
    {
        "id": "elementary",
        "name": "Elementary",
        "name_zh": "初级",
        "cefr": "A2",
        "desc": "基础语法·简单对话·生活场景",
        "emoji": "🌿",
        "color": "#43e97b",
        "target": "能说简单句子，想打好基础",
    },
    {
        "id": "intermediate",
        "name": "Intermediate",
        "name_zh": "中级",
        "cefr": "B1",
        "desc": "逻辑表达·段落写作·阅读理解",
        "emoji": "🌳",
        "color": "#f093fb",
        "target": "日常对话没问题，想提升表达",
    },
    {
        "id": "upper",
        "name": "Upper-Intermediate",
        "name_zh": "中高级",
        "cefr": "B2",
        "desc": "精准表达·议论文·学术词汇",
        "emoji": "🏔️",
        "color": "#667eea",
        "target": "流利表达，攻克精准和地道",
    },
    {
        "id": "advanced",
        "name": "Advanced",
        "name_zh": "高级",
        "cefr": "C1",
        "desc": "批判思维·复杂结构·风格塑造",
        "emoji": "🚀",
        "color": "#f5576c",
        "target": "接近母语，追求卓越表达",
    },
    {
        "id": "ielts",
        "name": "IELTS/SAT",
        "name_zh": "考试专项",
        "cefr": "B2-C1",
        "desc": "雅思·SAT·学术写作专项训练",
        "emoji": "🎯",
        "color": "#fda085",
        "target": "备考雅思/SAT，冲击高分",
    },
]
