MODULES_JA = [
    {
        "id": "ja.starter.hiragana",
        "name": "Hiragana",
        "name_zh": "平假名",
        "desc": "平假名识读与发音",
        "level_id": "starter",
        "order": 1,
        "emoji": "🔤",
        "lang": "ja",
    },
    {
        "id": "ja.starter.katakana",
        "name": "Katakana",
        "name_zh": "片假名",
        "desc": "片假名识读与外来语",
        "level_id": "starter",
        "order": 2,
        "emoji": "🧩",
        "lang": "ja",
    },
    {
        "id": "ja.starter.greetings",
        "name": "Greetings",
        "name_zh": "问候表达",
        "desc": "日语常用问候与自我介绍",
        "level_id": "starter",
        "order": 3,
        "emoji": "👋",
        "lang": "ja",
    },
    {
        "id": "ja.elementary.numbers",
        "name": "Numbers",
        "name_zh": "数字表达",
        "desc": "日语数字与时间",
        "level_id": "elementary",
        "order": 1,
        "emoji": "🔢",
        "lang": "ja",
    },
    {
        "id": "ja.elementary.family",
        "name": "Family",
        "name_zh": "家庭成员",
        "desc": "家族称谓与礼貌用语",
        "level_id": "elementary",
        "order": 2,
        "emoji": "🏠",
        "lang": "ja",
    },
    {
        "id": "ja.elementary.keigo_basic",
        "name": "Keigo Basics",
        "name_zh": "敬语基础",
        "desc": "です/ます与礼貌表达",
        "level_id": "elementary",
        "order": 3,
        "emoji": "🙏",
        "lang": "ja",
    },
    {
        "id": "ja.intermediate.keigo_adv",
        "name": "Keigo Advanced",
        "name_zh": "敬语进阶",
        "desc": "尊敬语与谦让语区分",
        "level_id": "intermediate",
        "order": 1,
        "emoji": "🎌",
        "lang": "ja",
    },
    {
        "id": "ja.intermediate.shopping",
        "name": "Shopping",
        "name_zh": "购物表达",
        "desc": "价格、试穿与支付",
        "level_id": "intermediate",
        "order": 2,
        "emoji": "🛍️",
        "lang": "ja",
    },
    {
        "id": "ja.intermediate.travel",
        "name": "Travel",
        "name_zh": "旅行出行",
        "desc": "交通、订票与问路",
        "level_id": "intermediate",
        "order": 3,
        "emoji": "🚅",
        "lang": "ja",
    },
]
