MODULES = [
    {
        "id": "starter.phonics",
        "name": "Phonics",
        "name_zh": "自然拼读",
        "desc": "26个字母发音规则",
        "level_id": "starter",
        "order": 1,
        "emoji": "🔤",
    },
    {
        "id": "starter.greetings",
        "name": "Greetings",
        "name_zh": "问候表达",
        "desc": "Hello/Goodbye/How are you",
        "level_id": "starter",
        "order": 2,
        "emoji": "👋",
    },
    {
        "id": "starter.numbers",
        "name": "Numbers & Time",
        "name_zh": "数字与时间",
        "desc": "数字、时间、日期表达",
        "level_id": "starter",
        "order": 3,
        "emoji": "🔢",
    },
    {
        "id": "starter.daily",
        "name": "Daily Phrases",
        "name_zh": "日常用语",
        "desc": "家/学校/食物",
        "level_id": "starter",
        "order": 4,
        "emoji": "🏠",
    },
    {
        "id": "elementary.grammar",
        "name": "Basic Grammar",
        "name_zh": "基础语法",
        "desc": "be动词/一般现在时",
        "level_id": "elementary",
        "order": 1,
        "emoji": "📘",
    },
    {
        "id": "elementary.dialog",
        "name": "Simple Dialogs",
        "name_zh": "简单对话",
        "desc": "点餐/问路/自我介绍",
        "level_id": "elementary",
        "order": 2,
        "emoji": "💬",
    },
    {
        "id": "elementary.routines",
        "name": "Daily Routines",
        "name_zh": "生活场景",
        "desc": "起居/校园/出行",
        "level_id": "elementary",
        "order": 3,
        "emoji": "⏰",
    },
    {
        "id": "elementary.questions",
        "name": "Question Forms",
        "name_zh": "提问句型",
        "desc": "Wh-问题与Yes/No问句",
        "level_id": "elementary",
        "order": 4,
        "emoji": "❓",
    },
    {
        "id": "intermediate.precision",
        "name": "Precision",
        "name_zh": "精准表达",
        "desc": "可验证性/范围/因果",
        "level_id": "intermediate",
        "order": 1,
        "emoji": "🎯",
    },
    {
        "id": "intermediate.structure",
        "name": "Paragraph Structure",
        "name_zh": "段落结构",
        "desc": "主题句/支撑句/结论",
        "level_id": "intermediate",
        "order": 2,
        "emoji": "🏗️",
    },
    {
        "id": "intermediate.logic",
        "name": "Logical Linking",
        "name_zh": "逻辑连接",
        "desc": "因果/转折/递进",
        "level_id": "intermediate",
        "order": 3,
        "emoji": "🧠",
    },
    {
        "id": "intermediate.reading",
        "name": "Reading Skills",
        "name_zh": "阅读理解",
        "desc": "主旨/细节/推断",
        "level_id": "intermediate",
        "order": 4,
        "emoji": "📖",
    },
    {
        "id": "upper.argument",
        "name": "Argumentation",
        "name_zh": "议论文表达",
        "desc": "观点-论据-反驳",
        "level_id": "upper",
        "order": 1,
        "emoji": "⚖️",
    },
    {
        "id": "upper.academic",
        "name": "Academic Vocabulary",
        "name_zh": "学术词汇",
        "desc": "学术写作高频词",
        "level_id": "upper",
        "order": 2,
        "emoji": "📚",
    },
    {
        "id": "upper.style",
        "name": "Natural Style",
        "name_zh": "地道表达",
        "desc": "同义改写/语体选择",
        "level_id": "upper",
        "order": 3,
        "emoji": "✨",
    },
    {
        "id": "upper.presentation",
        "name": "Presentations",
        "name_zh": "演讲表达",
        "desc": "结构化演讲与衔接",
        "level_id": "upper",
        "order": 4,
        "emoji": "🎤",
    },
    {
        "id": "advanced.critical",
        "name": "Critical Thinking",
        "name_zh": "批判思维",
        "desc": "评估证据与观点",
        "level_id": "advanced",
        "order": 1,
        "emoji": "🛰️",
    },
    {
        "id": "advanced.complex",
        "name": "Complex Structures",
        "name_zh": "复杂结构",
        "desc": "从句嵌套/非谓语",
        "level_id": "advanced",
        "order": 2,
        "emoji": "🧩",
    },
    {
        "id": "advanced.rhetoric",
        "name": "Rhetorical Style",
        "name_zh": "风格塑造",
        "desc": "语气/修辞/强调",
        "level_id": "advanced",
        "order": 3,
        "emoji": "🎙️",
    },
    {
        "id": "advanced.synthesis",
        "name": "Synthesis Writing",
        "name_zh": "综合写作",
        "desc": "多文本整合写作",
        "level_id": "advanced",
        "order": 4,
        "emoji": "🧵",
    },
    {
        "id": "ielts.listening",
        "name": "Listening",
        "name_zh": "听力专项",
        "desc": "细节捕捉与地图题",
        "level_id": "ielts",
        "order": 1,
        "emoji": "🎧",
    },
    {
        "id": "ielts.reading",
        "name": "Reading",
        "name_zh": "阅读专项",
        "desc": "定位信息与同义替换",
        "level_id": "ielts",
        "order": 2,
        "emoji": "📄",
    },
    {
        "id": "ielts.writing",
        "name": "Writing",
        "name_zh": "写作专项",
        "desc": "Task 1/2 结构与数据",
        "level_id": "ielts",
        "order": 3,
        "emoji": "✍️",
    },
    {
        "id": "ielts.speaking",
        "name": "Speaking",
        "name_zh": "口语专项",
        "desc": "话题扩展与流利度",
        "level_id": "ielts",
        "order": 4,
        "emoji": "🗣️",
    },
]
