MODULES_ES = [
    {
        "id": "es.starter.alphabet",
        "name": "Alphabet & Pronunciation",
        "name_zh": "字母与发音",
        "desc": "西班牙语字母与发音",
        "level_id": "starter",
        "order": 1,
        "emoji": "🔤",
        "lang": "es",
    },
    {
        "id": "es.starter.greetings",
        "name": "Greetings",
        "name_zh": "问候表达",
        "desc": "常用问候与告别",
        "level_id": "starter",
        "order": 2,
        "emoji": "👋",
        "lang": "es",
    },
    {
        "id": "es.starter.numbers",
        "name": "Numbers",
        "name_zh": "数字表达",
        "desc": "数字与时间表达",
        "level_id": "starter",
        "order": 3,
        "emoji": "🔢",
        "lang": "es",
    },
    {
        "id": "es.elementary.gender_nouns",
        "name": "Gender & Nouns",
        "name_zh": "名词性别",
        "desc": "名词性别与冠词",
        "level_id": "elementary",
        "order": 1,
        "emoji": "📘",
        "lang": "es",
    },
    {
        "id": "es.elementary.family",
        "name": "Family",
        "name_zh": "家庭成员",
        "desc": "家庭称谓与所有格",
        "level_id": "elementary",
        "order": 2,
        "emoji": "🏠",
        "lang": "es",
    },
    {
        "id": "es.elementary.daily",
        "name": "Daily Life",
        "name_zh": "日常生活",
        "desc": "日常活动与时间表达",
        "level_id": "elementary",
        "order": 3,
        "emoji": "⏰",
        "lang": "es",
    },
    {
        "id": "es.intermediate.ser_estar",
        "name": "Ser vs Estar",
        "name_zh": "ser与estar",
        "desc": "本质与状态的区分",
        "level_id": "intermediate",
        "order": 1,
        "emoji": "🎯",
        "lang": "es",
    },
    {
        "id": "es.intermediate.shopping",
        "name": "Shopping",
        "name_zh": "购物表达",
        "desc": "价格、尺寸与试穿",
        "level_id": "intermediate",
        "order": 2,
        "emoji": "🛍️",
        "lang": "es",
    },
    {
        "id": "es.intermediate.travel",
        "name": "Travel",
        "name_zh": "旅行出行",
        "desc": "交通、订票与问路",
        "level_id": "intermediate",
        "order": 3,
        "emoji": "✈️",
        "lang": "es",
    },
]
