MODULES_KO = [
    {
        "id": "ko.starter.hangul",
        "name": "Hangul",
        "name_zh": "韩文字母",
        "desc": "韩文字母与发音规则",
        "level_id": "starter",
        "order": 1,
        "emoji": "🔤",
        "lang": "ko",
    },
    {
        "id": "ko.starter.greetings",
        "name": "Greetings",
        "name_zh": "问候表达",
        "desc": "韩语常用问候与致谢",
        "level_id": "starter",
        "order": 2,
        "emoji": "👋",
        "lang": "ko",
    },
    {
        "id": "ko.starter.numbers",
        "name": "Numbers",
        "name_zh": "数字表达",
        "desc": "韩语数字与读法",
        "level_id": "starter",
        "order": 3,
        "emoji": "🔢",
        "lang": "ko",
    },
    {
        "id": "ko.elementary.formal_speech",
        "name": "Formal Speech",
        "name_zh": "正式语体",
        "desc": "敬语基本句尾",
        "level_id": "elementary",
        "order": 1,
        "emoji": "📘",
        "lang": "ko",
    },
    {
        "id": "ko.elementary.family",
        "name": "Family",
        "name_zh": "家庭成员",
        "desc": "家庭称谓与称呼",
        "level_id": "elementary",
        "order": 2,
        "emoji": "🏠",
        "lang": "ko",
    },
    {
        "id": "ko.elementary.food",
        "name": "Food",
        "name_zh": "饮食点餐",
        "desc": "点餐与口味表达",
        "level_id": "elementary",
        "order": 3,
        "emoji": "🍲",
        "lang": "ko",
    },
    {
        "id": "ko.intermediate.honorifics",
        "name": "Honorifics",
        "name_zh": "尊敬表达",
        "desc": "尊待法与特殊动词",
        "level_id": "intermediate",
        "order": 1,
        "emoji": "🙇",
        "lang": "ko",
    },
    {
        "id": "ko.intermediate.shopping",
        "name": "Shopping",
        "name_zh": "购物表达",
        "desc": "价格、尺寸与换货",
        "level_id": "intermediate",
        "order": 2,
        "emoji": "🛍️",
        "lang": "ko",
    },
    {
        "id": "ko.intermediate.travel",
        "name": "Travel",
        "name_zh": "旅行出行",
        "desc": "交通、订票与问路",
        "level_id": "intermediate",
        "order": 3,
        "emoji": "🚌",
        "lang": "ko",
    },
]
