MODULES_RU = [
    {
        "id": "ru.starter.cyrillic",
        "name": "Cyrillic",
        "name_zh": "西里尔字母",
        "desc": "西里尔字母与发音",
        "level_id": "starter",
        "order": 1,
        "emoji": "🔤",
        "lang": "ru",
    },
    {
        "id": "ru.starter.greetings",
        "name": "Greetings",
        "name_zh": "问候表达",
        "desc": "常用问候与告别",
        "level_id": "starter",
        "order": 2,
        "emoji": "👋",
        "lang": "ru",
    },
    {
        "id": "ru.starter.numbers",
        "name": "Numbers",
        "name_zh": "数字表达",
        "desc": "数字与时间表达",
        "level_id": "starter",
        "order": 3,
        "emoji": "🔢",
        "lang": "ru",
    },
    {
        "id": "ru.elementary.nouns_gender",
        "name": "Noun Gender",
        "name_zh": "名词性别",
        "desc": "名词阴阳中性与词尾",
        "level_id": "elementary",
        "order": 1,
        "emoji": "📘",
        "lang": "ru",
    },
    {
        "id": "ru.elementary.family",
        "name": "Family",
        "name_zh": "家庭成员",
        "desc": "家庭称谓与所有格",
        "level_id": "elementary",
        "order": 2,
        "emoji": "🏠",
        "lang": "ru",
    },
    {
        "id": "ru.elementary.daily",
        "name": "Daily Life",
        "name_zh": "日常生活",
        "desc": "日常活动与常用动词",
        "level_id": "elementary",
        "order": 3,
        "emoji": "⏰",
        "lang": "ru",
    },
    {
        "id": "ru.intermediate.cases",
        "name": "Cases",
        "name_zh": "格变化",
        "desc": "名词格变化与介词",
        "level_id": "intermediate",
        "order": 1,
        "emoji": "🧠",
        "lang": "ru",
    },
    {
        "id": "ru.intermediate.shopping",
        "name": "Shopping",
        "name_zh": "购物表达",
        "desc": "价格、数量与结账",
        "level_id": "intermediate",
        "order": 2,
        "emoji": "🛍️",
        "lang": "ru",
    },
    {
        "id": "ru.intermediate.travel",
        "name": "Travel",
        "name_zh": "旅行出行",
        "desc": "交通、订票与问路",
        "level_id": "intermediate",
        "order": 3,
        "emoji": "🚆",
        "lang": "ru",
    },
]
