MODULES_FR = [
    {
        "id": "fr.starter.alphabet",
        "name": "Alphabet & Pronunciation",
        "name_zh": "字母与发音",
        "desc": "法语字母发音与拼读",
        "level_id": "starter",
        "order": 1,
        "emoji": "🔤",
        "lang": "fr",
    },
    {
        "id": "fr.starter.greetings",
        "name": "Greetings",
        "name_zh": "问候表达",
        "desc": "法语日常问候与告别",
        "level_id": "starter",
        "order": 2,
        "emoji": "👋",
        "lang": "fr",
    },
    {
        "id": "fr.starter.numbers",
        "name": "Numbers",
        "name_zh": "数字表达",
        "desc": "法语数字与时间表达",
        "level_id": "starter",
        "order": 3,
        "emoji": "🔢",
        "lang": "fr",
    },
    {
        "id": "fr.elementary.articles",
        "name": "Articles & Gender",
        "name_zh": "冠词与性别",
        "desc": "名词阴阳性与冠词",
        "level_id": "elementary",
        "order": 1,
        "emoji": "📘",
        "lang": "fr",
    },
    {
        "id": "fr.elementary.family",
        "name": "Family",
        "name_zh": "家庭成员",
        "desc": "家庭称谓与所有格",
        "level_id": "elementary",
        "order": 2,
        "emoji": "🏠",
        "lang": "fr",
    },
    {
        "id": "fr.elementary.daily",
        "name": "Daily Life",
        "name_zh": "日常生活",
        "desc": "日常活动与时间表达",
        "level_id": "elementary",
        "order": 3,
        "emoji": "⏰",
        "lang": "fr",
    },
    {
        "id": "fr.intermediate.past_tense",
        "name": "Past Tense",
        "name_zh": "过去时",
        "desc": "复合过去时与未完成过去时",
        "level_id": "intermediate",
        "order": 1,
        "emoji": "⏳",
        "lang": "fr",
    },
    {
        "id": "fr.intermediate.shopping",
        "name": "Shopping",
        "name_zh": "购物表达",
        "desc": "价格、尺寸与试穿",
        "level_id": "intermediate",
        "order": 2,
        "emoji": "🛍️",
        "lang": "fr",
    },
    {
        "id": "fr.intermediate.travel",
        "name": "Travel",
        "name_zh": "旅行出行",
        "desc": "交通、订票与问路",
        "level_id": "intermediate",
        "order": 3,
        "emoji": "✈️",
        "lang": "fr",
    },
]
