QUESTIONS = {
    "starter.phonics": [
        {
            "id": "ph_001",
            "type": "choice",
            "level": "A0",
            "prompt": "Which letter makes the /ae/ sound as in cat?",
            "options": ["A", "E", "I", "O"],
            "answer": "A",
            "explanation": "The letter A makes the /ae/ sound in words like cat, hat, mat.",
        },
        {
            "id": "ph_002",
            "type": "choice",
            "level": "A0",
            "prompt": "Which letter makes the /b/ sound at the start of 'ball'?",
            "options": ["B", "D", "P", "V"],
            "answer": "B",
            "explanation": "Ball starts with the /b/ sound made by the letter B.",
        },
        {
            "id": "ph_003",
            "type": "choice",
            "level": "A0",
            "prompt": "Which word starts with the /s/ sound?",
            "options": ["sun", "moon", "rain", "kite"],
            "answer": "sun",
            "explanation": "Sun begins with the /s/ sound.",
        },
        {
            "id": "ph_004",
            "type": "choice",
            "level": "A0",
            "prompt": "Which letter makes the /m/ sound?",
            "options": ["N", "M", "L", "R"],
            "answer": "M",
            "explanation": "The letter M makes the /m/ sound as in milk.",
        },
        {
            "id": "ph_005",
            "type": "choice",
            "level": "A0",
            "prompt": "Which vowel sound is in the word 'bed'?",
            "options": ["/e/", "/i/", "/o/", "/u/"],
            "answer": "/e/",
            "explanation": "Bed has the short /e/ sound.",
        },
        {
            "id": "ph_006",
            "type": "choice",
            "level": "A0",
            "prompt": "Which word has the /t/ sound at the end?",
            "options": ["dog", "cat", "sun", "pen"],
            "answer": "cat",
            "explanation": "Cat ends with the /t/ sound.",
        },
        {
            "id": "ph_007",
            "type": "choice",
            "level": "A0",
            "prompt": "Which word starts with the /k/ sound?",
            "options": ["kite", "zip", "fish", "jar"],
            "answer": "kite",
            "explanation": "Kite starts with the /k/ sound.",
        },
        {
            "id": "ph_008",
            "type": "choice",
            "level": "A0",
            "prompt": "Which letter makes the /g/ sound as in 'go'?",
            "options": ["G", "J", "H", "K"],
            "answer": "G",
            "explanation": "The /g/ sound in go is made by G.",
        },
    ],
    "starter.greetings": [
        {
            "id": "gr_001",
            "type": "choice",
            "level": "A0",
            "prompt": "What do you say when you meet someone in the morning?",
            "options": ["Good night", "Good morning", "Goodbye", "See you"],
            "answer": "Good morning",
            "explanation": "Good morning is used to greet someone before noon.",
        },
        {
            "id": "gr_002",
            "type": "choice",
            "level": "A0",
            "prompt": "A: How are you? B: ___",
            "options": ["I'm fine, thanks.", "Good night.", "See you later.", "Nice to meet you."] ,
            "answer": "I'm fine, thanks.",
            "explanation": "A common response to 'How are you?' is 'I'm fine, thanks.'",
        },
        {
            "id": "gr_003",
            "type": "choice",
            "level": "A0",
            "prompt": "Which phrase is a friendly goodbye?",
            "options": ["Hello", "Goodbye", "Good morning", "How are you"],
            "answer": "Goodbye",
            "explanation": "Goodbye is used when leaving.",
        },
        {
            "id": "gr_004",
            "type": "choice",
            "level": "A0",
            "prompt": "What do you say when you meet someone for the first time?",
            "options": ["Nice to meet you.", "See you later.", "Good night.", "You're welcome."],
            "answer": "Nice to meet you.",
            "explanation": "Nice to meet you is used for first-time introductions.",
        },
        {
            "id": "gr_005",
            "type": "choice",
            "level": "A0",
            "prompt": "A: Thank you. B: ___",
            "options": ["You're welcome.", "Hello.", "Goodbye.", "I'm tired."],
            "answer": "You're welcome.",
            "explanation": "You're welcome is a polite response to thanks.",
        },
        {
            "id": "gr_006",
            "type": "choice",
            "level": "A0",
            "prompt": "Which greeting is used in the evening?",
            "options": ["Good evening", "Good morning", "Goodbye", "Hello"],
            "answer": "Good evening",
            "explanation": "Good evening is used after sunset.",
        },
        {
            "id": "gr_007",
            "type": "choice",
            "level": "A0",
            "prompt": "A: See you tomorrow. B: ___",
            "options": ["See you.", "Good morning.", "I'm fine.", "Nice to meet you."] ,
            "answer": "See you.",
            "explanation": "See you is a casual goodbye.",
        },
        {
            "id": "gr_008",
            "type": "choice",
            "level": "A0",
            "prompt": "Which is the most informal greeting?",
            "options": ["Hi", "Good morning", "Good evening", "Nice to meet you"],
            "answer": "Hi",
            "explanation": "Hi is an informal greeting.",
        },
    ],
    "starter.numbers": [
        {
            "id": "nu_001",
            "type": "choice",
            "level": "A0",
            "prompt": "What number comes after seven?",
            "options": ["six", "seven", "eight", "nine"],
            "answer": "eight",
            "explanation": "After seven comes eight.",
        },
        {
            "id": "nu_002",
            "type": "choice",
            "level": "A0",
            "prompt": "How do you write the number 12 in words?",
            "options": ["twelve", "twenty", "two", "ten"],
            "answer": "twelve",
            "explanation": "12 is written as twelve.",
        },
        {
            "id": "nu_003",
            "type": "choice",
            "level": "A0",
            "prompt": "Which is correct for 3:30?",
            "options": ["three thirty", "three thirteen", "thirty three", "three three"],
            "answer": "three thirty",
            "explanation": "3:30 is said 'three thirty'.",
        },
        {
            "id": "nu_004",
            "type": "choice",
            "level": "A0",
            "prompt": "What is 5 + 2?",
            "options": ["six", "seven", "eight", "nine"],
            "answer": "seven",
            "explanation": "5 + 2 = 7.",
        },
        {
            "id": "nu_005",
            "type": "choice",
            "level": "A0",
            "prompt": "Which is a weekday?",
            "options": ["Sunday", "Monday", "Saturday", "Holiday"],
            "answer": "Monday",
            "explanation": "Monday is a weekday.",
        },
        {
            "id": "nu_006",
            "type": "choice",
            "level": "A0",
            "prompt": "How do you say 9:00?",
            "options": ["nine o'clock", "nine five", "five nine", "nine fifty"],
            "answer": "nine o'clock",
            "explanation": "9:00 is 'nine o'clock'.",
        },
        {
            "id": "nu_007",
            "type": "choice",
            "level": "A0",
            "prompt": "Which number is even?",
            "options": ["3", "5", "8", "9"],
            "answer": "8",
            "explanation": "8 is an even number.",
        },
        {
            "id": "nu_008",
            "type": "choice",
            "level": "A0",
            "prompt": "What month comes after March?",
            "options": ["February", "April", "May", "June"],
            "answer": "April",
            "explanation": "April comes after March.",
        },
    ],
    "starter.daily": [
        {
            "id": "da_001",
            "type": "choice",
            "level": "A0",
            "prompt": "Which word means '吃早饭'?",
            "options": ["have breakfast", "go to sleep", "go home", "do homework"],
            "answer": "have breakfast",
            "explanation": "Have breakfast means 吃早饭.",
        },
        {
            "id": "da_002",
            "type": "choice",
            "level": "A0",
            "prompt": "A: Where is the classroom? B: ___",
            "options": ["It is upstairs.", "I am hungry.", "Good night.", "See you."],
            "answer": "It is upstairs.",
            "explanation": "This answer gives a location.",
        },
        {
            "id": "da_003",
            "type": "choice",
            "level": "A0",
            "prompt": "Which phrase is for ordering food?",
            "options": ["I would like a sandwich.", "I am a student.", "This is my book.", "It is raining."],
            "answer": "I would like a sandwich.",
            "explanation": "This is a polite way to order food.",
        },
        {
            "id": "da_004",
            "type": "choice",
            "level": "A0",
            "prompt": "Which is a school item?",
            "options": ["pencil", "banana", "chair", "water"],
            "answer": "pencil",
            "explanation": "A pencil is a school item.",
        },
        {
            "id": "da_005",
            "type": "choice",
            "level": "A0",
            "prompt": "What do you say when you need help?",
            "options": ["Can you help me?", "I am full.", "Goodbye.", "It is sunny."],
            "answer": "Can you help me?",
            "explanation": "This is a polite request for help.",
        },
        {
            "id": "da_006",
            "type": "choice",
            "level": "A0",
            "prompt": "Which sentence is about your home?",
            "options": ["My house is small.", "I like apples.", "She is a teacher.", "We are happy."],
            "answer": "My house is small.",
            "explanation": "This sentence describes a home.",
        },
        {
            "id": "da_007",
            "type": "choice",
            "level": "A0",
            "prompt": "Which is a food word?",
            "options": ["rice", "book", "desk", "door"],
            "answer": "rice",
            "explanation": "Rice is food.",
        },
        {
            "id": "da_008",
            "type": "choice",
            "level": "A0",
            "prompt": "A: What is this? B: ___ (pointing to a cup)",
            "options": ["It is a cup.", "It is Monday.", "It is big.", "It is near."],
            "answer": "It is a cup.",
            "explanation": "This answer names the object.",
        },
    ],
    "elementary.grammar": [
        {
            "id": "eg_001",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct form: She ___ a student.",
            "options": ["am", "is", "are", "be"],
            "answer": "is",
            "explanation": "Use 'is' with she/he/it.",
        },
        {
            "id": "eg_002",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct sentence.",
            "options": ["He go to school.", "He goes to school.", "He going to school.", "He gone to school."],
            "answer": "He goes to school.",
            "explanation": "Third-person singular takes -s.",
        },
        {
            "id": "eg_003",
            "type": "choice",
            "level": "A2",
            "prompt": "Which is the plural of 'box'?",
            "options": ["boxs", "boxes", "box", "boxies"],
            "answer": "boxes",
            "explanation": "Add -es after words ending in x.",
        },
        {
            "id": "eg_004",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct negative: I ___ like coffee.",
            "options": ["don't", "doesn't", "isn't", "aren't"],
            "answer": "don't",
            "explanation": "Use don't with I/you/we/they.",
        },
        {
            "id": "eg_005",
            "type": "choice",
            "level": "A2",
            "prompt": "Which word is an adjective?",
            "options": ["quick", "quickly", "run", "running"],
            "answer": "quick",
            "explanation": "Quick describes a noun.",
        },
        {
            "id": "eg_006",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct sentence.",
            "options": ["They is happy.", "They are happy.", "They am happy.", "They be happy."],
            "answer": "They are happy.",
            "explanation": "Use 'are' with they.",
        },
        {
            "id": "eg_007",
            "type": "choice",
            "level": "A2",
            "prompt": "What is the past tense of 'walk'?",
            "options": ["walked", "walks", "walking", "walk"],
            "answer": "walked",
            "explanation": "Regular verbs add -ed in past tense.",
        },
        {
            "id": "eg_008",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct question: ___ you like tea?",
            "options": ["Do", "Does", "Is", "Are"],
            "answer": "Do",
            "explanation": "Use Do with you.",
        },
    ],
    "elementary.dialog": [
        {
            "id": "ed_001",
            "type": "choice",
            "level": "A2",
            "prompt": "A: Can I have the menu? B: ___",
            "options": ["Sure, here you are.", "I am hungry.", "It is blue.", "Good morning."],
            "answer": "Sure, here you are.",
            "explanation": "This is a polite response to a request.",
        },
        {
            "id": "ed_002",
            "type": "choice",
            "level": "A2",
            "prompt": "A: Where is the bus stop? B: ___",
            "options": ["It's next to the bank.", "I like buses.", "See you later.", "I'm fine."],
            "answer": "It's next to the bank.",
            "explanation": "This answers a location question.",
        },
        {
            "id": "ed_003",
            "type": "choice",
            "level": "A2",
            "prompt": "A: How much is this? B: ___",
            "options": ["It's five dollars.", "It's mine.", "It's small.", "It's open."],
            "answer": "It's five dollars.",
            "explanation": "This answers a price question.",
        },
        {
            "id": "ed_004",
            "type": "choice",
            "level": "A2",
            "prompt": "A: What do you do? B: ___",
            "options": ["I'm a teacher.", "I'm 25.", "I'm here.", "I'm tired."],
            "answer": "I'm a teacher.",
            "explanation": "This gives a job/role.",
        },
        {
            "id": "ed_005",
            "type": "choice",
            "level": "A2",
            "prompt": "A: Can you help me? B: ___",
            "options": ["Sure.", "Good night.", "No problem?", "I'm busy?"],
            "answer": "Sure.",
            "explanation": "Sure is a positive, polite response.",
        },
        {
            "id": "ed_006",
            "type": "choice",
            "level": "A2",
            "prompt": "A: Would you like tea or coffee? B: ___",
            "options": ["Tea, please.", "Yes, I do.", "I am fine.", "Goodbye."],
            "answer": "Tea, please.",
            "explanation": "Choose one of the options.",
        },
        {
            "id": "ed_007",
            "type": "choice",
            "level": "A2",
            "prompt": "A: What time does it open? B: ___",
            "options": ["At 9 a.m.", "It's new.", "It's open.", "It's cheap."],
            "answer": "At 9 a.m.",
            "explanation": "This gives a time.",
        },
        {
            "id": "ed_008",
            "type": "choice",
            "level": "A2",
            "prompt": "A: Sorry I'm late. B: ___",
            "options": ["That's okay.", "It's late.", "I'm late.", "It's fine?"],
            "answer": "That's okay.",
            "explanation": "That's okay accepts the apology.",
        },
    ],
    "elementary.routines": [
        {
            "id": "er_001",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct sentence.",
            "options": ["I get up at 7.", "I get up on 7.", "I get up in 7.", "I get up by 7?"],
            "answer": "I get up at 7.",
            "explanation": "Use 'at' with specific times.",
        },
        {
            "id": "er_002",
            "type": "choice",
            "level": "A2",
            "prompt": "Which verb matches 'breakfast'?",
            "options": ["have", "do", "make", "play"],
            "answer": "have",
            "explanation": "We say 'have breakfast'.",
        },
        {
            "id": "er_003",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct order: morning routine.",
            "options": ["wake up -> brush teeth -> go to school", "go to school -> wake up -> brush teeth", "brush teeth -> go to school -> wake up", "wake up -> go to school -> brush teeth"],
            "answer": "wake up -> brush teeth -> go to school",
            "explanation": "This is the normal order.",
        },
        {
            "id": "er_004",
            "type": "choice",
            "level": "A2",
            "prompt": "Which sentence uses 'usually' correctly?",
            "options": ["I usually go to bed at 10.", "Usually I am go to bed.", "I go bed usually at 10.", "I go usually bed at 10."],
            "answer": "I usually go to bed at 10.",
            "explanation": "Adverbs of frequency go before the main verb.",
        },
        {
            "id": "er_005",
            "type": "choice",
            "level": "A2",
            "prompt": "Which phrase means 放学后?",
            "options": ["after school", "before school", "at school", "in school"],
            "answer": "after school",
            "explanation": "After school means 放学后.",
        },
        {
            "id": "er_006",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct sentence.",
            "options": ["She goes home by bus.", "She goes home by a bus.", "She goes home with bus.", "She goes home in bus."],
            "answer": "She goes home by bus.",
            "explanation": "Use 'by bus' without an article.",
        },
        {
            "id": "er_007",
            "type": "choice",
            "level": "A2",
            "prompt": "Which is a weekend activity?",
            "options": ["go hiking", "go to class", "take a test", "do homework"],
            "answer": "go hiking",
            "explanation": "Go hiking is a typical weekend activity.",
        },
        {
            "id": "er_008",
            "type": "choice",
            "level": "A2",
            "prompt": "Which sentence is in the present continuous?",
            "options": ["I am cooking now.", "I cook every day.", "I cooked yesterday.", "I will cook."],
            "answer": "I am cooking now.",
            "explanation": "Present continuous uses am/is/are + verb-ing.",
        },
    ],
    "elementary.questions": [
        {
            "id": "eq_001",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct question for 'She lives in Beijing.'",
            "options": ["Where does she live?", "Where she live?", "Where do she live?", "Where is she live?"],
            "answer": "Where does she live?",
            "explanation": "Use does for third-person singular questions.",
        },
        {
            "id": "eq_002",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct question: ___ you like apples?",
            "options": ["Do", "Does", "Are", "Is"],
            "answer": "Do",
            "explanation": "Use Do with you/we/they.",
        },
        {
            "id": "eq_003",
            "type": "choice",
            "level": "A2",
            "prompt": "Which is a Wh-question?",
            "options": ["What is your name?", "Is it yours?", "Do you like it?", "Can you swim?"],
            "answer": "What is your name?",
            "explanation": "Wh-questions start with what/where/when/why/how.",
        },
        {
            "id": "eq_004",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct question for 'He is 12.'",
            "options": ["How old is he?", "How old he is?", "How is he old?", "How age is he?"],
            "answer": "How old is he?",
            "explanation": "Correct word order is auxiliary + subject.",
        },
        {
            "id": "eq_005",
            "type": "choice",
            "level": "A2",
            "prompt": "Which question asks about time?",
            "options": ["What time is it?", "What is it?", "Where is it?", "Who is it?"],
            "answer": "What time is it?",
            "explanation": "This question asks about time.",
        },
        {
            "id": "eq_006",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct question for 'They are in the park.'",
            "options": ["Where are they?", "Where they are?", "Where do they?", "Where is they?"],
            "answer": "Where are they?",
            "explanation": "Use are with they.",
        },
        {
            "id": "eq_007",
            "type": "choice",
            "level": "A2",
            "prompt": "Which is a Yes/No question?",
            "options": ["Do you like pizza?", "What do you like?", "Where do you live?", "Why are you here?"],
            "answer": "Do you like pizza?",
            "explanation": "Yes/No questions can be answered with yes or no.",
        },
        {
            "id": "eq_008",
            "type": "choice",
            "level": "A2",
            "prompt": "Choose the correct question for 'I go to work by bus.'",
            "options": ["How do you go to work?", "How you go to work?", "How do go to work?", "How you do go to work?"],
            "answer": "How do you go to work?",
            "explanation": "Use do-support for questions with verbs.",
        },
    ],
    "intermediate.precision": [
        {
            "id": "pr_001",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence is more precise?",
            "options": [
                "Students learn faster with technology.",
                "Test scores improved 15% after 8 weeks of tablet use.",
            ],
            "answer": "Test scores improved 15% after 8 weeks of tablet use.",
            "explanation": "精确陈述：有具体数字(15%)、时间范围(8周)、可验证对象(平板使用)",
        },
        {
            "id": "pr_002",
            "type": "choice",
            "level": "B1",
            "prompt": "Which statement is verifiable?",
            "options": ["The app is amazing.", "The app reduced errors by 20% in April."],
            "answer": "The app reduced errors by 20% in April.",
            "explanation": "This statement includes measurable data and time.",
        },
        {
            "id": "pr_003",
            "type": "choice",
            "level": "B1",
            "prompt": "Which revision adds a clear scope?",
            "options": [
                "People prefer online classes.",
                "75% of adult learners in our survey preferred online classes.",
            ],
            "answer": "75% of adult learners in our survey preferred online classes.",
            "explanation": "It limits the claim to a specific group.",
        },
        {
            "id": "pr_004",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence avoids vague modifiers?",
            "options": ["Sales increased significantly.", "Sales increased by 12% year over year."],
            "answer": "Sales increased by 12% year over year.",
            "explanation": "Specific numbers replace vague words.",
        },
        {
            "id": "pr_005",
            "type": "choice",
            "level": "B1",
            "prompt": "Which statement is too general?",
            "options": ["All teenagers are addicted to phones.", "Many teens in urban areas use phones for 3+ hours daily."],
            "answer": "All teenagers are addicted to phones.",
            "explanation": "The word \"all\" is an over-generalization.",
        },
        {
            "id": "pr_006",
            "type": "choice",
            "level": "B1",
            "prompt": "Which statement has clearer causality?",
            "options": [
                "After the training, errors dropped by 30%.",
                "Errors dropped because the training changed the workflow, reducing steps from 6 to 3.",
            ],
            "answer": "Errors dropped because the training changed the workflow, reducing steps from 6 to 3.",
            "explanation": "It explains the causal mechanism and specifics.",
        },
        {
            "id": "pr_007",
            "type": "choice",
            "level": "B1",
            "prompt": "Which statement specifies time range?",
            "options": ["The policy improved attendance.", "Attendance rose from 82% to 90% in Q1."],
            "answer": "Attendance rose from 82% to 90% in Q1.",
            "explanation": "Time range and numbers make it precise.",
        },
        {
            "id": "pr_008",
            "type": "choice",
            "level": "B1",
            "prompt": "Which statement is easiest to verify?",
            "options": ["Customers are happier now.", "Customer satisfaction score increased from 3.6 to 4.2."],
            "answer": "Customer satisfaction score increased from 3.6 to 4.2.",
            "explanation": "Numbers and metrics are verifiable.",
        },
    ],
    "intermediate.structure": [
        {
            "id": "st_001",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence is a topic sentence?",
            "options": [
                "There are three reasons to learn coding.",
                "First, coding is fun.",
                "Also, it pays well.",
                "For example, many jobs require it.",
            ],
            "answer": "There are three reasons to learn coding.",
            "explanation": "A topic sentence previews the paragraph's main idea.",
        },
        {
            "id": "st_002",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence best supports the topic: 'Exercise improves mood.'",
            "options": [
                "Studies show a 20-minute walk reduces stress hormones.",
                "Some people dislike gyms.",
                "Exercise can be hard.",
                "Mood is personal.",
            ],
            "answer": "Studies show a 20-minute walk reduces stress hormones.",
            "explanation": "This provides evidence supporting the topic.",
        },
        {
            "id": "st_003",
            "type": "choice",
            "level": "B1",
            "prompt": "Which is a good concluding sentence?",
            "options": [
                "In short, public transport saves time and reduces pollution.",
                "The bus is blue.",
                "There are many cities.",
                "I like cars.",
            ],
            "answer": "In short, public transport saves time and reduces pollution.",
            "explanation": "A conclusion summarizes the main points.",
        },
        {
            "id": "st_004",
            "type": "choice",
            "level": "B1",
            "prompt": "Which transition shows contrast?",
            "options": ["However", "Therefore", "For example", "In addition"],
            "answer": "However",
            "explanation": "However introduces a contrast.",
        },
        {
            "id": "st_005",
            "type": "choice",
            "level": "B1",
            "prompt": "Which outline is best for a paragraph?",
            "options": [
                "Topic sentence -> evidence -> explanation -> conclusion",
                "Conclusion -> evidence -> topic sentence",
                "Evidence only",
                "Examples without topic",
            ],
            "answer": "Topic sentence -> evidence -> explanation -> conclusion",
            "explanation": "This structure is clear and logical.",
        },
        {
            "id": "st_006",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence is a supporting detail?",
            "options": [
                "For example, the library added 200 new books this year.",
                "Libraries are important.",
                "I like books.",
                "This is my opinion.",
            ],
            "answer": "For example, the library added 200 new books this year.",
            "explanation": "This gives concrete support.",
        },
        {
            "id": "st_007",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence best restates the main idea?",
            "options": [
                "Overall, healthy sleep habits improve focus and energy.",
                "Sleep is nice.",
                "I slept late.",
                "Pillows are soft.",
            ],
            "answer": "Overall, healthy sleep habits improve focus and energy.",
            "explanation": "It restates the main idea clearly.",
        },
        {
            "id": "st_008",
            "type": "choice",
            "level": "B1",
            "prompt": "Which transition adds information?",
            "options": ["Moreover", "Instead", "Despite", "Although"],
            "answer": "Moreover",
            "explanation": "Moreover adds another supporting point.",
        },
    ],
    "intermediate.logic": [
        {
            "id": "lg_001",
            "type": "choice",
            "level": "B1",
            "prompt": "Choose the best connector: It was raining, ___ we stayed inside.",
            "options": ["so", "but", "however", "although"],
            "answer": "so",
            "explanation": "So shows cause and result.",
        },
        {
            "id": "lg_002",
            "type": "choice",
            "level": "B1",
            "prompt": "Choose the best connector: He is tired; ___, he will finish the task.",
            "options": ["however", "because", "so", "therefore"],
            "answer": "however",
            "explanation": "However introduces contrast.",
        },
        {
            "id": "lg_003",
            "type": "choice",
            "level": "B1",
            "prompt": "Which word shows example?",
            "options": ["for instance", "therefore", "instead", "despite"],
            "answer": "for instance",
            "explanation": "For instance introduces an example.",
        },
        {
            "id": "lg_004",
            "type": "choice",
            "level": "B1",
            "prompt": "Choose the best connector: We studied hard; ___, we passed the exam.",
            "options": ["as a result", "although", "however", "unless"],
            "answer": "as a result",
            "explanation": "As a result shows outcome.",
        },
        {
            "id": "lg_005",
            "type": "choice",
            "level": "B1",
            "prompt": "Which word shows contrast?",
            "options": ["whereas", "because", "therefore", "since"],
            "answer": "whereas",
            "explanation": "Whereas compares contrasting ideas.",
        },
        {
            "id": "lg_006",
            "type": "choice",
            "level": "B1",
            "prompt": "Choose the best connector: ___ the traffic, we arrived on time.",
            "options": ["Despite", "Because", "So", "If"],
            "answer": "Despite",
            "explanation": "Despite introduces contrast to a difficulty.",
        },
        {
            "id": "lg_007",
            "type": "choice",
            "level": "B1",
            "prompt": "Which connector shows sequence?",
            "options": ["First", "However", "Otherwise", "Meanwhile"],
            "answer": "First",
            "explanation": "First shows order.",
        },
        {
            "id": "lg_008",
            "type": "choice",
            "level": "B1",
            "prompt": "Choose the best connector: He didn't bring an umbrella; ___, he got wet.",
            "options": ["therefore", "although", "while", "yet"],
            "answer": "therefore",
            "explanation": "Therefore shows result.",
        },
    ],
    "intermediate.reading": [
        {
            "id": "rd_001",
            "type": "choice",
            "level": "B1",
            "prompt": "Main idea: 'Many cities are adding bike lanes to reduce traffic and pollution.' What is the main idea?",
            "options": [
                "Cities add bike lanes to reduce traffic and pollution.",
                "Bikes are expensive.",
                "Traffic is fun.",
                "Pollution is blue.",
            ],
            "answer": "Cities add bike lanes to reduce traffic and pollution.",
            "explanation": "This restates the main idea.",
        },
        {
            "id": "rd_002",
            "type": "choice",
            "level": "B1",
            "prompt": "Detail question: 'The report says 60% of users prefer email.' Which is correct?",
            "options": ["Most users prefer email.", "Users prefer phone calls.", "No users prefer email.", "Email is new."],
            "answer": "Most users prefer email.",
            "explanation": "60% means most users.",
        },
        {
            "id": "rd_003",
            "type": "choice",
            "level": "B1",
            "prompt": "Inference: 'Tom wore a coat and scarf.' What can we infer?",
            "options": ["It was cold.", "It was hot.", "It was raining indoors.", "He was swimming."],
            "answer": "It was cold.",
            "explanation": "Coat and scarf suggest cold weather.",
        },
        {
            "id": "rd_004",
            "type": "choice",
            "level": "B1",
            "prompt": "Which is a good title for a text about healthy eating habits?",
            "options": ["Eat Well, Live Well", "The History of Cars", "Mountains and Rivers", "How to Draw"],
            "answer": "Eat Well, Live Well",
            "explanation": "This matches the topic.",
        },
        {
            "id": "rd_005",
            "type": "choice",
            "level": "B1",
            "prompt": "Vocabulary in context: 'The solution was simple.' Simple means ___ .",
            "options": ["easy", "expensive", "dangerous", "strange"],
            "answer": "easy",
            "explanation": "Simple often means easy.",
        },
        {
            "id": "rd_006",
            "type": "choice",
            "level": "B1",
            "prompt": "Which sentence is a fact?",
            "options": ["Water boils at 100°C.", "Pizza is the best food.", "Cats are cute.", "Winter is boring."],
            "answer": "Water boils at 100°C.",
            "explanation": "Facts are verifiable.",
        },
        {
            "id": "rd_007",
            "type": "choice",
            "level": "B1",
            "prompt": "Which is a purpose statement?",
            "options": ["This guide explains how to save energy.", "Energy is important.", "I like guides.", "The guide is green."],
            "answer": "This guide explains how to save energy.",
            "explanation": "It states the purpose.",
        },
        {
            "id": "rd_008",
            "type": "choice",
            "level": "B1",
            "prompt": "Which phrase suggests a conclusion?",
            "options": ["In conclusion", "For example", "Because", "First"],
            "answer": "In conclusion",
            "explanation": "In conclusion signals a wrap-up.",
        },
    ],
    "upper.argument": [
        {
            "id": "ua_001",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a clear claim?",
            "options": [
                "City governments should expand public transit funding.",
                "Public transit exists.",
                "Buses are large.",
                "Some people take the bus.",
            ],
            "answer": "City governments should expand public transit funding.",
            "explanation": "A claim takes a position and can be argued.",
        },
        {
            "id": "ua_002",
            "type": "choice",
            "level": "B2",
            "prompt": "Which sentence is evidence?",
            "options": [
                "Ridership increased 18% after the fare cut.",
                "Transit is important.",
                "Buses are noisy.",
                "People like trains.",
            ],
            "answer": "Ridership increased 18% after the fare cut.",
            "explanation": "Evidence includes data.",
        },
        {
            "id": "ua_003",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a counterargument?",
            "options": [
                "Some argue the budget should focus on roads instead.",
                "We should expand transit.",
                "Transit reduces traffic.",
                "The city is large.",
            ],
            "answer": "Some argue the budget should focus on roads instead.",
            "explanation": "Counterarguments present the opposite view.",
        },
        {
            "id": "ua_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best rebuttal.",
            "options": [
                "However, studies show transit investment reduces long-term road costs.",
                "Roads are long.",
                "Buses are red.",
                "People drive cars.",
            ],
            "answer": "However, studies show transit investment reduces long-term road costs.",
            "explanation": "A rebuttal answers the counterargument with evidence.",
        },
        {
            "id": "ua_005",
            "type": "choice",
            "level": "B2",
            "prompt": "Which transition introduces a concession?",
            "options": ["Although", "Therefore", "For example", "Finally"],
            "answer": "Although",
            "explanation": "Although introduces a concession.",
        },
        {
            "id": "ua_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Which statement is an assumption?",
            "options": ["All commuters will switch to buses.", "The bus line runs every 10 minutes.", "A survey of 500 riders was conducted.", "The budget is $2 million."],
            "answer": "All commuters will switch to buses.",
            "explanation": "It makes an unproven assumption.",
        },
        {
            "id": "ua_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which sentence best summarizes an argument?",
            "options": [
                "Because transit reduces traffic and pollution, the city should invest more in buses and trains.",
                "Traffic is bad.",
                "Buses are good.",
                "The city is big.",
            ],
            "answer": "Because transit reduces traffic and pollution, the city should invest more in buses and trains.",
            "explanation": "It states reasons and the claim.",
        },
        {
            "id": "ua_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is the strongest evidence type?",
            "options": ["Peer-reviewed study results", "Anecdote from one person", "Personal opinion", "A guess"],
            "answer": "Peer-reviewed study results",
            "explanation": "Peer-reviewed studies are reliable evidence.",
        },
    ],
    "upper.academic": [
        {
            "id": "uv_001",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best academic word for 'show':",
            "options": ["demonstrate", "see", "look", "watch"],
            "answer": "demonstrate",
            "explanation": "Demonstrate is more academic than show.",
        },
        {
            "id": "uv_002",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best academic word for 'use':",
            "options": ["utilize", "use", "take", "hold"],
            "answer": "utilize",
            "explanation": "Utilize is a formal alternative to use.",
        },
        {
            "id": "uv_003",
            "type": "choice",
            "level": "B2",
            "prompt": "Which word means 'important' in academic style?",
            "options": ["significant", "big", "huge", "great"],
            "answer": "significant",
            "explanation": "Significant is commonly used in academic writing.",
        },
        {
            "id": "uv_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best academic word for 'about':",
            "options": ["regarding", "around", "near", "close"],
            "answer": "regarding",
            "explanation": "Regarding is more formal than about.",
        },
        {
            "id": "uv_005",
            "type": "choice",
            "level": "B2",
            "prompt": "Which word best replaces 'get' in academic writing?",
            "options": ["obtain", "get", "take", "grab"],
            "answer": "obtain",
            "explanation": "Obtain is more formal.",
        },
        {
            "id": "uv_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best academic word for 'idea':",
            "options": ["concept", "thing", "stuff", "thought"],
            "answer": "concept",
            "explanation": "Concept is more academic.",
        },
        {
            "id": "uv_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which word means 'increase' in academic style?",
            "options": ["increase", "go up", "get bigger", "rise up"],
            "answer": "increase",
            "explanation": "Increase is formal and precise.",
        },
        {
            "id": "uv_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best academic phrase for 'more and more':",
            "options": ["an increasing number of", "lots of", "many many", "a lot"],
            "answer": "an increasing number of",
            "explanation": "This is formal and precise.",
        },
    ],
    "upper.style": [
        {
            "id": "us_001",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the most natural phrasing.",
            "options": ["It depends on the situation.", "It depends of the situation.", "It depends from the situation.", "It depends at the situation."],
            "answer": "It depends on the situation.",
            "explanation": "The correct preposition is 'on'.",
        },
        {
            "id": "us_002",
            "type": "choice",
            "level": "B2",
            "prompt": "Which sentence is more concise?",
            "options": ["We need to reduce costs.", "We need to make costs go down."],
            "answer": "We need to reduce costs.",
            "explanation": "Reduce is more concise.",
        },
        {
            "id": "us_003",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the formal option.",
            "options": ["purchase", "buy", "get", "pick up"],
            "answer": "purchase",
            "explanation": "Purchase is formal.",
        },
        {
            "id": "us_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the best register for an email to a professor.",
            "options": ["I would appreciate your feedback.", "Hey, check this out.", "Yo, can you see this?", "This is awesome."],
            "answer": "I would appreciate your feedback.",
            "explanation": "This is polite and formal.",
        },
        {
            "id": "us_005",
            "type": "choice",
            "level": "B2",
            "prompt": "Which sentence avoids redundancy?",
            "options": ["The final outcome was positive.", "The outcome was positive.", "The end result outcome was positive.", "The final end was positive."],
            "answer": "The outcome was positive.",
            "explanation": "Avoid repeating the same idea.",
        },
        {
            "id": "us_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Choose the more natural collocation.",
            "options": ["make a decision", "do a decision", "take a decision", "create a decision"],
            "answer": "make a decision",
            "explanation": "Make a decision is the standard collocation.",
        },
        {
            "id": "us_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which sentence is more fluent?",
            "options": ["I look forward to hearing from you.", "I look forward to hear from you.", "I look forward hearing from you.", "I look forward for hearing from you."],
            "answer": "I look forward to hearing from you.",
            "explanation": "Look forward to + gerund.",
        },
        {
            "id": "us_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is the most natural closing?",
            "options": ["Best regards,", "Bye bye", "See ya", "Peace"],
            "answer": "Best regards,",
            "explanation": "Best regards is formal and natural.",
        },
    ],
    "upper.presentation": [
        {
            "id": "up_001",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a strong opening line?",
            "options": [
                "Today I'd like to share three key findings from our study.",
                "I will talk now.",
                "Hello.",
                "Okay.",
            ],
            "answer": "Today I'd like to share three key findings from our study.",
            "explanation": "It previews the structure and purpose.",
        },
        {
            "id": "up_002",
            "type": "choice",
            "level": "B2",
            "prompt": "Which transition signals a new section?",
            "options": ["Let's move on to the next point.", "In summary", "For example", "Because"],
            "answer": "Let's move on to the next point.",
            "explanation": "It signals a new section.",
        },
        {
            "id": "up_003",
            "type": "choice",
            "level": "B2",
            "prompt": "Which sentence engages the audience?",
            "options": ["Have you ever felt overwhelmed by choices?", "Here is my slide.", "This is data.", "Okay."],
            "answer": "Have you ever felt overwhelmed by choices?",
            "explanation": "Questions engage the audience.",
        },
        {
            "id": "up_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a clear conclusion?",
            "options": ["To conclude, these steps reduce churn by 12%.", "Next slide.", "Maybe that's it.", "That's all."],
            "answer": "To conclude, these steps reduce churn by 12%.",
            "explanation": "It summarizes with a key result.",
        },
        {
            "id": "up_005",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is best for explaining a chart?",
            "options": ["As you can see, sales peaked in July.", "This is a chart.", "Blue is nice.", "Numbers are here."],
            "answer": "As you can see, sales peaked in July.",
            "explanation": "It highlights a key trend.",
        },
        {
            "id": "up_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Which phrase invites questions?",
            "options": ["I'm happy to take questions.", "No questions.", "Stop now.", "Next."],
            "answer": "I'm happy to take questions.",
            "explanation": "It invites Q&A politely.",
        },
        {
            "id": "up_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which phrase signals emphasis?",
            "options": ["The key point is...", "Maybe", "Sort of", "Kind of"],
            "answer": "The key point is...",
            "explanation": "It highlights importance.",
        },
        {
            "id": "up_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a smooth handoff to a demo?",
            "options": ["Now, let's jump into a quick demo.", "Demo.", "Here it is.", "Look."],
            "answer": "Now, let's jump into a quick demo.",
            "explanation": "It transitions clearly.",
        },
    ],
    "advanced.critical": [
        {
            "id": "ac_001",
            "type": "choice",
            "level": "C1",
            "prompt": "Which question best checks evidence quality?",
            "options": ["Is the sample size large enough?", "Is the paper long?", "Is the font nice?", "Is the topic fun?"],
            "answer": "Is the sample size large enough?",
            "explanation": "Sample size affects reliability.",
        },
        {
            "id": "ac_002",
            "type": "choice",
            "level": "C1",
            "prompt": "Which statement identifies bias?",
            "options": ["The survey only included online users.", "The results are interesting.", "The chart is colorful.", "The report is new."],
            "answer": "The survey only included online users.",
            "explanation": "A limited sample can introduce bias.",
        },
        {
            "id": "ac_003",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is a logical fallacy?",
            "options": ["Either we ban phones or students will fail.", "We reduced noise by adding panels.", "A controlled study found a 10% increase.", "The data were collected in May."],
            "answer": "Either we ban phones or students will fail.",
            "explanation": "This is a false dilemma.",
        },
        {
            "id": "ac_004",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence separates correlation from causation?",
            "options": ["The variables moved together, but causality wasn't established.", "A caused B.", "B caused A.", "They are the same."],
            "answer": "The variables moved together, but causality wasn't established.",
            "explanation": "It acknowledges correlation without causal claim.",
        },
        {
            "id": "ac_005",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is a strong critique?",
            "options": ["The methodology lacks a control group.", "I don't like it.", "It's boring.", "The author is wrong."],
            "answer": "The methodology lacks a control group.",
            "explanation": "It targets a methodological issue.",
        },
        {
            "id": "ac_006",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is the most credible source?",
            "options": ["A peer-reviewed journal article", "A random blog", "An anonymous comment", "A rumor"],
            "answer": "A peer-reviewed journal article",
            "explanation": "Peer review improves credibility.",
        },
        {
            "id": "ac_007",
            "type": "choice",
            "level": "C1",
            "prompt": "Which question checks generalizability?",
            "options": ["Can these results apply to other populations?", "Is the title catchy?", "Is the chart blue?", "Is it short?"],
            "answer": "Can these results apply to other populations?",
            "explanation": "Generalizability is about applying results broadly.",
        },
        {
            "id": "ac_008",
            "type": "choice",
            "level": "C1",
            "prompt": "Which statement shows balanced evaluation?",
            "options": ["The study is strong in design but limited by sample size.", "The study is perfect.", "The study is useless.", "The study is fine."],
            "answer": "The study is strong in design but limited by sample size.",
            "explanation": "It notes strengths and limitations.",
        },
    ],
    "advanced.complex": [
        {
            "id": "cx_001",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct sentence.",
            "options": [
                "The report that you sent yesterday was helpful.",
                "The report that you sent yesterday were helpful.",
                "The report which you sent yesterday are helpful.",
                "The report you sent yesterday were helpful.",
            ],
            "answer": "The report that you sent yesterday was helpful.",
            "explanation": "Subject-verb agreement with singular report.",
        },
        {
            "id": "cx_002",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the best reduced relative clause.",
            "options": ["The data collected last year are incomplete.", "The data which collected last year are incomplete.", "The data collected last year is incomplete.", "The data that collecting last year are incomplete."],
            "answer": "The data collected last year are incomplete.",
            "explanation": "Reduced clause uses past participle.",
        },
        {
            "id": "cx_003",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct inversion.",
            "options": ["Not only did she finish, but she also won.", "Not only she did finish, but she also won.", "Not only finished she, but she also won.", "Not only she finished, but she also won."],
            "answer": "Not only did she finish, but she also won.",
            "explanation": "Inversion uses auxiliary before subject.",
        },
        {
            "id": "cx_004",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct sentence with a participle clause.",
            "options": ["Having finished the report, he went home.", "Finished the report, he goes home.", "Having finish the report, he went home.", "Finished he the report, he went home."],
            "answer": "Having finished the report, he went home.",
            "explanation": "Use having + past participle.",
        },
        {
            "id": "cx_005",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct sentence.",
            "options": ["Had I known, I would have called.", "Had I know, I would have called.", "If I had knew, I would have called.", "Had I known, I would call."],
            "answer": "Had I known, I would have called.",
            "explanation": "Third conditional inversion is correct.",
        },
        {
            "id": "cx_006",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct nominalization.",
            "options": ["The implementation of the policy was delayed.", "The policy implemented was delayed.", "The implement of the policy was delayed.", "The policy implementation were delayed."],
            "answer": "The implementation of the policy was delayed.",
            "explanation": "Implementation is the correct noun form.",
        },
        {
            "id": "cx_007",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct cleft sentence.",
            "options": ["What she needed was a quiet room.", "What she needed was quiet room.", "What she needs was a quiet room.", "What she needed is a quiet room."],
            "answer": "What she needed was a quiet room.",
            "explanation": "Past tense consistency in cleft sentence.",
        },
        {
            "id": "cx_008",
            "type": "choice",
            "level": "C1",
            "prompt": "Choose the correct sentence with a relative clause.",
            "options": ["The team, which won last year, returned.", "The team, which win last year, returned.", "The team, who won last year, returned.", "The team, which won last year, return."],
            "answer": "The team, which won last year, returned.",
            "explanation": "Use which for non-human and past tense won.",
        },
    ],
    "advanced.rhetoric": [
        {
            "id": "rh_001",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence uses parallelism?",
            "options": ["We must plan, act, and reflect.", "We must plan, acting, and reflection.", "We must plan and action and reflect.", "We must plan, and we reflect."],
            "answer": "We must plan, act, and reflect.",
            "explanation": "Parallel verb forms create rhythm.",
        },
        {
            "id": "rh_002",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is a rhetorical question?",
            "options": ["How can we ignore the evidence?", "Where is the station?", "What time is it?", "Who is she?"],
            "answer": "How can we ignore the evidence?",
            "explanation": "It is asked for effect, not an answer.",
        },
        {
            "id": "rh_003",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence uses emphasis by repetition?",
            "options": ["We need action, action, action.", "We need action once.", "We need action maybe.", "We need action quietly."],
            "answer": "We need action, action, action.",
            "explanation": "Repetition adds emphasis.",
        },
        {
            "id": "rh_004",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is a metaphor?",
            "options": ["Time is a thief.", "Time is late.", "Time is 5 p.m.", "Time is measured."],
            "answer": "Time is a thief.",
            "explanation": "It compares time to a thief.",
        },
        {
            "id": "rh_005",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence softens tone?",
            "options": ["It may be worth considering another approach.", "You are wrong.", "This is bad.", "Stop this."],
            "answer": "It may be worth considering another approach.",
            "explanation": "Hedging softens the statement.",
        },
        {
            "id": "rh_006",
            "type": "choice",
            "level": "C1",
            "prompt": "Which phrase signals contrast for emphasis?",
            "options": ["Not only...but also", "Because of", "For example", "As a result"],
            "answer": "Not only...but also",
            "explanation": "It emphasizes by contrasting and adding.",
        },
        {
            "id": "rh_007",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence uses antithesis?",
            "options": ["We must learn to live together or we will die alone.", "We must learn to live together.", "We must learn.", "We must live."],
            "answer": "We must learn to live together or we will die alone.",
            "explanation": "It contrasts two opposite outcomes.",
        },
        {
            "id": "rh_008",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is the best concise restatement?",
            "options": ["In short, clarity strengthens persuasion.", "In a very long way, clarity is good.", "Clarity is good, good, good.", "Clarity is like a thing."],
            "answer": "In short, clarity strengthens persuasion.",
            "explanation": "It is concise and formal.",
        },
    ],
    "advanced.synthesis": [
        {
            "id": "sy_001",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence best synthesizes two sources?",
            "options": [
                "Source A notes rising costs, while Source B attributes them to supply shortages.",
                "Source A is long.",
                "Source B is new.",
                "Sources are interesting.",
            ],
            "answer": "Source A notes rising costs, while Source B attributes them to supply shortages.",
            "explanation": "It combines ideas from both sources.",
        },
        {
            "id": "sy_002",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is an appropriate citation phrase?",
            "options": ["According to the 2022 report, ...", "People say ...", "I heard ...", "Maybe ..."],
            "answer": "According to the 2022 report, ...",
            "explanation": "It attributes information clearly.",
        },
        {
            "id": "sy_003",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence avoids plagiarism?",
            "options": ["The study suggests that sleep improves memory.", "Copying the sentence word for word.", "Using the same wording without citation.", "Repeating the exact line."],
            "answer": "The study suggests that sleep improves memory.",
            "explanation": "It paraphrases the idea.",
        },
        {
            "id": "sy_004",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is the best synthesis statement?",
            "options": [
                "Together, the studies indicate that early feedback improves retention.",
                "The first study is good.",
                "The second study is good.",
                "Both are okay.",
            ],
            "answer": "Together, the studies indicate that early feedback improves retention.",
            "explanation": "It combines evidence to make a unified claim.",
        },
        {
            "id": "sy_005",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is a good comparison structure?",
            "options": ["While Source A focuses on cost, Source B emphasizes access.", "Source A is cost.", "Source B is access.", "Sources are different."],
            "answer": "While Source A focuses on cost, Source B emphasizes access.",
            "explanation": "It clearly compares focus areas.",
        },
        {
            "id": "sy_006",
            "type": "choice",
            "level": "C1",
            "prompt": "Which is a balanced synthesis?",
            "options": ["The data are promising, yet the sample size is limited.", "The data prove everything.", "The data are useless.", "The data are perfect."],
            "answer": "The data are promising, yet the sample size is limited.",
            "explanation": "It presents both strengths and limits.",
        },
        {
            "id": "sy_007",
            "type": "choice",
            "level": "C1",
            "prompt": "Which sentence integrates evidence and interpretation?",
            "options": ["The survey found 62% support, suggesting growing acceptance.", "The survey found 62% support.", "Support is high.", "People like it."],
            "answer": "The survey found 62% support, suggesting growing acceptance.",
            "explanation": "It combines data with interpretation.",
        },
        {
            "id": "sy_008",
            "type": "choice",
            "level": "C1",
            "prompt": "Which closing sentence synthesizes?",
            "options": ["Overall, both sources show that early practice boosts fluency.", "Both sources exist.", "Practice is good.", "Sources are done."],
            "answer": "Overall, both sources show that early practice boosts fluency.",
            "explanation": "It synthesizes both sources into one conclusion.",
        },
    ],
    "ielts.listening": [
        {
            "id": "il_001",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is the best listening strategy for map questions?",
            "options": ["Follow directions and landmarks", "Translate every word", "Ignore the map", "Guess randomly"],
            "answer": "Follow directions and landmarks",
            "explanation": "Map questions rely on landmarks and directions.",
        },
        {
            "id": "il_002",
            "type": "choice",
            "level": "B2",
            "prompt": "What should you write for a phone number?",
            "options": ["Numbers exactly as heard", "Spelled-out words", "A summary", "Only the area code"],
            "answer": "Numbers exactly as heard",
            "explanation": "Write numbers exactly as heard.",
        },
        {
            "id": "il_003",
            "type": "choice",
            "level": "B2",
            "prompt": "Which helps with multiple-choice listening?",
            "options": ["Preview the options first", "Close your eyes", "Skip the question", "Write long notes"],
            "answer": "Preview the options first",
            "explanation": "Previewing options helps focus on key info.",
        },
        {
            "id": "il_004",
            "type": "choice",
            "level": "B2",
            "prompt": "When you miss an answer, you should ___.",
            "options": ["Move on quickly", "Stop and panic", "Rewind", "Ask the speaker"],
            "answer": "Move on quickly",
            "explanation": "IELTS listening keeps moving; don't get stuck.",
        },
        {
            "id": "il_005",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a signpost word for a correction?",
            "options": ["Actually", "Furthermore", "However", "Similarly"],
            "answer": "Actually",
            "explanation": "Actually often signals a correction.",
        },
        {
            "id": "il_006",
            "type": "choice",
            "level": "B2",
            "prompt": "What is the best note-taking style?",
            "options": ["Short keywords", "Full sentences", "No notes", "Long paragraphs"],
            "answer": "Short keywords",
            "explanation": "Keywords are faster and clearer.",
        },
        {
            "id": "il_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a common distractor?",
            "options": ["A number is mentioned, then corrected", "The final answer is repeated", "The speaker spells it twice", "The answer is written"],
            "answer": "A number is mentioned, then corrected",
            "explanation": "Distractors often include corrections.",
        },
        {
            "id": "il_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is best for Section 4?",
            "options": ["Focus on academic vocabulary", "Ignore key terms", "Only listen for names", "Wait until the end"],
            "answer": "Focus on academic vocabulary",
            "explanation": "Section 4 is academic lecture style.",
        },
    ],
    "ielts.reading": [
        {
            "id": "ir_001",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good skimming strategy?",
            "options": ["Read the first sentence of each paragraph", "Translate every word", "Read backwards", "Skip headings"],
            "answer": "Read the first sentence of each paragraph",
            "explanation": "Skimming focuses on topic sentences.",
        },
        {
            "id": "ir_002",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good scanning strategy?",
            "options": ["Look for numbers or names", "Read slowly line by line", "Ignore keywords", "Close the passage"],
            "answer": "Look for numbers or names",
            "explanation": "Scanning targets specific details.",
        },
        {
            "id": "ir_003",
            "type": "choice",
            "level": "B2",
            "prompt": "What should you do when you see a paraphrase in a question?",
            "options": ["Find synonyms in the text", "Stop reading", "Guess immediately", "Skip the question"],
            "answer": "Find synonyms in the text",
            "explanation": "IELTS uses paraphrasing in questions.",
        },
        {
            "id": "ir_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a True/False/Not Given tip?",
            "options": ["Answer only from the text", "Use outside knowledge", "Assume it's true", "Guess all"],
            "answer": "Answer only from the text",
            "explanation": "T/F/NG depends on text evidence.",
        },
        {
            "id": "ir_005",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good time-management rule?",
            "options": ["Move on if stuck", "Spend 10 minutes on one question", "Read dictionary definitions", "Rewrite the passage"],
            "answer": "Move on if stuck",
            "explanation": "Time is limited; keep moving.",
        },
        {
            "id": "ir_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a matching headings strategy?",
            "options": ["Identify the main idea of each paragraph", "Match by first word", "Count sentences", "Choose random"],
            "answer": "Identify the main idea of each paragraph",
            "explanation": "Headings summarize main ideas.",
        },
        {
            "id": "ir_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a sign of a distractor?",
            "options": ["Similar wording but different meaning", "Exact match", "Clear synonym", "Direct quote"],
            "answer": "Similar wording but different meaning",
            "explanation": "Distractors look similar but are incorrect.",
        },
        {
            "id": "ir_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Which question type often requires locating specific details?",
            "options": ["Short-answer questions", "Essay questions", "Opinion questions", "Summary writing"],
            "answer": "Short-answer questions",
            "explanation": "Short answers require specific details.",
        },
    ],
    "ielts.writing": [
        {
            "id": "iw_001",
            "type": "choice",
            "level": "B2",
            "prompt": "What is the purpose of Task 1 (Academic)?",
            "options": ["Describe visual information", "Argue an opinion", "Tell a story", "Write a letter"],
            "answer": "Describe visual information",
            "explanation": "Task 1 Academic summarizes charts/graphs.",
        },
        {
            "id": "iw_002",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good Task 2 structure?",
            "options": ["Introduction -> body -> conclusion", "Only conclusion", "Only examples", "Random ideas"],
            "answer": "Introduction -> body -> conclusion",
            "explanation": "A clear structure is required.",
        },
        {
            "id": "iw_003",
            "type": "choice",
            "level": "B2",
            "prompt": "What should the introduction include?",
            "options": ["Paraphrase the question and thesis", "New data", "All examples", "A full summary"],
            "answer": "Paraphrase the question and thesis",
            "explanation": "Introduce topic and position.",
        },
        {
            "id": "iw_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good overview sentence for Task 1?",
            "options": ["Overall, sales rose while costs fell.", "The chart is blue.", "There are many lines.", "I like charts."],
            "answer": "Overall, sales rose while costs fell.",
            "explanation": "Overview summarizes main trends.",
        },
        {
            "id": "iw_005",
            "type": "choice",
            "level": "B2",
            "prompt": "What is a common error to avoid in Task 1?",
            "options": ["Giving opinions", "Using past tense", "Using numbers", "Summarizing"],
            "answer": "Giving opinions",
            "explanation": "Task 1 should be objective.",
        },
        {
            "id": "iw_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a cohesive device?",
            "options": ["Moreover", "Table", "Figure", "Data"],
            "answer": "Moreover",
            "explanation": "Moreover links ideas.",
        },
        {
            "id": "iw_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a strong thesis statement?",
            "options": ["This essay argues that public transport should be subsidized.", "Public transport exists.", "I will talk about buses.", "Transport is good."],
            "answer": "This essay argues that public transport should be subsidized.",
            "explanation": "It states a clear position.",
        },
        {
            "id": "iw_008",
            "type": "choice",
            "level": "B2",
            "prompt": "What is the best way to support a point?",
            "options": ["Explain and give an example", "Repeat the same idea", "Add unrelated facts", "End early"],
            "answer": "Explain and give an example",
            "explanation": "Support requires explanation and evidence.",
        },
    ],
    "ielts.speaking": [
        {
            "id": "is_001",
            "type": "choice",
            "level": "B2",
            "prompt": "In Part 1, you should ___.",
            "options": ["Answer briefly and naturally", "Give a long speech", "Stay silent", "Only say yes/no"],
            "answer": "Answer briefly and naturally",
            "explanation": "Part 1 is short personal questions.",
        },
        {
            "id": "is_002",
            "type": "choice",
            "level": "B2",
            "prompt": "In Part 2, you should ___.",
            "options": ["Use the 1-minute prep time", "Start immediately", "Refuse to speak", "Ask for the answers"],
            "answer": "Use the 1-minute prep time",
            "explanation": "Preparation time helps structure the talk.",
        },
        {
            "id": "is_003",
            "type": "choice",
            "level": "B2",
            "prompt": "Which helps fluency?",
            "options": ["Using fillers like 'well' or 'let me think'", "Stopping often", "Only one-word answers", "Speaking too fast"],
            "answer": "Using fillers like 'well' or 'let me think'",
            "explanation": "Fillers give time without long pauses.",
        },
        {
            "id": "is_004",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good way to extend an answer?",
            "options": ["Give a reason and example", "Repeat the same word", "Say 'no comment'", "Stop"],
            "answer": "Give a reason and example",
            "explanation": "Expansion improves coherence.",
        },
        {
            "id": "is_005",
            "type": "choice",
            "level": "B2",
            "prompt": "What should you do if you don't understand a question?",
            "options": ["Ask for clarification", "Stay silent", "Change topic", "End the test"],
            "answer": "Ask for clarification",
            "explanation": "You can ask the examiner to repeat or clarify.",
        },
        {
            "id": "is_006",
            "type": "choice",
            "level": "B2",
            "prompt": "Which phrase signals opinion?",
            "options": ["In my view", "Because", "However", "For example"],
            "answer": "In my view",
            "explanation": "In my view introduces opinion.",
        },
        {
            "id": "is_007",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a good closing for Part 2?",
            "options": ["That's why it was memorable for me.", "I don't know.", "Stop.", "Next."],
            "answer": "That's why it was memorable for me.",
            "explanation": "It wraps up the talk.",
        },
        {
            "id": "is_008",
            "type": "choice",
            "level": "B2",
            "prompt": "Which is a linking phrase?",
            "options": ["On the other hand", "Table", "Number", "Color"],
            "answer": "On the other hand",
            "explanation": "It links contrasting ideas.",
        },
    ],
}
