QUESTIONS = {}

QUESTIONS["es.starter.alphabet"] = [
    # 10题，字母发音
    {"id": "es_al_001", "type": "choice", "level": "A0",
     "prompt": "字母 A 的发音是？",
     "options": ["a", "e", "i", "o"],
     "answer": "a",
     "explanation": "ES: La A se pronuncia /a/ | ZH: A发a音"},
    {"id": "es_al_002", "type": "choice", "level": "A0",
     "prompt": "字母 E 的发音是？",
     "options": ["e", "a", "i", "u"],
     "answer": "e",
     "explanation": "ES: La E se pronuncia /e/ | ZH: E发e音"},
    {"id": "es_al_003", "type": "choice", "level": "A0",
     "prompt": "字母 I 的发音是？",
     "options": ["i", "e", "o", "a"],
     "answer": "i",
     "explanation": "ES: La I se pronuncia /i/ | ZH: I发i音"},
    {"id": "es_al_004", "type": "choice", "level": "A0",
     "prompt": "字母 O 的发音是？",
     "options": ["o", "u", "a", "e"],
     "answer": "o",
     "explanation": "ES: La O se pronuncia /o/ | ZH: O发o音"},
    {"id": "es_al_005", "type": "choice", "level": "A0",
     "prompt": "字母 U 的发音是？",
     "options": ["u", "o", "i", "e"],
     "answer": "u",
     "explanation": "ES: La U se pronuncia /u/ | ZH: U发u音"},
    {"id": "es_al_006", "type": "choice", "level": "A0",
     "prompt": "字母 B 的名称读作？",
     "options": ["be", "de", "pe", "ve"],
     "answer": "be",
     "explanation": "ES: La B se llama be | ZH: B读作be"},
    {"id": "es_al_007", "type": "choice", "level": "A0",
     "prompt": "字母 C 的名称读作？",
     "options": ["ce", "se", "ge", "che"],
     "answer": "ce",
     "explanation": "ES: La C se llama ce | ZH: C读作ce"},
    {"id": "es_al_008", "type": "choice", "level": "A0",
     "prompt": "字母 D 的名称读作？",
     "options": ["de", "te", "pe", "ge"],
     "answer": "de",
     "explanation": "ES: La D se llama de | ZH: D读作de"},
    {"id": "es_al_009", "type": "choice", "level": "A0",
     "prompt": "字母 F 的名称读作？",
     "options": ["efe", "ele", "eme", "ene"],
     "answer": "efe",
     "explanation": "ES: La F se llama efe | ZH: F读作efe"},
    {"id": "es_al_010", "type": "choice", "level": "A0",
     "prompt": "字母 G 的名称读作？",
     "options": ["ge", "je", "gue", "gi"],
     "answer": "ge",
     "explanation": "ES: La G se llama ge | ZH: G读作ge"},
]

QUESTIONS["es.starter.greetings"] = [
    # 10题，问候
    {"id": "es_gr_001", "type": "choice", "level": "A0",
     "prompt": "“你好”是？",
     "options": ["Hola", "Adios", "Gracias", "Perdon"],
     "answer": "Hola",
     "explanation": "ES: Hola es saludo informal | ZH: 常用你好"},
    {"id": "es_gr_002", "type": "choice", "level": "A0",
     "prompt": "“早上好”是？",
     "options": ["Buenos dias", "Buenas noches", "Buenas tardes", "Hasta luego"],
     "answer": "Buenos dias",
     "explanation": "ES: Buenos dias es saludo matinal | ZH: 早上好"},
    {"id": "es_gr_003", "type": "choice", "level": "A0",
     "prompt": "“下午好”是？",
     "options": ["Buenas tardes", "Buenos dias", "Buenas noches", "De nada"],
     "answer": "Buenas tardes",
     "explanation": "ES: Buenas tardes es saludo de tarde | ZH: 下午好"},
    {"id": "es_gr_004", "type": "choice", "level": "A0",
     "prompt": "“晚安/晚上好”是？",
     "options": ["Buenas noches", "Buenas tardes", "Buenos dias", "Por favor"],
     "answer": "Buenas noches",
     "explanation": "ES: Buenas noches se usa de noche | ZH: 晚上好/晚安"},
    {"id": "es_gr_005", "type": "choice", "level": "A0",
     "prompt": "“再见”是？",
     "options": ["Adios", "Hola", "Salud", "Bien"],
     "answer": "Adios",
     "explanation": "ES: Adios es despedida | ZH: 再见"},
    {"id": "es_gr_006", "type": "choice", "level": "A0",
     "prompt": "“一会儿见”是？",
     "options": ["Hasta luego", "Hasta manana", "Buenos dias", "Gracias"],
     "answer": "Hasta luego",
     "explanation": "ES: Hasta luego significa hasta mas tarde | ZH: 一会儿见"},
    {"id": "es_gr_007", "type": "choice", "level": "A0",
     "prompt": "“谢谢”是？",
     "options": ["Gracias", "Perdon", "Por favor", "Lo siento"],
     "answer": "Gracias",
     "explanation": "ES: Gracias es agradecimiento | ZH: 谢谢"},
    {"id": "es_gr_008", "type": "choice", "level": "A0",
     "prompt": "“不客气”是？",
     "options": ["De nada", "Lo siento", "Buenas", "Mucho gusto"],
     "answer": "De nada",
     "explanation": "ES: De nada responde a gracias | ZH: 不客气"},
    {"id": "es_gr_009", "type": "choice", "level": "A0",
     "prompt": "“请”是？",
     "options": ["Por favor", "Perdon", "Salud", "Hasta pronto"],
     "answer": "Por favor",
     "explanation": "ES: Por favor es pedir con cortesia | ZH: 请"},
    {"id": "es_gr_010", "type": "choice", "level": "A0",
     "prompt": "“很高兴认识你”是？",
     "options": ["Mucho gusto", "Hasta luego", "Buenos dias", "Adios"],
     "answer": "Mucho gusto",
     "explanation": "ES: Mucho gusto al conocer | ZH: 很高兴认识你"},
]

QUESTIONS["es.starter.numbers"] = [
    # 10题，数字
    {"id": "es_nb_001", "type": "choice", "level": "A0",
     "prompt": "数字1是？",
     "options": ["uno", "dos", "tres", "cuatro"],
     "answer": "uno",
     "explanation": "ES: uno es 1 | ZH: 数字1"},
    {"id": "es_nb_002", "type": "choice", "level": "A0",
     "prompt": "数字2是？",
     "options": ["dos", "uno", "cinco", "siete"],
     "answer": "dos",
     "explanation": "ES: dos es 2 | ZH: 数字2"},
    {"id": "es_nb_003", "type": "choice", "level": "A0",
     "prompt": "数字3是？",
     "options": ["tres", "cuatro", "seis", "ocho"],
     "answer": "tres",
     "explanation": "ES: tres es 3 | ZH: 数字3"},
    {"id": "es_nb_004", "type": "choice", "level": "A0",
     "prompt": "数字4是？",
     "options": ["cuatro", "tres", "nueve", "diez"],
     "answer": "cuatro",
     "explanation": "ES: cuatro es 4 | ZH: 数字4"},
    {"id": "es_nb_005", "type": "choice", "level": "A0",
     "prompt": "数字5是？",
     "options": ["cinco", "siete", "ocho", "nueve"],
     "answer": "cinco",
     "explanation": "ES: cinco es 5 | ZH: 数字5"},
    {"id": "es_nb_006", "type": "choice", "level": "A0",
     "prompt": "数字6是？",
     "options": ["seis", "cinco", "siete", "dos"],
     "answer": "seis",
     "explanation": "ES: seis es 6 | ZH: 数字6"},
    {"id": "es_nb_007", "type": "choice", "level": "A0",
     "prompt": "数字7是？",
     "options": ["siete", "seis", "ocho", "tres"],
     "answer": "siete",
     "explanation": "ES: siete es 7 | ZH: 数字7"},
    {"id": "es_nb_008", "type": "choice", "level": "A0",
     "prompt": "数字8是？",
     "options": ["ocho", "siete", "nueve", "cuatro"],
     "answer": "ocho",
     "explanation": "ES: ocho es 8 | ZH: 数字8"},
    {"id": "es_nb_009", "type": "choice", "level": "A0",
     "prompt": "数字9是？",
     "options": ["nueve", "ocho", "siete", "cinco"],
     "answer": "nueve",
     "explanation": "ES: nueve es 9 | ZH: 数字9"},
    {"id": "es_nb_010", "type": "choice", "level": "A0",
     "prompt": "数字10是？",
     "options": ["diez", "nueve", "doce", "once"],
     "answer": "diez",
     "explanation": "ES: diez es 10 | ZH: 数字10"},
]

QUESTIONS["es.elementary.gender_nouns"] = [
    # 10题，名词性别（el/la）
    {"id": "es_gn_001", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ libro”",
     "options": ["el", "la", "los", "las"],
     "answer": "el",
     "explanation": "ES: libro es masculino | ZH: libro为阳性"},
    {"id": "es_gn_002", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ casa”",
     "options": ["la", "el", "los", "un"],
     "answer": "la",
     "explanation": "ES: casa es femenino | ZH: casa为阴性"},
    {"id": "es_gn_003", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ estudiante (男)”",
     "options": ["el", "la", "una", "las"],
     "answer": "el",
     "explanation": "ES: estudiante masculino usa el | ZH: 男生用el"},
    {"id": "es_gn_004", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ estudiante (女)”",
     "options": ["la", "el", "un", "los"],
     "answer": "la",
     "explanation": "ES: estudiante femenino usa la | ZH: 女生用la"},
    {"id": "es_gn_005", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ problema”",
     "options": ["el", "la", "las", "una"],
     "answer": "el",
     "explanation": "ES: problema es masculino | ZH: 虽然结尾a，但为阳性"},
    {"id": "es_gn_006", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ mano”",
     "options": ["la", "el", "los", "unas"],
     "answer": "la",
     "explanation": "ES: mano es femenino | ZH: mano为阴性"},
    {"id": "es_gn_007", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ dia”",
     "options": ["el", "la", "una", "las"],
     "answer": "el",
     "explanation": "ES: dia es masculino | ZH: dia为阳性"},
    {"id": "es_gn_008", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ flor”",
     "options": ["la", "el", "los", "unos"],
     "answer": "la",
     "explanation": "ES: flor es femenino | ZH: flor为阴性"},
    {"id": "es_gn_009", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ hotel”",
     "options": ["el", "la", "las", "una"],
     "answer": "el",
     "explanation": "ES: hotel es masculino | ZH: hotel为阳性"},
    {"id": "es_gn_010", "type": "choice", "level": "A1",
     "prompt": "选择正确的冠词：“__ noche”",
     "options": ["la", "el", "los", "un"],
     "answer": "la",
     "explanation": "ES: noche es femenino | ZH: noche为阴性"},
]

QUESTIONS["es.elementary.family"] = [
    # 10题，家庭
    {"id": "es_fa_001", "type": "choice", "level": "A1",
     "prompt": "“父亲”是？",
     "options": ["padre", "madre", "hermano", "hijo"],
     "answer": "padre",
     "explanation": "ES: padre es padre | ZH: 父亲"},
    {"id": "es_fa_002", "type": "choice", "level": "A1",
     "prompt": "“母亲”是？",
     "options": ["madre", "padre", "hija", "tio"],
     "answer": "madre",
     "explanation": "ES: madre es madre | ZH: 母亲"},
    {"id": "es_fa_003", "type": "choice", "level": "A1",
     "prompt": "“哥哥/弟弟”是？",
     "options": ["hermano", "hermana", "abuelo", "prima"],
     "answer": "hermano",
     "explanation": "ES: hermano es hermano | ZH: 兄弟"},
    {"id": "es_fa_004", "type": "choice", "level": "A1",
     "prompt": "“姐姐/妹妹”是？",
     "options": ["hermana", "hermano", "abuela", "hijo"],
     "answer": "hermana",
     "explanation": "ES: hermana es hermana | ZH: 姐妹"},
    {"id": "es_fa_005", "type": "choice", "level": "A1",
     "prompt": "“儿子”是？",
     "options": ["hijo", "hija", "nieto", "tio"],
     "answer": "hijo",
     "explanation": "ES: hijo es hijo | ZH: 儿子"},
    {"id": "es_fa_006", "type": "choice", "level": "A1",
     "prompt": "“女儿”是？",
     "options": ["hija", "hijo", "nieta", "tio"],
     "answer": "hija",
     "explanation": "ES: hija es hija | ZH: 女儿"},
    {"id": "es_fa_007", "type": "choice", "level": "A1",
     "prompt": "“爷爷/外公”是？",
     "options": ["abuelo", "abuela", "tio", "primo"],
     "answer": "abuelo",
     "explanation": "ES: abuelo es abuelo | ZH: 祖父/外公"},
    {"id": "es_fa_008", "type": "choice", "level": "A1",
     "prompt": "“奶奶/外婆”是？",
     "options": ["abuela", "abuelo", "tia", "prima"],
     "answer": "abuela",
     "explanation": "ES: abuela es abuela | ZH: 祖母/外婆"},
    {"id": "es_fa_009", "type": "choice", "level": "A1",
     "prompt": "“叔叔/舅舅”是？",
     "options": ["tio", "tia", "primo", "sobrino"],
     "answer": "tio",
     "explanation": "ES: tio es tio | ZH: 叔叔/舅舅"},
    {"id": "es_fa_010", "type": "choice", "level": "A1",
     "prompt": "“阿姨/姑妈”是？",
     "options": ["tia", "tio", "prima", "sobrina"],
     "answer": "tia",
     "explanation": "ES: tia es tia | ZH: 阿姨/姑妈"},
]

QUESTIONS["es.elementary.daily"] = [
    # 10题，日常
    {"id": "es_da_001", "type": "choice", "level": "A1",
     "prompt": "“起床”是？",
     "options": ["levantarse", "dormir", "comer", "salir"],
     "answer": "levantarse",
     "explanation": "ES: levantarse es levantarse | ZH: 起床"},
    {"id": "es_da_002", "type": "choice", "level": "A1",
     "prompt": "“睡觉”是？",
     "options": ["dormir", "estudiar", "trabajar", "caminar"],
     "answer": "dormir",
     "explanation": "ES: dormir es dormir | ZH: 睡觉"},
    {"id": "es_da_003", "type": "choice", "level": "A1",
     "prompt": "“吃饭”是？",
     "options": ["comer", "beber", "cocinar", "comprar"],
     "answer": "comer",
     "explanation": "ES: comer es comer | ZH: 吃饭"},
    {"id": "es_da_004", "type": "choice", "level": "A1",
     "prompt": "“喝水”是？",
     "options": ["beber agua", "comer pan", "ver la tele", "leer"],
     "answer": "beber agua",
     "explanation": "ES: beber agua | ZH: 喝水"},
    {"id": "es_da_005", "type": "choice", "level": "A1",
     "prompt": "“上班”是？",
     "options": ["ir al trabajo", "ir de viaje", "ir al cine", "ir de compras"],
     "answer": "ir al trabajo",
     "explanation": "ES: ir al trabajo | ZH: 上班"},
    {"id": "es_da_006", "type": "choice", "level": "A1",
     "prompt": "“学习”是？",
     "options": ["estudiar", "descansar", "cantar", "bailar"],
     "answer": "estudiar",
     "explanation": "ES: estudiar es estudiar | ZH: 学习"},
    {"id": "es_da_007", "type": "choice", "level": "A1",
     "prompt": "“做饭”是？",
     "options": ["cocinar", "limpiar", "dormir", "viajar"],
     "answer": "cocinar",
     "explanation": "ES: cocinar es cocinar | ZH: 做饭"},
    {"id": "es_da_008", "type": "choice", "level": "A1",
     "prompt": "“打扫”是？",
     "options": ["limpiar", "pagar", "correr", "nadar"],
     "answer": "limpiar",
     "explanation": "ES: limpiar es limpiar | ZH: 打扫"},
    {"id": "es_da_009", "type": "choice", "level": "A1",
     "prompt": "“散步”是？",
     "options": ["pasear", "trabajar", "estudiar", "dormir"],
     "answer": "pasear",
     "explanation": "ES: pasear es pasear | ZH: 散步"},
    {"id": "es_da_010", "type": "choice", "level": "A1",
     "prompt": "“购物”是？",
     "options": ["ir de compras", "ir al trabajo", "ir al parque", "ir a casa"],
     "answer": "ir de compras",
     "explanation": "ES: ir de compras | ZH: 购物"},
]

QUESTIONS["es.intermediate.ser_estar"] = [
    # 10题，ser vs estar
    {"id": "es_se_001", "type": "choice", "level": "B1",
     "prompt": "“他是医生”应选哪个动词？",
     "options": ["ser", "estar", "tener", "haber"],
     "answer": "ser",
     "explanation": "ES: Profesion -> ser | ZH: 职业用ser"},
    {"id": "es_se_002", "type": "choice", "level": "B1",
     "prompt": "“她在家”应选哪个动词？",
     "options": ["estar", "ser", "tener", "hacer"],
     "answer": "estar",
     "explanation": "ES: Ubicacion -> estar | ZH: 位置用estar"},
    {"id": "es_se_003", "type": "choice", "level": "B1",
     "prompt": "“他们很高兴（情绪）”应选哪个动词？",
     "options": ["estar", "ser", "haber", "ir"],
     "answer": "estar",
     "explanation": "ES: Estado emocional -> estar | ZH: 情绪用estar"},
    {"id": "es_se_004", "type": "choice", "level": "B1",
     "prompt": "“这个城市很大（特征）”应选哪个动词？",
     "options": ["ser", "estar", "tener", "venir"],
     "answer": "ser",
     "explanation": "ES: Caracteristica -> ser | ZH: 固有特征用ser"},
    {"id": "es_se_005", "type": "choice", "level": "B1",
     "prompt": "“门是开着的（状态）”应选哪个动词？",
     "options": ["estar", "ser", "hacer", "poder"],
     "answer": "estar",
     "explanation": "ES: Estado -> estar | ZH: 状态用estar"},
    {"id": "es_se_006", "type": "choice", "level": "B1",
     "prompt": "“会议在三点（时间）”应选哪个动词？",
     "options": ["ser", "estar", "ir", "tener"],
     "answer": "ser",
     "explanation": "ES: Hora -> ser | ZH: 时间用ser"},
    {"id": "es_se_007", "type": "choice", "level": "B1",
     "prompt": "“我来自中国”应选哪个动词？",
     "options": ["ser", "estar", "venir", "haber"],
     "answer": "ser",
     "explanation": "ES: Origen -> ser | ZH: 出身用ser"},
    {"id": "es_se_008", "type": "choice", "level": "B1",
     "prompt": "“餐厅在那边”应选哪个动词？",
     "options": ["estar", "ser", "ir", "ver"],
     "answer": "estar",
     "explanation": "ES: Lugar -> estar | ZH: 位置用estar"},
    {"id": "es_se_009", "type": "choice", "level": "B1",
     "prompt": "“今天是星期一”应选哪个动词？",
     "options": ["ser", "estar", "tener", "hacer"],
     "answer": "ser",
     "explanation": "ES: Dia/fecha -> ser | ZH: 日期用ser"},
    {"id": "es_se_010", "type": "choice", "level": "B1",
     "prompt": "“他在生病（状态）”应选哪个动词？",
     "options": ["estar", "ser", "haber", "hacer"],
     "answer": "estar",
     "explanation": "ES: Estado temporal -> estar | ZH: 临时状态用estar"},
]

QUESTIONS["es.intermediate.shopping"] = [
    # 10题，购物
    {"id": "es_sh_001", "type": "choice", "level": "B1",
     "prompt": "“这个多少钱？”是？",
     "options": ["Cuanto cuesta?", "Donde esta?", "Que hora es?", "Quien es?"],
     "answer": "Cuanto cuesta?",
     "explanation": "ES: Cuanto cuesta? pregunta precio | ZH: 询问价格"},
    {"id": "es_sh_002", "type": "choice", "level": "B1",
     "prompt": "“可以便宜点吗？”是？",
     "options": ["Puede hacer descuento?", "Puede ayudarme?", "Puede venir?", "Puede entrar?"],
     "answer": "Puede hacer descuento?",
     "explanation": "ES: pedir descuento | ZH: 请求打折"},
    {"id": "es_sh_003", "type": "choice", "level": "B1",
     "prompt": "“我想试穿”是？",
     "options": ["Quiero probarmelo", "Quiero comerlo", "Quiero verlo", "Quiero comprarlo"],
     "answer": "Quiero probarmelo",
     "explanation": "ES: probarse =试穿 | ZH: 想试穿"},
    {"id": "es_sh_004", "type": "choice", "level": "B1",
     "prompt": "“有更大的尺码吗？”是？",
     "options": ["Hay una talla mas grande?", "Hay una talla mas pequena?", "Es muy caro?", "Es bonito?"],
     "answer": "Hay una talla mas grande?",
     "explanation": "ES: talla mas grande | ZH: 更大的尺码"},
    {"id": "es_sh_005", "type": "choice", "level": "B1",
     "prompt": "“我就要这个”是？",
     "options": ["Me llevo este", "No lo quiero", "Solo miro", "Me voy"],
     "answer": "Me llevo este",
     "explanation": "ES: Me llevo este | ZH: 我要这个"},
    {"id": "es_sh_006", "type": "choice", "level": "B1",
     "prompt": "“可以刷卡吗？”是？",
     "options": ["Aceptan tarjeta?", "Solo efectivo?", "No tengo dinero", "Tengo efectivo"],
     "answer": "Aceptan tarjeta?",
     "explanation": "ES: aceptar tarjeta | ZH: 能刷卡吗"},
    {"id": "es_sh_007", "type": "choice", "level": "B1",
     "prompt": "“我用现金付款”是？",
     "options": ["Pago en efectivo", "Pago con tarjeta", "No pago", "Solo miro"],
     "answer": "Pago en efectivo",
     "explanation": "ES: pago en efectivo | ZH: 用现金付款"},
    {"id": "es_sh_008", "type": "choice", "level": "B1",
     "prompt": "“需要收据吗？”是？",
     "options": ["Necesita recibo?", "Quiere bolsa?", "Quiere mas?", "Quiere sentarse?"],
     "answer": "Necesita recibo?",
     "explanation": "ES: recibo = recibo | ZH: 需要收据吗"},
    {"id": "es_sh_009", "type": "choice", "level": "B1",
     "prompt": "“有别的颜色吗？”是？",
     "options": ["Hay otro color?", "Hay otra calle?", "Hay otro dia?", "Hay otro lugar?"],
     "answer": "Hay otro color?",
     "explanation": "ES: otro color | ZH: 其他颜色"},
    {"id": "es_sh_010", "type": "choice", "level": "B1",
     "prompt": "“请打包带走”是？",
     "options": ["Para llevar, por favor", "Para aqui", "No quiero", "Gracias"],
     "answer": "Para llevar, por favor",
     "explanation": "ES: para llevar | ZH: 打包带走"},
]

QUESTIONS["es.intermediate.travel"] = [
    # 10题，旅行
    {"id": "es_tr_001", "type": "choice", "level": "B1",
     "prompt": "“机场”是？",
     "options": ["aeropuerto", "estacion", "hotel", "puerto"],
     "answer": "aeropuerto",
     "explanation": "ES: aeropuerto es aeropuerto | ZH: 机场"},
    {"id": "es_tr_002", "type": "choice", "level": "B1",
     "prompt": "“火车站”是？",
     "options": ["estacion", "aeropuerto", "parque", "mercado"],
     "answer": "estacion",
     "explanation": "ES: estacion de tren | ZH: 火车站"},
    {"id": "es_tr_003", "type": "choice", "level": "B1",
     "prompt": "“我想预订一间房”是？",
     "options": ["Quiero reservar una habitacion", "Quiero limpiar la habitacion", "No hay habitaciones", "La habitacion es pequena"],
     "answer": "Quiero reservar una habitacion",
     "explanation": "ES: reservar una habitacion | ZH: 预订房间"},
    {"id": "es_tr_004", "type": "choice", "level": "B1",
     "prompt": "“入住”是？",
     "options": ["check-in", "check-out", "salida", "llegada"],
     "answer": "check-in",
     "explanation": "ES: check-in es registro | ZH: 入住"},
    {"id": "es_tr_005", "type": "choice", "level": "B1",
     "prompt": "“退房”是？",
     "options": ["check-out", "check-in", "salida", "llegada"],
     "answer": "check-out",
     "explanation": "ES: check-out es salida | ZH: 退房"},
    {"id": "es_tr_006", "type": "choice", "level": "B1",
     "prompt": "“地铁”是？",
     "options": ["metro", "autobus", "taxi", "avion"],
     "answer": "metro",
     "explanation": "ES: metro es metro | ZH: 地铁"},
    {"id": "es_tr_007", "type": "choice", "level": "B1",
     "prompt": "“公交车”是？",
     "options": ["autobus", "metro", "barco", "tren"],
     "answer": "autobus",
     "explanation": "ES: autobus es bus | ZH: 公交车"},
    {"id": "es_tr_008", "type": "choice", "level": "B1",
     "prompt": "“一张到马德里的票”是？",
     "options": ["Un billete a Madrid", "Un billete de Madrid", "Madrid es lejos", "Donde esta Madrid?"],
     "answer": "Un billete a Madrid",
     "explanation": "ES: billete a Madrid | ZH: 一张到马德里的票"},
    {"id": "es_tr_009", "type": "choice", "level": "B1",
     "prompt": "“洗手间在哪里？”是？",
     "options": ["Donde esta el bano?", "Donde esta la salida?", "Donde esta la entrada?", "Donde esta mi equipaje?"],
     "answer": "Donde esta el bano?",
     "explanation": "ES: bano = bano | ZH: 洗手间在哪里"},
    {"id": "es_tr_010", "type": "choice", "level": "B1",
     "prompt": "“请帮我叫一辆出租车”是？",
     "options": ["Llame un taxi, por favor", "No quiero taxi", "Voy en metro", "Tengo coche"],
     "answer": "Llame un taxi, por favor",
     "explanation": "ES: llame un taxi | ZH: 请帮我叫出租车"},
]
