QUESTIONS = {}

QUESTIONS["ko.starter.hangul"] = [
    # 10题，韩文字母识别，中文出题
    {"id": "ko_ha_001", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㄱ的发音是？",
     "options": ["g/k", "n", "d/t", "r/l"],
     "answer": "g/k",
     "explanation": "KO: ㄱ은 g/k 발음 | ZH: ㄱ在词首多读g，词末多读k"},
    {"id": "ko_ha_002", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㄴ的发音是？",
     "options": ["n", "m", "b/p", "s"],
     "answer": "n",
     "explanation": "KO: ㄴ은 n 발음 | ZH: ㄴ发n音"},
    {"id": "ko_ha_003", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㄷ的发音是？",
     "options": ["d/t", "g/k", "r/l", "h"],
     "answer": "d/t",
     "explanation": "KO: ㄷ은 d/t 발음 | ZH: 词首多读d，词末多读t"},
    {"id": "ko_ha_004", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㄹ的发音接近？",
     "options": ["r/l", "n", "m", "s"],
     "answer": "r/l",
     "explanation": "KO: ㄹ은 r/l 소리 | ZH: 介于r和l之间"},
    {"id": "ko_ha_005", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㅁ的发音是？",
     "options": ["m", "n", "b/p", "g/k"],
     "answer": "m",
     "explanation": "KO: ㅁ은 m 발음 | ZH: ㅁ发m音"},
    {"id": "ko_ha_006", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㅂ的发音是？",
     "options": ["b/p", "d/t", "s", "h"],
     "answer": "b/p",
     "explanation": "KO: ㅂ은 b/p 발음 | ZH: 词首多读b，词末多读p"},
    {"id": "ko_ha_007", "type": "choice", "level": "A0",
     "prompt": "韩语字母ㅅ的发音是？",
     "options": ["s", "h", "j", "m"],
     "answer": "s",
     "explanation": "KO: ㅅ은 s 발음 | ZH: ㅅ发s音"},
    {"id": "ko_ha_008", "type": "choice", "level": "A0",
     "prompt": "韩语元音ㅏ的发音是？",
     "options": ["a", "eo", "o", "u"],
     "answer": "a",
     "explanation": "KO: ㅏ는 a 발음 | ZH: ㅏ发a音"},
    {"id": "ko_ha_009", "type": "choice", "level": "A0",
     "prompt": "韩语元音ㅓ的发音是？",
     "options": ["eo", "a", "o", "u"],
     "answer": "eo",
     "explanation": "KO: ㅓ는 eo 발음 | ZH: ㅓ发eo音"},
    {"id": "ko_ha_010", "type": "choice", "level": "A0",
     "prompt": "韩语元音ㅗ的发音是？",
     "options": ["o", "u", "a", "i"],
     "answer": "o",
     "explanation": "KO: ㅗ는 o 발음 | ZH: ㅗ发o音"},
]

QUESTIONS["ko.starter.greetings"] = [
    # 10题，韩语问候语
    {"id": "ko_gr_001", "type": "choice", "level": "A0",
     "prompt": "“你好”的常用表达是？",
     "options": ["안녕하세요", "감사합니다", "죄송합니다", "안녕히 가세요"],
     "answer": "안녕하세요",
     "explanation": "KO: 안녕하세요는 일반 인사 | ZH: 安宁하세요，常用问候语"},
    {"id": "ko_gr_002", "type": "choice", "level": "A0",
     "prompt": "“谢谢”是？",
     "options": ["감사합니다", "괜찮아요", "안녕히 계세요", "주세요"],
     "answer": "감사합니다",
     "explanation": "KO: 감사합니다는 감사 표현 | ZH: 表示感谢"},
    {"id": "ko_gr_003", "type": "choice", "level": "A0",
     "prompt": "“对不起”是？",
     "options": ["죄송합니다", "환영합니다", "알겠습니다", "괜찮습니다"],
     "answer": "죄송합니다",
     "explanation": "KO: 죄송합니다는 사과 | ZH: 表示道歉"},
    {"id": "ko_gr_004", "type": "choice", "level": "A0",
     "prompt": "“再见（对留下的人说）”是？",
     "options": ["안녕히 계세요", "안녕히 가세요", "안녕하세요", "처음 뵙겠습니다"],
     "answer": "안녕히 계세요",
     "explanation": "KO: 안녕히 계세요는 남는 사람에게 | ZH: 对留下的人说再见"},
    {"id": "ko_gr_005", "type": "choice", "level": "A0",
     "prompt": "“再见（对离开的人说）”是？",
     "options": ["안녕히 가세요", "안녕히 계세요", "감사합니다", "수고하세요"],
     "answer": "안녕히 가세요",
     "explanation": "KO: 안녕히 가세요는 떠나는 사람에게 | ZH: 对要离开的人说"},
    {"id": "ko_gr_006", "type": "choice", "level": "A0",
     "prompt": "“初次见面”是？",
     "options": ["처음 뵙겠습니다", "만나서 반갑습니다", "잘 부탁드립니다", "안녕히 가세요"],
     "answer": "처음 뵙겠습니다",
     "explanation": "KO: 처음 뵙겠습니다는 첫 만남 | ZH: 初次见面敬语"},
    {"id": "ko_gr_007", "type": "choice", "level": "A0",
     "prompt": "“很高兴见到你”是？",
     "options": ["만나서 반갑습니다", "모르겠습니다", "괜찮아요", "어서 오세요"],
     "answer": "만나서 반갑습니다",
     "explanation": "KO: 만나서 반갑습니다는 기쁨 표현 | ZH: 见面很高兴"},
    {"id": "ko_gr_008", "type": "choice", "level": "A0",
     "prompt": "“请多关照”是？",
     "options": ["잘 부탁드립니다", "감사합니다", "괜찮습니다", "어서 오세요"],
     "answer": "잘 부탁드립니다",
     "explanation": "KO: 잘 부탁드립니다는 부탁 표현 | ZH: 请多关照"},
    {"id": "ko_gr_009", "type": "choice", "level": "A0",
     "prompt": "“欢迎光临”是？",
     "options": ["어서 오세요", "수고하셨습니다", "안녕히 가세요", "괜찮아요"],
     "answer": "어서 오세요",
     "explanation": "KO: 어서 오세요는 환영 인사 | ZH: 欢迎光临"},
    {"id": "ko_gr_010", "type": "choice", "level": "A0",
     "prompt": "“辛苦了”是？",
     "options": ["수고하셨습니다", "알겠습니다", "잠깐만요", "미안합니다"],
     "answer": "수고하셨습니다",
     "explanation": "KO: 수고하셨습니다는 노고 표현 | ZH: 表示辛苦了"},
]

QUESTIONS["ko.starter.numbers"] = [
    # 10题，韩语数字
    {"id": "ko_nb_001", "type": "choice", "level": "A0",
     "prompt": "数字1（固有韩语）是？",
     "options": ["하나", "둘", "셋", "넷"],
     "answer": "하나",
     "explanation": "KO: 하나는 1 | ZH: 固有数词1"},
    {"id": "ko_nb_002", "type": "choice", "level": "A0",
     "prompt": "数字2（固有韩语）是？",
     "options": ["둘", "하나", "다섯", "열"],
     "answer": "둘",
     "explanation": "KO: 둘은 2 | ZH: 固有数词2"},
    {"id": "ko_nb_003", "type": "choice", "level": "A0",
     "prompt": "数字3（固有韩语）是？",
     "options": ["셋", "넷", "여섯", "일곱"],
     "answer": "셋",
     "explanation": "KO: 셋은 3 | ZH: 固有数词3"},
    {"id": "ko_nb_004", "type": "choice", "level": "A0",
     "prompt": "数字4（固有韩语）是？",
     "options": ["넷", "셋", "여덟", "아홉"],
     "answer": "넷",
     "explanation": "KO: 넷은 4 | ZH: 固有数词4"},
    {"id": "ko_nb_005", "type": "choice", "level": "A0",
     "prompt": "数字5（固有韩语）是？",
     "options": ["다섯", "둘", "열", "스물"],
     "answer": "다섯",
     "explanation": "KO: 다섯은 5 | ZH: 固有数词5"},
    {"id": "ko_nb_006", "type": "choice", "level": "A0",
     "prompt": "数字6（固有韩语）是？",
     "options": ["여섯", "일곱", "여덟", "아홉"],
     "answer": "여섯",
     "explanation": "KO: 여섯은 6 | ZH: 固有数词6"},
    {"id": "ko_nb_007", "type": "choice", "level": "A0",
     "prompt": "数字7（固有韩语）是？",
     "options": ["일곱", "여섯", "여덟", "아홉"],
     "answer": "일곱",
     "explanation": "KO: 일곱은 7 | ZH: 固有数词7"},
    {"id": "ko_nb_008", "type": "choice", "level": "A0",
     "prompt": "数字8（固有韩语）是？",
     "options": ["여덟", "아홉", "열", "다섯"],
     "answer": "여덟",
     "explanation": "KO: 여덟은 8 | ZH: 固有数词8"},
    {"id": "ko_nb_009", "type": "choice", "level": "A0",
     "prompt": "数字9（固有韩语）是？",
     "options": ["아홉", "여덟", "일곱", "열"],
     "answer": "아홉",
     "explanation": "KO: 아홉은 9 | ZH: 固有数词9"},
    {"id": "ko_nb_010", "type": "choice", "level": "A0",
     "prompt": "数字10（固有韩语）是？",
     "options": ["열", "스물", "다섯", "하나"],
     "answer": "열",
     "explanation": "KO: 열은 10 | ZH: 固有数词10"},
]

QUESTIONS["ko.elementary.formal_speech"] = [
    # 10题，正式语体（합니다体）
    {"id": "ko_fs_001", "type": "choice", "level": "A1",
     "prompt": "动词“去”正式语体是？",
     "options": ["갑니다", "가요", "가자", "가세요"],
     "answer": "갑니다",
     "explanation": "KO: 가다 -> 갑니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_002", "type": "choice", "level": "A1",
     "prompt": "动词“来”正式语体是？",
     "options": ["옵니다", "와요", "오자", "오세요"],
     "answer": "옵니다",
     "explanation": "KO: 오다 -> 옵니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_003", "type": "choice", "level": "A1",
     "prompt": "动词“吃”正式语体是？",
     "options": ["먹습니다", "먹어요", "먹자", "먹으세요"],
     "answer": "먹습니다",
     "explanation": "KO: 먹다 -> 먹습니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_004", "type": "choice", "level": "A1",
     "prompt": "动词“看”正式语体是？",
     "options": ["봅니다", "봐요", "보자", "보세요"],
     "answer": "봅니다",
     "explanation": "KO: 보다 -> 봅니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_005", "type": "choice", "level": "A1",
     "prompt": "动词“做”正式语体是？",
     "options": ["합니다", "해요", "하자", "하세요"],
     "answer": "합니다",
     "explanation": "KO: 하다 -> 합니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_006", "type": "choice", "level": "A1",
     "prompt": "动词“学习”正式语体是？",
     "options": ["공부합니다", "공부해요", "공부하자", "공부하세요"],
     "answer": "공부합니다",
     "explanation": "KO: 공부하다 -> 공부합니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_007", "type": "choice", "level": "A1",
     "prompt": "动词“工作”正式语体是？",
     "options": ["일합니다", "일해요", "일하자", "일하세요"],
     "answer": "일합니다",
     "explanation": "KO: 일하다 -> 일합니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_008", "type": "choice", "level": "A1",
     "prompt": "动词“休息”正式语体是？",
     "options": ["쉽니다", "쉬어요", "쉬자", "쉬세요"],
     "answer": "쉽니다",
     "explanation": "KO: 쉬다 -> 쉽니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_009", "type": "choice", "level": "A1",
     "prompt": "动词“写”正式语体是？",
     "options": ["씁니다", "써요", "쓰자", "쓰세요"],
     "answer": "씁니다",
     "explanation": "KO: 쓰다 -> 씁니다 | ZH: 합니다体正式语体"},
    {"id": "ko_fs_010", "type": "choice", "level": "A1",
     "prompt": "动词“听”正式语体是？",
     "options": ["듣습니다", "들어요", "듣자", "들으세요"],
     "answer": "듣습니다",
     "explanation": "KO: 듣다 -> 듣습니다 | ZH: 합니다体正式语体"},
]

QUESTIONS["ko.elementary.family"] = [
    # 10题，家庭成员
    {"id": "ko_fa_001", "type": "choice", "level": "A1",
     "prompt": "“父亲”是？",
     "options": ["아버지", "어머니", "형", "누나"],
     "answer": "아버지",
     "explanation": "KO: 아버지는 아버지 | ZH: 父亲"},
    {"id": "ko_fa_002", "type": "choice", "level": "A1",
     "prompt": "“母亲”是？",
     "options": ["어머니", "아버지", "동생", "언니"],
     "answer": "어머니",
     "explanation": "KO: 어머니는 어머니 | ZH: 母亲"},
    {"id": "ko_fa_003", "type": "choice", "level": "A1",
     "prompt": "“哥哥（男生称呼）”是？",
     "options": ["형", "오빠", "누나", "언니"],
     "answer": "형",
     "explanation": "KO: 형은 남자가 부름 | ZH: 男生称哥哥"},
    {"id": "ko_fa_004", "type": "choice", "level": "A1",
     "prompt": "“哥哥（女生称呼）”是？",
     "options": ["오빠", "형", "누나", "언니"],
     "answer": "오빠",
     "explanation": "KO: 오빠는 여자가 부름 | ZH: 女生称哥哥"},
    {"id": "ko_fa_005", "type": "choice", "level": "A1",
     "prompt": "“姐姐（男生称呼）”是？",
     "options": ["누나", "언니", "오빠", "형"],
     "answer": "누나",
     "explanation": "KO: 누나는 남자가 부름 | ZH: 男生称姐姐"},
    {"id": "ko_fa_006", "type": "choice", "level": "A1",
     "prompt": "“姐姐（女生称呼）”是？",
     "options": ["언니", "누나", "오빠", "형"],
     "answer": "언니",
     "explanation": "KO: 언니는 여자가 부름 | ZH: 女生称姐姐"},
    {"id": "ko_fa_007", "type": "choice", "level": "A1",
     "prompt": "“弟弟/妹妹”通用是？",
     "options": ["동생", "친구", "사촌", "아들"],
     "answer": "동생",
     "explanation": "KO: 동생은 남녀 공통 | ZH: 弟弟或妹妹"},
    {"id": "ko_fa_008", "type": "choice", "level": "A1",
     "prompt": "“儿子”是？",
     "options": ["아들", "딸", "조카", "삼촌"],
     "answer": "아들",
     "explanation": "KO: 아들은 아들 | ZH: 儿子"},
    {"id": "ko_fa_009", "type": "choice", "level": "A1",
     "prompt": "“女儿”是？",
     "options": ["딸", "아들", "이모", "고모"],
     "answer": "딸",
     "explanation": "KO: 딸은 딸 | ZH: 女儿"},
    {"id": "ko_fa_010", "type": "choice", "level": "A1",
     "prompt": "“爷爷/外公”常用是？",
     "options": ["할아버지", "할머니", "삼촌", "이모"],
     "answer": "할아버지",
     "explanation": "KO: 할아버지는 할아버지 | ZH: 爷爷或外公"},
]

QUESTIONS["ko.elementary.food"] = [
    # 10题，食物词汇
    {"id": "ko_fd_001", "type": "choice", "level": "A1",
     "prompt": "“米饭”是？",
     "options": ["밥", "국", "빵", "물"],
     "answer": "밥",
     "explanation": "KO: 밥은 밥 | ZH: 米饭"},
    {"id": "ko_fd_002", "type": "choice", "level": "A1",
     "prompt": "“汤”是？",
     "options": ["국", "밥", "차", "우유"],
     "answer": "국",
     "explanation": "KO: 국은 국 | ZH: 汤"},
    {"id": "ko_fd_003", "type": "choice", "level": "A1",
     "prompt": "“面包”是？",
     "options": ["빵", "밥", "과일", "물"],
     "answer": "빵",
     "explanation": "KO: 빵은 빵 | ZH: 面包"},
    {"id": "ko_fd_004", "type": "choice", "level": "A1",
     "prompt": "“水”是？",
     "options": ["물", "차", "주스", "커피"],
     "answer": "물",
     "explanation": "KO: 물은 물 | ZH: 水"},
    {"id": "ko_fd_005", "type": "choice", "level": "A1",
     "prompt": "“茶”是？",
     "options": ["차", "우유", "맥주", "주스"],
     "answer": "차",
     "explanation": "KO: 차는 차 | ZH: 茶"},
    {"id": "ko_fd_006", "type": "choice", "level": "A1",
     "prompt": "“咖啡”是？",
     "options": ["커피", "차", "물", "우유"],
     "answer": "커피",
     "explanation": "KO: 커피는 커피 | ZH: 咖啡"},
    {"id": "ko_fd_007", "type": "choice", "level": "A1",
     "prompt": "“牛奶”是？",
     "options": ["우유", "주스", "맥주", "소주"],
     "answer": "우유",
     "explanation": "KO: 우유는 우유 | ZH: 牛奶"},
    {"id": "ko_fd_008", "type": "choice", "level": "A1",
     "prompt": "“水果”是？",
     "options": ["과일", "야채", "고기", "생선"],
     "answer": "과일",
     "explanation": "KO: 과일은 과일 | ZH: 水果"},
    {"id": "ko_fd_009", "type": "choice", "level": "A1",
     "prompt": "“蔬菜”是？",
     "options": ["야채", "과일", "빵", "밥"],
     "answer": "야채",
     "explanation": "KO: 야채는 야채 | ZH: 蔬菜"},
    {"id": "ko_fd_010", "type": "choice", "level": "A1",
     "prompt": "“肉”是？",
     "options": ["고기", "생선", "계란", "밥"],
     "answer": "고기",
     "explanation": "KO: 고기는 고기 | ZH: 肉"},
]

QUESTIONS["ko.intermediate.honorifics"] = [
    # 10题，尊待法
    {"id": "ko_hn_001", "type": "choice", "level": "B1",
     "prompt": "“吃（尊敬语）”是？",
     "options": ["드십니다", "먹습니다", "먹어요", "먹자"],
     "answer": "드십니다",
     "explanation": "KO: 드시다의 합니다체 | ZH: 吃的尊敬语"},
    {"id": "ko_hn_002", "type": "choice", "level": "B1",
     "prompt": "“睡觉（尊敬语）”是？",
     "options": ["주무십니다", "잡니다", "자요", "자자"],
     "answer": "주무십니다",
     "explanation": "KO: 주무시다의 합니다체 | ZH: 睡觉尊敬语"},
    {"id": "ko_hn_003", "type": "choice", "level": "B1",
     "prompt": "“在（尊敬语）”是？",
     "options": ["계십니다", "있습니다", "있어요", "있자"],
     "answer": "계십니다",
     "explanation": "KO: 계시다의 합니다체 | ZH: 在的尊敬语"},
    {"id": "ko_hn_004", "type": "choice", "level": "B1",
     "prompt": "“说（尊敬语）”是？",
     "options": ["말씀하십니다", "말합니다", "말해요", "말하자"],
     "answer": "말씀하십니다",
     "explanation": "KO: 말씀하시다의 합니다체 | ZH: 说的尊敬语"},
    {"id": "ko_hn_005", "type": "choice", "level": "B1",
     "prompt": "“给（尊敬语）”是？",
     "options": ["드리십니다", "줍니다", "줘요", "주자"],
     "answer": "드리십니다",
     "explanation": "KO: 드리다의 합니다체 | ZH: 给的尊敬语"},
    {"id": "ko_hn_006", "type": "choice", "level": "B1",
     "prompt": "“来（尊敬语）”是？",
     "options": ["오십니다", "옵니다", "와요", "오자"],
     "answer": "오십니다",
     "explanation": "KO: 오시다의 합니다체 | ZH: 来的尊敬语"},
    {"id": "ko_hn_007", "type": "choice", "level": "B1",
     "prompt": "“请看（尊敬语）”是？",
     "options": ["보시기 바랍니다", "봐요", "봅시다", "보자"],
     "answer": "보시기 바랍니다",
     "explanation": "KO: 보다의 높임 표현 | ZH: 请您看的尊敬表达"},
    {"id": "ko_hn_008", "type": "choice", "level": "B1",
     "prompt": "“请坐（尊敬语）”是？",
     "options": ["앉으시기 바랍니다", "앉아요", "앉자", "앉습니다"],
     "answer": "앉으시기 바랍니다",
     "explanation": "KO: 앉다의 높임 요청 | ZH: 请坐的尊敬表达"},
    {"id": "ko_hn_009", "type": "choice", "level": "B1",
     "prompt": "“拿（尊敬语）”是？",
     "options": ["가지십니다", "가집니다", "가져요", "가지자"],
     "answer": "가지십니다",
     "explanation": "KO: 가지다의 높임 | ZH: 拿/拥有的尊敬语"},
    {"id": "ko_hn_010", "type": "choice", "level": "B1",
     "prompt": "“听（尊敬语）”是？",
     "options": ["들으십니다", "듣습니다", "들어요", "듣자"],
     "answer": "들으십니다",
     "explanation": "KO: 듣다의 높임 | ZH: 听的尊敬语"},
]

QUESTIONS["ko.intermediate.shopping"] = [
    # 10题，购物
    {"id": "ko_sh_001", "type": "choice", "level": "B1",
     "prompt": "“这个多少钱？”是？",
     "options": ["이거 얼마예요?", "어디예요?", "몇 시예요?", "누구예요?"],
     "answer": "이거 얼마예요?",
     "explanation": "KO: 이거 얼마예요?는 가격 질문 | ZH: 询问价格"},
    {"id": "ko_sh_002", "type": "choice", "level": "B1",
     "prompt": "“能便宜点吗？”是？",
     "options": ["좀 깎아 주세요", "좀 기다려 주세요", "좀 보여 주세요", "좀 드세요"],
     "answer": "좀 깎아 주세요",
     "explanation": "KO: 깎아 주세요는 할인 요청 | ZH: 请求便宜"},
    {"id": "ko_sh_003", "type": "choice", "level": "B1",
     "prompt": "“试穿一下”是？",
     "options": ["입어 봐도 돼요?", "먹어 봐도 돼요?", "봐도 돼요?", "가도 돼요?"],
     "answer": "입어 봐도 돼요?",
     "explanation": "KO: 입어 보다 | ZH: 试穿"},
    {"id": "ko_sh_004", "type": "choice", "level": "B1",
     "prompt": "“有更大的尺寸吗？”是？",
     "options": ["더 큰 사이즈 있어요?", "더 작은 사이즈 있어요?", "이거 예뻐요?", "어디에 있어요?"],
     "answer": "더 큰 사이즈 있어요?",
     "explanation": "KO: 큰 사이즈 | ZH: 更大的尺码"},
    {"id": "ko_sh_005", "type": "choice", "level": "B1",
     "prompt": "“请给我这个”是？",
     "options": ["이거 주세요", "이거 아니에요", "이거 보세요", "이거 가세요"],
     "answer": "이거 주세요",
     "explanation": "KO: 주세요는 요청 | ZH: 请给我这个"},
    {"id": "ko_sh_006", "type": "choice", "level": "B1",
     "prompt": "“刷卡可以吗？”是？",
     "options": ["카드 돼요?", "현금만 돼요?", "돈 없어요", "카드 없어요"],
     "answer": "카드 돼요?",
     "explanation": "KO: 카드 돼요?는 카드 결제 | ZH: 能刷卡吗"},
    {"id": "ko_sh_007", "type": "choice", "level": "B1",
     "prompt": "“现金结账”是？",
     "options": ["현금으로 할게요", "카드로 할게요", "계산서 주세요", "영수증 없어요"],
     "answer": "현금으로 할게요",
     "explanation": "KO: 현금으로 할게요 | ZH: 用现金结账"},
    {"id": "ko_sh_008", "type": "choice", "level": "B1",
     "prompt": "“需要收据吗？”是？",
     "options": ["영수증 필요하세요?", "포장해 드릴까요?", "더 드릴까요?", "여기 앉으세요"],
     "answer": "영수증 필요하세요?",
     "explanation": "KO: 영수증 필요하세요? | ZH: 需要收据吗"},
    {"id": "ko_sh_009", "type": "choice", "level": "B1",
     "prompt": "“这件有其他颜色吗？”是？",
     "options": ["다른 색 있어요?", "다른 집 있어요?", "다른 길 있어요?", "다른 시간 있어요?"],
     "answer": "다른 색 있어요?",
     "explanation": "KO: 다른 색 | ZH: 其他颜色"},
    {"id": "ko_sh_010", "type": "choice", "level": "B1",
     "prompt": "“打包带走”是？",
     "options": ["포장해 주세요", "여기서 먹을게요", "안 먹을게요", "집에 갈게요"],
     "answer": "포장해 주세요",
     "explanation": "KO: 포장해 주세요 | ZH: 请打包"},
]

QUESTIONS["ko.intermediate.travel"] = [
    # 10题，旅行
    {"id": "ko_tr_001", "type": "choice", "level": "B1",
     "prompt": "“机场”是？",
     "options": ["공항", "역", "항구", "호텔"],
     "answer": "공항",
     "explanation": "KO: 공항은 공항 | ZH: 机场"},
    {"id": "ko_tr_002", "type": "choice", "level": "B1",
     "prompt": "“车站”是？",
     "options": ["역", "공원", "시장", "식당"],
     "answer": "역",
     "explanation": "KO: 역은 역 | ZH: 车站"},
    {"id": "ko_tr_003", "type": "choice", "level": "B1",
     "prompt": "“我想订一个房间”是？",
     "options": ["방을 예약하고 싶어요", "방을 청소해 주세요", "방이 없어요", "방이 작아요"],
     "answer": "방을 예약하고 싶어요",
     "explanation": "KO: 예약하고 싶어요 | ZH: 想预订"},
    {"id": "ko_tr_004", "type": "choice", "level": "B1",
     "prompt": "“入住”是？",
     "options": ["체크인", "체크아웃", "출발", "도착"],
     "answer": "체크인",
     "explanation": "KO: 체크인 | ZH: 入住"},
    {"id": "ko_tr_005", "type": "choice", "level": "B1",
     "prompt": "“退房”是？",
     "options": ["체크아웃", "체크인", "출발", "도착"],
     "answer": "체크아웃",
     "explanation": "KO: 체크아웃 | ZH: 退房"},
    {"id": "ko_tr_006", "type": "choice", "level": "B1",
     "prompt": "“地铁”是？",
     "options": ["지하철", "버스", "택시", "비행기"],
     "answer": "지하철",
     "explanation": "KO: 지하철은 지하철 | ZH: 地铁"},
    {"id": "ko_tr_007", "type": "choice", "level": "B1",
     "prompt": "“公交车”是？",
     "options": ["버스", "지하철", "배", "기차"],
     "answer": "버스",
     "explanation": "KO: 버스는 버스 | ZH: 公交车"},
    {"id": "ko_tr_008", "type": "choice", "level": "B1",
     "prompt": "“一张到首尔的票”是？",
     "options": ["서울까지 한 장", "서울에서 한 장", "서울로 돌아와요", "서울이 어디예요"],
     "answer": "서울까지 한 장",
     "explanation": "KO: 서울까지 한 장 | ZH: 一张到首尔的票"},
    {"id": "ko_tr_009", "type": "choice", "level": "B1",
     "prompt": "“请问洗手间在哪里？”是？",
     "options": ["화장실이 어디예요?", "출구가 어디예요?", "입구가 어디예요?", "짐이 어디예요?"],
     "answer": "화장실이 어디예요?",
     "explanation": "KO: 화장실이 어디예요? | ZH: 洗手间在哪里"},
    {"id": "ko_tr_010", "type": "choice", "level": "B1",
     "prompt": "“帮我叫一辆出租车”是？",
     "options": ["택시 불러 주세요", "택시가 없어요", "택시 타요", "택시 주세요"],
     "answer": "택시 불러 주세요",
     "explanation": "KO: 택시 불러 주세요 | ZH: 请帮我叫出租车"},
]
