# LinguoOS Question Bank — aligned with curriculum module IDs
# 240 questions across 24 modules, A0-C2 levels

QUESTIONS = {}

QUESTIONS['starter.phonics'] = [
    {'id': 'ph_001', 'type': 'choice', 'level': 'A0', 'prompt': "Which letter makes the /k/ sound in 'cat'?", 'options': ['a', 'c', 't', 'e'], 'answer': 'c', 'explanation': 'EN: c makes /k/ in cat. | ZH: c发/k/音'},
    {'id': 'ph_002', 'type': 'choice', 'level': 'A0', 'prompt': "Sound of 'sh'?", 'options': ['/s/', '/ʃ/', '/h/', '/tʃ/'], 'answer': '/ʃ/', 'explanation': 'EN: sh = /ʃ/ as in ship. | ZH: sh发/ʃ/'},
    {'id': 'ph_003', 'type': 'choice', 'level': 'A0', 'prompt': "Long 'a' sound?", 'options': ['cat', 'hat', 'cake', 'back'], 'answer': 'cake', 'explanation': 'EN: cake has long /eɪ/. | ZH: 长元音/eɪ/'},
    {'id': 'ph_004', 'type': 'choice', 'level': 'A0', 'prompt': "Silent letter in 'knife'?", 'options': ['n', 'i', 'k', 'e'], 'answer': 'k', 'explanation': 'EN: k is silent. | ZH: k不发音'},
    {'id': 'ph_005', 'type': 'choice', 'level': 'A0', 'prompt': "Syllables in 'elephant'?", 'options': ['1', '2', '3', '4'], 'answer': '3', 'explanation': 'EN: el-e-phant = 3. | ZH: 3个音节'},
    {'id': 'ph_006', 'type': 'choice', 'level': 'A0', 'prompt': "Rhymes with 'cat'?", 'options': ['cup', 'bat', 'car', 'cut'], 'answer': 'bat', 'explanation': 'EN: bat ends in /æt/. | ZH: bat和cat押韵'},
    {'id': 'ph_007', 'type': 'choice', 'level': 'A0', 'prompt': "'th' in 'the'?", 'options': ['/t/', '/ð/', '/θ/', '/d/'], 'answer': '/ð/', 'explanation': 'EN: voiced /ð/. | ZH: 浊辅音/ð/'},
    {'id': 'ph_008', 'type': 'choice', 'level': 'A0', 'prompt': "Vowel in 'bit'?", 'options': ['long i', 'short i', 'long e', 'short e'], 'answer': 'short i', 'explanation': 'EN: short /ɪ/. | ZH: 短元音/ɪ/'},
    {'id': 'ph_009', 'type': 'choice', 'level': 'A0', 'prompt': "'ch' in 'chair'?", 'options': ['/k/', '/ʃ/', '/tʃ/', '/s/'], 'answer': '/tʃ/', 'explanation': 'EN: /tʃ/ as in chair. | ZH: /tʃ/'},
    {'id': 'ph_010', 'type': 'choice', 'level': 'A0', 'prompt': "Vowel in 'moon'?", 'options': ['short u', 'long u', 'short o', 'long o'], 'answer': 'long u', 'explanation': 'EN: long /uː/. | ZH: 长元音/uː/'},
]

QUESTIONS['starter.greetings'] = [
    {'id': 'gr_001', 'type': 'choice', 'level': 'A0', 'prompt': 'Formal greeting?', 'options': ['Hey!', 'Yo!', 'Good morning.', 'Wassup?'], 'answer': 'Good morning.', 'explanation': 'EN: Good morning is formal. | ZH: 正式问候'},
    {'id': 'gr_002', 'type': 'choice', 'level': 'A0', 'prompt': "Reply to 'How are you?'", 'options': ['My name is Tom.', 'Fine, thanks!', 'See you.', 'Good night.'], 'answer': 'Fine, thanks!', 'explanation': 'EN: Standard polite reply. | ZH: 标准回答'},
    {'id': 'gr_003', 'type': 'choice', 'level': 'A0', 'prompt': 'Formal goodbye?', 'options': ['Bye!', 'See ya!', 'Farewell.', 'Later!'], 'answer': 'Farewell.', 'explanation': 'EN: Farewell is formal. | ZH: 正式告别'},
    {'id': 'gr_004', 'type': 'choice', 'level': 'A0', 'prompt': 'First meeting:', 'options': ['Long time no see!', 'Nice to meet you.', 'Welcome back!', 'How have you been?'], 'answer': 'Nice to meet you.', 'explanation': 'EN: For new introductions. | ZH: 初次见面'},
    {'id': 'gr_005', 'type': 'choice', 'level': 'A0', 'prompt': 'Greeting at 8pm?', 'options': ['Good morning', 'Good afternoon', 'Good evening', 'Good night'], 'answer': 'Good evening', 'explanation': 'EN: Good evening for evening. | ZH: 傍晚问候'},
    {'id': 'gr_006', 'type': 'choice', 'level': 'A1', 'prompt': "'How do you do?' is:", 'options': ['very casual', 'informal', 'formal', 'rude'], 'answer': 'formal', 'explanation': 'EN: Very formal British greeting. | ZH: 英式正式问候'},
    {'id': 'gr_007', 'type': 'choice', 'level': 'A0', 'prompt': 'Most casual?', 'options': ['Good morning', 'Hello', 'Hi there', 'Greetings'], 'answer': 'Hi there', 'explanation': 'EN: Most casual greeting. | ZH: 最随意'},
    {'id': 'gr_008', 'type': 'choice', 'level': 'A0', 'prompt': 'Not seen for a year:', 'options': ['Nice to meet you.', 'Long time no see!', 'Good morning.', 'Farewell.'], 'answer': 'Long time no see!', 'explanation': 'EN: For people not seen recently. | ZH: 久未见面'},
    {'id': 'gr_009', 'type': 'choice', 'level': 'A1', 'prompt': 'Take care means:', 'options': ['Be careful always', 'Goodbye stay well', 'Thank you', 'Come back'], 'answer': 'Goodbye stay well', 'explanation': 'EN: Warm goodbye. | ZH: 温暖告别'},
    {'id': 'gr_010', 'type': 'choice', 'level': 'A0', 'prompt': 'NOT a greeting?', 'options': ['Hello', 'Hi', 'Good luck', 'Hey'], 'answer': 'Good luck', 'explanation': 'EN: Good luck is a wish. | ZH: 祝福语不是问候'},
]

QUESTIONS['starter.numbers'] = [
    {'id': 'nu_001', 'type': 'choice', 'level': 'A0', 'prompt': 'How to say 21?', 'options': ['twenty-one', 'two-one', 'twenty oneth', 'two ten'], 'answer': 'twenty-one', 'explanation': 'EN: 21 = twenty-one. | ZH: 二十一'},
    {'id': 'nu_002', 'type': 'choice', 'level': 'A0', 'prompt': 'A dozen =', 'options': ['6', '10', '12', '20'], 'answer': '12', 'explanation': 'EN: Dozen = 12. | ZH: 12'},
    {'id': 'nu_003', 'type': 'choice', 'level': 'A0', 'prompt': 'Ordinal of 3:', 'options': ['three', 'third', 'threeth', 'thirdly'], 'answer': 'third', 'explanation': 'EN: Ordinal of 3 = third. | ZH: 序数词third'},
    {'id': 'nu_004', 'type': 'choice', 'level': 'A0', 'prompt': '1000000 =', 'options': ['one thousand', 'one million', 'one billion', 'ten thousand'], 'answer': 'one million', 'explanation': 'EN: One million. | ZH: 一百万'},
    {'id': 'nu_005', 'type': 'choice', 'level': 'A0', 'prompt': 'Quarter past three =', 'options': ['3:15', '3:45', '2:45', '3:25'], 'answer': '3:15', 'explanation': 'EN: Quarter past three = 3:15. | ZH: 三点十五'},
    {'id': 'nu_006', 'type': 'choice', 'level': 'A0', 'prompt': '2:30 =', 'options': ['two thirty only', 'half past two only', 'both are correct', 'quarter to two'], 'answer': 'both are correct', 'explanation': 'EN: Both forms work. | ZH: 两种说法均可'},
    {'id': 'nu_007', 'type': 'choice', 'level': 'A1', 'prompt': '15% of 200 =', 'options': ['20', '30', '25', '35'], 'answer': '30', 'explanation': 'EN: 0.15 x 200 = 30. | ZH: 30'},
    {'id': 'nu_008', 'type': 'choice', 'level': 'A1', 'prompt': 'Nought =', 'options': ['0', '1', '10', '100'], 'answer': '0', 'explanation': 'EN: Nought = zero (British). | ZH: 零'},
    {'id': 'nu_009', 'type': 'choice', 'level': 'A1', 'prompt': 'A score =', 'options': ['12', '20', '100', '50'], 'answer': '20', 'explanation': 'EN: A score = 20. | ZH: 旧英语20'},
    {'id': 'nu_010', 'type': 'choice', 'level': 'A0', 'prompt': 'Year 2024:', 'options': ['two thousand twenty-four', 'twenty twenty-four', 'both are correct', 'two oh two four'], 'answer': 'both are correct', 'explanation': 'EN: Both acceptable. | ZH: 两种均可'},
]

QUESTIONS['starter.daily'] = [
    {'id': 'da_001', 'type': 'choice', 'level': 'A0', 'prompt': 'Most polite request:', 'options': ['Give me water.', 'Water!', 'Could I have some water please?', 'I want water.'], 'answer': 'Could I have some water please?', 'explanation': 'EN: Could I have please = most polite. | ZH: 最礼貌请求'},
    {'id': 'da_002', 'type': 'choice', 'level': 'A0', 'prompt': 'Ask for the bill:', 'options': ['Give me the money.', 'Could I have the bill please?', 'I want to pay!', 'Money!'], 'answer': 'Could I have the bill please?', 'explanation': 'EN: Polite request for bill. | ZH: 礼貌请结账'},
    {'id': 'da_003', 'type': 'choice', 'level': 'A0', 'prompt': "'I did not catch that' means:", 'options': ['You were angry', 'You did not hear', 'You disagree', 'You are leaving'], 'answer': 'You did not hear', 'explanation': 'EN: Did not catch = did not hear. | ZH: 没听清'},
    {'id': 'da_004', 'type': 'choice', 'level': 'A0', 'prompt': 'No problem as reply to thanks =', 'options': ['I have no problems', 'You are welcome', 'I do not care', 'No thanks'], 'answer': 'You are welcome', 'explanation': 'EN: You are welcome. | ZH: 不客气'},
    {'id': 'da_005', 'type': 'choice', 'level': 'A0', 'prompt': 'Polite directions request:', 'options': ['Where?', 'Could you tell me how to get to the station?', 'Station where?', 'Find station.'], 'answer': 'Could you tell me how to get to the station?', 'explanation': 'EN: Polite way to ask directions. | ZH: 礼貌问路'},
    {'id': 'da_006', 'type': 'choice', 'level': 'A0', 'prompt': 'Just a moment =', 'options': ['Go away', 'Wait briefly', 'I do not understand', 'Come here'], 'answer': 'Wait briefly', 'explanation': 'EN: Please wait briefly. | ZH: 请稍等'},
    {'id': 'da_007', 'type': 'choice', 'level': 'A1', 'prompt': 'Polite disagreement:', 'options': ['That is wrong!', 'I see your point but...', 'No way!', 'Seriously?'], 'answer': 'I see your point but...', 'explanation': 'EN: Acknowledge then disagree. | ZH: 先认可再反驳'},
    {'id': 'da_008', 'type': 'choice', 'level': 'A1', 'prompt': 'I am running late =', 'options': ['I run mornings', 'I will be late', 'I ran fast', 'I am exercising'], 'answer': 'I will be late', 'explanation': 'EN: Running late = about to be late. | ZH: 快迟到了'},
    {'id': 'da_009', 'type': 'choice', 'level': 'A0', 'prompt': 'Ordering food:', 'options': ['I will have the chicken please.', 'Give chicken.', 'Chicken!', 'I eat chicken.'], 'answer': 'I will have the chicken please.', 'explanation': 'EN: I will have is used for ordering. | ZH: 点餐'},
    {'id': 'da_010', 'type': 'choice', 'level': 'A0', 'prompt': 'Excuse me is used to:', 'options': ['Only apologise', 'Only get attention', 'Both apologise and get attention', 'Insult'], 'answer': 'Both apologise and get attention', 'explanation': 'EN: Serves both purposes. | ZH: 兼有两种功能'},
]

QUESTIONS['elementary.grammar'] = [
    {'id': 'eg_001', 'type': 'choice', 'level': 'A1', 'prompt': 'She ___ like coffee.', 'options': ['do not', 'does not', 'not', 'is not'], 'answer': 'does not', 'explanation': 'EN: Third person singular: does not. | ZH: 第三人称单数'},
    {'id': 'eg_002', 'type': 'choice', 'level': 'A1', 'prompt': 'Past of go:', 'options': ['goed', 'went', 'go', 'gone'], 'answer': 'went', 'explanation': 'EN: Went = irregular past. | ZH: 不规则过去式'},
    {'id': 'eg_003', 'type': 'choice', 'level': 'A1', 'prompt': 'I have lived here ___ 2010.', 'options': ['for', 'since', 'ago', 'from'], 'answer': 'since', 'explanation': 'EN: Since + point in time. | ZH: since后接时间点'},
    {'id': 'eg_004', 'type': 'choice', 'level': 'A1', 'prompt': 'Correct a/an:', 'options': ['a apple', 'an orange', 'a hour', 'an university'], 'answer': 'an orange', 'explanation': 'EN: An before vowel sounds. | ZH: 元音前用an'},
    {'id': 'eg_005', 'type': 'choice', 'level': 'A1', 'prompt': 'Correct comparative:', 'options': ['more tall than', 'taller than', 'tallest than', 'most tall'], 'answer': 'taller than', 'explanation': 'EN: -er for one syllable. | ZH: 单音节加-er'},
    {'id': 'eg_006', 'type': 'choice', 'level': 'B1', 'prompt': 'If I ___ rich I would travel.', 'options': ['am', 'was', 'were', 'be'], 'answer': 'were', 'explanation': 'EN: Hypothetical = were. | ZH: 虚拟用were'},
    {'id': 'eg_007', 'type': 'choice', 'level': 'A1', 'prompt': 'Correct quantity:', 'options': ['Much people', 'Many people came.', 'A lot people', 'Peoples'], 'answer': 'Many people came.', 'explanation': 'EN: Many + countable nouns. | ZH: many用于可数'},
    {'id': 'eg_008', 'type': 'choice', 'level': 'A2', 'prompt': 'She ___ TV when I called.', 'options': ['watched', 'was watching', 'is watching', 'watches'], 'answer': 'was watching', 'explanation': 'EN: Past continuous for ongoing action. | ZH: 过去进行时'},
    {'id': 'eg_009', 'type': 'choice', 'level': 'B1', 'prompt': 'Passive voice:', 'options': ['They built the bridge.', 'The bridge was built.', 'The bridge built.', 'Built bridge.'], 'answer': 'The bridge was built.', 'explanation': 'EN: Object + was/were + past participle. | ZH: 被动语态'},
    {'id': 'eg_010', 'type': 'choice', 'level': 'A2', 'prompt': 'Obligation: I ___ finish by Friday.', 'options': ['must', 'have to', 'need to', 'all are correct'], 'answer': 'all are correct', 'explanation': 'EN: All express necessity. | ZH: 三者均可表示必要'},
]

QUESTIONS['elementary.dialog'] = [
    {'id': 'di_001', 'type': 'choice', 'level': 'A1', 'prompt': 'A: Can I help? B: ___', 'options': ['Yes I looking.', 'Yes I am looking for shoes.', 'Yes I look.', 'Yes I looked.'], 'answer': 'Yes I am looking for shoes.', 'explanation': 'EN: Present continuous for current activity. | ZH: 现在进行时'},
    {'id': 'di_002', 'type': 'choice', 'level': 'A1', 'prompt': 'What do you do asks about:', 'options': ['Your action', 'Your job', 'Your location', 'Your age'], 'answer': 'Your job', 'explanation': 'EN: Job/occupation. | ZH: 询问职业'},
    {'id': 'di_003', 'type': 'choice', 'level': 'A0', 'prompt': 'Reply: Would you like tea?', 'options': ['Yes please.', 'Yes I would like.', 'Yes please I would.', 'Yes I do.'], 'answer': 'Yes please.', 'explanation': 'EN: Yes please = polite acceptance. | ZH: 礼貌接受'},
    {'id': 'di_004', 'type': 'choice', 'level': 'A1', 'prompt': 'Giving a price:', 'options': ['It costs dollars.', 'That costs 10 dollars.', 'This is cost.', 'It costing.'], 'answer': 'That costs 10 dollars.', 'explanation': 'EN: That costs + amount. | ZH: 报价'},
    {'id': 'di_005', 'type': 'choice', 'level': 'A2', 'prompt': 'Short answer: Have you been to Japan?', 'options': ['Yes I have been.', 'Yes I have.', 'Yes I did.', 'Yes I been.'], 'answer': 'Yes I have.', 'explanation': 'EN: Present perfect short answer. | ZH: 现在完成时简答'},
    {'id': 'di_006', 'type': 'choice', 'level': 'A1', 'prompt': 'A: What is the matter? B: ___', 'options': ['I do not matter.', 'I have a headache.', 'Nothing matter.', 'Matter.'], 'answer': 'I have a headache.', 'explanation': 'EN: What is the matter = what is wrong. | ZH: 询问不适'},
    {'id': 'di_007', 'type': 'choice', 'level': 'A2', 'prompt': 'I am afraid I cannot make it =', 'options': ['I am scared', 'I cannot attend', 'I cannot create', 'I am unsure'], 'answer': 'I cannot attend', 'explanation': 'EN: Cannot make it = cannot attend. | ZH: 无法赴约'},
    {'id': 'di_008', 'type': 'choice', 'level': 'A1', 'prompt': 'Could you say that again means:', 'options': ['Speak faster', 'Repeat please', 'I disagree', 'I am leaving'], 'answer': 'Repeat please', 'explanation': 'EN: Asking for repetition. | ZH: 请重复'},
    {'id': 'di_009', 'type': 'choice', 'level': 'A2', 'prompt': 'That suits me fine =', 'options': ['That is beautiful', 'That time works for me', 'That is expensive', 'I like it'], 'answer': 'That time works for me', 'explanation': 'EN: Suits me = convenient. | ZH: 时间合适'},
    {'id': 'di_010', 'type': 'choice', 'level': 'A2', 'prompt': 'What brings you here =', 'options': ['How did you travel', 'Why are you here', 'When did you arrive', 'Where are you from'], 'answer': 'Why are you here', 'explanation': 'EN: Reason for visit. | ZH: 来访原因'},
]

QUESTIONS['elementary.routines'] = [
    {'id': 'ro_001', 'type': 'choice', 'level': 'A1', 'prompt': 'I wake up ___ 7 every morning.', 'options': ['in', 'on', 'at', 'by'], 'answer': 'at', 'explanation': 'EN: At + specific time. | ZH: 具体时间用at'},
    {'id': 'ro_002', 'type': 'choice', 'level': 'A1', 'prompt': 'Eating breakfast:', 'options': ['have breakfast', 'make breakfast', 'do breakfast', 'take breakfast'], 'answer': 'have breakfast', 'explanation': 'EN: Have breakfast = fixed collocation. | ZH: 固定搭配'},
    {'id': 'ro_003', 'type': 'choice', 'level': 'A2', 'prompt': 'Running late =', 'options': ['I run mornings', 'I will be late', 'I ran fast', 'I exercise'], 'answer': 'I will be late', 'explanation': 'EN: About to be late. | ZH: 快要迟到'},
    {'id': 'ro_004', 'type': 'choice', 'level': 'A1', 'prompt': 'She ___ up late on weekends.', 'options': ['sleeps', 'slept', 'is sleeping', 'sleep'], 'answer': 'sleeps', 'explanation': 'EN: Habitual present tense. | ZH: 习惯性动作'},
    {'id': 'ro_005', 'type': 'choice', 'level': 'B1', 'prompt': 'A lot on my plate =', 'options': ['Plate is full', 'I am very busy', 'I eat a lot', 'Need bigger plate'], 'answer': 'I am very busy', 'explanation': 'EN: Very busy idiom. | ZH: 很忙'},
    {'id': 'ro_006', 'type': 'choice', 'level': 'A2', 'prompt': 'ASAP =', 'options': ['As Soon As Possible', 'A Simple And Plain', 'After Some Action', 'All Students'], 'answer': 'As Soon As Possible', 'explanation': 'EN: ASAP = As Soon As Possible. | ZH: 尽快'},
    {'id': 'ro_007', 'type': 'choice', 'level': 'A1', 'prompt': 'Logical morning sequence:', 'options': ['Dinner wake shower', 'Wake shower breakfast', 'Breakfast wake shower', 'Work wake sleep'], 'answer': 'Wake shower breakfast', 'explanation': 'EN: Logical routine. | ZH: 合理顺序'},
    {'id': 'ro_008', 'type': 'choice', 'level': 'A2', 'prompt': 'I commute to work =', 'options': ['Work from home', 'Travel to work regularly', 'Drive fast', 'Late for work'], 'answer': 'Travel to work regularly', 'explanation': 'EN: Commute = regular travel. | ZH: 通勤'},
    {'id': 'ro_009', 'type': 'choice', 'level': 'B1', 'prompt': 'Wind down =', 'options': ['Exercise harder', 'Relax before sleep', 'Start new tasks', 'Wake up'], 'answer': 'Relax before sleep', 'explanation': 'EN: Wind down = relax. | ZH: 放松'},
    {'id': 'ro_010', 'type': 'choice', 'level': 'A1', 'prompt': 'I usually ___ 8 hours.', 'options': ['sleep', 'sleeping', 'slept', 'am sleeping'], 'answer': 'sleep', 'explanation': 'EN: Usually + simple present. | ZH: 习惯用一般现在时'},
]

QUESTIONS['elementary.questions'] = [
    {'id': 'qu_001', 'type': 'choice', 'level': 'A1', 'prompt': '___ does she live? London.', 'options': ['Where', 'What', 'When', 'Who'], 'answer': 'Where', 'explanation': 'EN: Where = location. | ZH: 地点'},
    {'id': 'qu_002', 'type': 'choice', 'level': 'A1', 'prompt': '___ time does it start? 8pm.', 'options': ['Who', 'What', 'How', 'When'], 'answer': 'What', 'explanation': 'EN: What time = clock time. | ZH: 询问时间'},
    {'id': 'qu_003', 'type': 'choice', 'level': 'A1', 'prompt': '___ is your colour? Blue.', 'options': ['Why', 'Who', 'What', 'Where'], 'answer': 'What', 'explanation': 'EN: What = things. | ZH: 询问事物'},
    {'id': 'qu_004', 'type': 'choice', 'level': 'A1', 'prompt': '___ did you go? Because fun.', 'options': ['How', 'When', 'Why', 'Where'], 'answer': 'Why', 'explanation': 'EN: Why = reason. | ZH: 原因'},
    {'id': 'qu_005', 'type': 'choice', 'level': 'A1', 'prompt': '___ long? 30 minutes.', 'options': ['How', 'What', 'When', 'Which'], 'answer': 'How', 'explanation': 'EN: How long = duration. | ZH: 时长'},
    {'id': 'qu_006', 'type': 'choice', 'level': 'A1', 'prompt': '___ is your birthday? March 5.', 'options': ['Why', 'When', 'What', 'Who'], 'answer': 'When', 'explanation': 'EN: When = date/time. | ZH: 时间'},
    {'id': 'qu_007', 'type': 'choice', 'level': 'A1', 'prompt': '___ made this? My mother.', 'options': ['Where', 'When', 'Who', 'How'], 'answer': 'Who', 'explanation': 'EN: Who = person. | ZH: 人物'},
    {'id': 'qu_008', 'type': 'choice', 'level': 'A1', 'prompt': '___ many? 25.', 'options': ['How', 'What', 'Which', 'Who'], 'answer': 'How', 'explanation': 'EN: How many = quantity. | ZH: 数量'},
    {'id': 'qu_009', 'type': 'choice', 'level': 'A2', 'prompt': '___ prefer: tea or coffee?', 'options': ['Who', 'What', 'Which', 'Why'], 'answer': 'Which', 'explanation': 'EN: Which = limited choices. | ZH: 有限选项'},
    {'id': 'qu_010', 'type': 'choice', 'level': 'A1', 'prompt': '___ far? 500m.', 'options': ['How', 'What', 'When', 'Which'], 'answer': 'How', 'explanation': 'EN: How far = distance. | ZH: 距离'},
]

QUESTIONS['intermediate.precision'] = [
    {'id': 'pr_001', 'type': 'choice', 'level': 'B1', 'prompt': 'More precise?', 'options': ['Many students failed.', '37% of students failed.', 'Lots failed.', 'Students failed.'], 'answer': '37% of students failed.', 'explanation': 'EN: Specific data beats vague terms. | ZH: 具体数据更精确'},
    {'id': 'pr_002', 'type': 'choice', 'level': 'B1', 'prompt': 'Verifiable claim?', 'options': ['She is talented.', 'She won three competitions.', 'She is the best.', 'She is good.'], 'answer': 'She won three competitions.', 'explanation': 'EN: Facts are verifiable. | ZH: 可核实的事实'},
    {'id': 'pr_003', 'type': 'choice', 'level': 'B1', 'prompt': "'Quickly' is imprecise because:", 'options': ['It is a verb', 'It lacks specific data', 'It is passive', 'It is short'], 'answer': 'It lacks specific data', 'explanation': 'EN: Quickly has no time specifics. | ZH: 缺乏具体数据'},
    {'id': 'pr_004', 'type': 'choice', 'level': 'B2', 'prompt': "Most precise revision of 'Sales increased.'", 'options': ['Sales went up.', 'Sales rose 23% in Q3 2024.', 'Sales were higher.', 'Sales improved.'], 'answer': 'Sales rose 23% in Q3 2024.', 'explanation': 'EN: Include percentage and period. | ZH: 含百分比和时间'},
    {'id': 'pr_005', 'type': 'choice', 'level': 'B1', 'prompt': 'Roughly weakens by:', 'options': ['Adding data', 'Adding vagueness', 'Giving range', 'Citing sources'], 'answer': 'Adding vagueness', 'explanation': 'EN: Roughly = less specific. | ZH: 引入模糊性'},
    {'id': 'pr_006', 'type': 'choice', 'level': 'B2', 'prompt': 'Most experts agree needs:', 'options': ['More adjectives', 'Specific citation', 'Passive verb', 'Punctuation'], 'answer': 'Specific citation', 'explanation': 'EN: Sources needed. | ZH: 需要来源'},
    {'id': 'pr_007', 'type': 'choice', 'level': 'B1', 'prompt': 'Students in China is too ___ in scope.', 'options': ['narrow', 'wide', 'precise', 'specific'], 'answer': 'wide', 'explanation': 'EN: Too broad. | ZH: 范围太广'},
    {'id': 'pr_008', 'type': 'choice', 'level': 'B1', 'prompt': 'Adds measurable time:', 'options': ['soon', 'within 48 hours', 'later', 'eventually'], 'answer': 'within 48 hours', 'explanation': 'EN: Measurable deadline. | ZH: 可测量时限'},
    {'id': 'pr_009', 'type': 'choice', 'level': 'B2', 'prompt': "'The drug is effective' needs:", 'options': ['More adjectives', 'Clinical data', 'Passive verb', 'An idiom'], 'answer': 'Clinical data', 'explanation': 'EN: Medical claims need evidence. | ZH: 需要数据'},
    {'id': 'pr_010', 'type': 'choice', 'level': 'B1', 'prompt': 'Precision helps by:', 'options': ['Making longer', 'Reducing ambiguity', 'Adding emotion', 'Impressing'], 'answer': 'Reducing ambiguity', 'explanation': 'EN: Removes multiple interpretations. | ZH: 消除歧义'},
]

QUESTIONS['intermediate.structure'] = [
    {'id': 'st_001', 'type': 'choice', 'level': 'B1', 'prompt': 'Paragraph begins with:', 'options': ['Example', 'Topic sentence', 'Conclusion', 'Question'], 'answer': 'Topic sentence', 'explanation': 'EN: Topic sentence = main idea. | ZH: 主题句'},
    {'id': 'st_002', 'type': 'choice', 'level': 'B1', 'prompt': 'Supporting sentences:', 'options': ['Contradict', 'Develop main idea', 'Start new topic', 'Be long'], 'answer': 'Develop main idea', 'explanation': 'EN: Expand and explain the topic. | ZH: 发展主题'},
    {'id': 'st_003', 'type': 'choice', 'level': 'B1', 'prompt': 'However signals:', 'options': ['Addition', 'Contrast', 'Cause', 'Example'], 'answer': 'Contrast', 'explanation': 'EN: Contrast transition. | ZH: 转折'},
    {'id': 'st_004', 'type': 'choice', 'level': 'B1', 'prompt': 'Therefore signals:', 'options': ['Contrast', 'Addition', 'Result', 'Example'], 'answer': 'Result', 'explanation': 'EN: Result or conclusion. | ZH: 结果'},
    {'id': 'st_005', 'type': 'choice', 'level': 'A2', 'prompt': 'For instance signals:', 'options': ['Contrast', 'Example', 'Cause', 'Summary'], 'answer': 'Example', 'explanation': 'EN: Introduces an example. | ZH: 举例'},
    {'id': 'st_006', 'type': 'choice', 'level': 'B1', 'prompt': 'Standard order:', 'options': ['Conclusion evidence topic', 'Topic evidence conclusion', 'Evidence conclusion topic', 'Conclusion topic evidence'], 'answer': 'Topic evidence conclusion', 'explanation': 'EN: Topic then evidence then conclusion. | ZH: 主题证据结论'},
    {'id': 'st_007', 'type': 'choice', 'level': 'A2', 'prompt': 'In addition:', 'options': ['Shows contrast', 'Adds information', 'Shows result', 'Concedes'], 'answer': 'Adds information', 'explanation': 'EN: Adds more information. | ZH: 补充信息'},
    {'id': 'st_008', 'type': 'choice', 'level': 'B1', 'prompt': 'Unity means:', 'options': ['Many ideas', 'All sentences on one topic', 'Long sentences', 'Using transitions'], 'answer': 'All sentences on one topic', 'explanation': 'EN: One main idea. | ZH: 统一性'},
    {'id': 'st_009', 'type': 'choice', 'level': 'B1', 'prompt': 'Coherence means:', 'options': ['Long sentences', 'Logical flow', 'Many paragraphs', 'Technical vocab'], 'answer': 'Logical flow', 'explanation': 'EN: Ideas flow logically. | ZH: 连贯性'},
    {'id': 'st_010', 'type': 'choice', 'level': 'B1', 'prompt': 'Concluding sentence:', 'options': ['Introduces new ideas', 'Restates main point', 'Asks question', 'Gives examples'], 'answer': 'Restates main point', 'explanation': 'EN: Reinforces main idea. | ZH: 重申主旨'},
]

QUESTIONS['intermediate.logic'] = [
    {'id': 'lo_001', 'type': 'choice', 'level': 'B1', 'prompt': 'Despite shows:', 'options': ['Cause', 'Contrast', 'Result', 'Addition'], 'answer': 'Contrast', 'explanation': 'EN: Concession/contrast. | ZH: 让步'},
    {'id': 'lo_002', 'type': 'choice', 'level': 'B1', 'prompt': 'Since here means:', 'options': ['Time', 'Cause', 'Contrast', 'Condition'], 'answer': 'Cause', 'explanation': 'EN: Since can mean because. | ZH: 原因'},
    {'id': 'lo_003', 'type': 'choice', 'level': 'B2', 'prompt': 'Provided that is a ___ clause.', 'options': ['time', 'result', 'conditional', 'contrast'], 'answer': 'conditional', 'explanation': 'EN: Condition clause. | ZH: 条件从句'},
    {'id': 'lo_004', 'type': 'choice', 'level': 'B1', 'prompt': 'Best cause-effect:', 'options': ['Rain. We stayed.', 'It rained so we stayed.', 'Rain. Inside.', 'Stayed. Rain.'], 'answer': 'It rained so we stayed.', 'explanation': 'EN: So shows result. | ZH: 因果连接'},
    {'id': 'lo_005', 'type': 'choice', 'level': 'B1', 'prompt': 'Although he tried result =', 'options': ['He tried', 'He failed', 'Both', 'He succeeded'], 'answer': 'He failed', 'explanation': 'EN: Concession but failure. | ZH: 结果失败'},
    {'id': 'lo_006', 'type': 'choice', 'level': 'B1', 'prompt': 'Unless =', 'options': ['If', 'If not', 'Although', 'Because'], 'answer': 'If not', 'explanation': 'EN: Unless = if not. | ZH: 如果不'},
    {'id': 'lo_007', 'type': 'choice', 'level': 'B2', 'prompt': 'Shows contrast:', 'options': ['furthermore', 'therefore', 'nevertheless', 'consequently'], 'answer': 'nevertheless', 'explanation': 'EN: Nevertheless = however. | ZH: 转折'},
    {'id': 'lo_008', 'type': 'choice', 'level': 'B1', 'prompt': 'As a result introduces:', 'options': ['Example', 'Contrast', 'Consequence', 'Condition'], 'answer': 'Consequence', 'explanation': 'EN: Consequence. | ZH: 结果'},
    {'id': 'lo_009', 'type': 'choice', 'level': 'B1', 'prompt': 'In other words =', 'options': ['Add info', 'Restate', 'Contrast', 'Conclude'], 'answer': 'Restate', 'explanation': 'EN: Paraphrase. | ZH: 换句话说'},
    {'id': 'lo_010', 'type': 'choice', 'level': 'B2', 'prompt': 'Not only A but also B =', 'options': ['A or B', 'Only B', 'Both A and B', 'Neither'], 'answer': 'Both A and B', 'explanation': 'EN: Both. | ZH: 两者都'},
]

QUESTIONS['intermediate.reading'] = [
    {'id': 're_001', 'type': 'choice', 'level': 'B1', 'prompt': 'Main idea usually in:', 'options': ['Last sentence', 'Topic sentence', 'Footnote', 'Middle'], 'answer': 'Topic sentence', 'explanation': 'EN: Topic sentence = main idea. | ZH: 主题句'},
    {'id': 're_002', 'type': 'choice', 'level': 'B1', 'prompt': 'Inference means:', 'options': ['Read every word', 'Guess from context', 'Look up words', 'Memorise'], 'answer': 'Guess from context', 'explanation': 'EN: Use clues to understand. | ZH: 推断'},
    {'id': 're_003', 'type': 'choice', 'level': 'B1', 'prompt': 'Skimming means:', 'options': ['Read every detail', 'Read fast for gist', 'Memorise', 'Underline'], 'answer': 'Read fast for gist', 'explanation': 'EN: Quick overview. | ZH: 略读'},
    {'id': 're_004', 'type': 'choice', 'level': 'B1', 'prompt': 'Scanning finds:', 'options': ['Overall tone', 'Specific information', 'Pleasure', 'Structure'], 'answer': 'Specific information', 'explanation': 'EN: Search for specific fact. | ZH: 扫读'},
    {'id': 're_005', 'type': 'choice', 'level': 'B2', 'prompt': 'Connotation is:', 'options': ['Dictionary meaning', 'Emotional meaning', 'Pronunciation', 'Grammar'], 'answer': 'Emotional meaning', 'explanation': 'EN: Emotional or implied meaning. | ZH: 内涵义'},
    {'id': 're_006', 'type': 'choice', 'level': 'B1', 'prompt': 'Implies means:', 'options': ['States directly', 'Suggests indirectly', 'Quotes', 'Contradicts'], 'answer': 'Suggests indirectly', 'explanation': 'EN: Suggests without stating. | ZH: 暗示'},
    {'id': 're_007', 'type': 'choice', 'level': 'B1', 'prompt': 'Tone refers to:', 'options': ['Volume', 'Author attitude', 'Sentence length', 'Grammar'], 'answer': 'Author attitude', 'explanation': 'EN: Writer attitude. | ZH: 作者态度'},
    {'id': 're_008', 'type': 'choice', 'level': 'B1', 'prompt': 'Fact not opinion?', 'options': ['Math is boring.', 'Exam had 20 questions.', 'History matters.', 'Grammar is hard.'], 'answer': 'Exam had 20 questions.', 'explanation': 'EN: Facts are verifiable. | ZH: 事实可核实'},
    {'id': 're_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Biased text shows:', 'options': ['Only facts', 'One-sided view', 'Multiple views', 'No opinion'], 'answer': 'One-sided view', 'explanation': 'EN: One perspective only. | ZH: 片面观点'},
    {'id': 're_010', 'type': 'choice', 'level': 'B1', 'prompt': 'Context clues help:', 'options': ['Spell words', 'Guess meaning', 'Find errors', 'Count syllables'], 'answer': 'Guess meaning', 'explanation': 'EN: Clues for unknown words. | ZH: 猜测生词'},
]

QUESTIONS['upper.argument'] = [
    {'id': 'ar_001', 'type': 'choice', 'level': 'C1', 'prompt': 'Strong argument needs:', 'options': ['Emotion only', 'Claim evidence reasoning', 'Long sentences', 'Formal vocab'], 'answer': 'Claim evidence reasoning', 'explanation': 'EN: Claim + evidence + reasoning. | ZH: 论点证据推理'},
    {'id': 'ar_002', 'type': 'choice', 'level': 'B2', 'prompt': 'Counterargument is:', 'options': ['Your evidence', 'Opposing view you address', 'A conclusion', 'A statistic'], 'answer': 'Opposing view you address', 'explanation': 'EN: Address opposing views. | ZH: 反驳对方'},
    {'id': 'ar_003', 'type': 'choice', 'level': 'C1', 'prompt': 'Ad hominem attacks:', 'options': ['The argument', 'The person', 'The data', 'The source'], 'answer': 'The person', 'explanation': 'EN: Attack person not argument. | ZH: 人身攻击'},
    {'id': 'ar_004', 'type': 'choice', 'level': 'C1', 'prompt': 'Straw man means:', 'options': ['Misrepresenting opponent', 'Weak evidence', 'Emotional appeal', 'Circular reasoning'], 'answer': 'Misrepresenting opponent', 'explanation': 'EN: Distort opponent position. | ZH: 稻草人谬误'},
    {'id': 'ar_005', 'type': 'choice', 'level': 'B2', 'prompt': 'Concession transition:', 'options': ['Therefore', 'Furthermore', 'Admittedly', 'Consequently'], 'answer': 'Admittedly', 'explanation': 'EN: Admittedly = concedes. | ZH: 让步'},
    {'id': 'ar_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Slippery slope claims:', 'options': ['Evidence is weak', 'One event causes extreme outcomes', 'Source biased', 'Data old'], 'answer': 'One event causes extreme outcomes', 'explanation': 'EN: Unjustified chain. | ZH: 滑坡谬误'},
    {'id': 'ar_007', 'type': 'choice', 'level': 'C1', 'prompt': 'Begging the question =', 'options': ['Asking question', 'Assuming what you prove', 'Weak evidence', 'Ignoring counter'], 'answer': 'Assuming what you prove', 'explanation': 'EN: Circular reasoning. | ZH: 循环论证'},
    {'id': 'ar_008', 'type': 'choice', 'level': 'C1', 'prompt': 'Best rebuttal:', 'options': ['Ignore', 'Dismiss rudely', 'Acknowledge then refute', 'Repeat claim'], 'answer': 'Acknowledge then refute', 'explanation': 'EN: Acknowledge then disprove. | ZH: 先承认再推翻'},
    {'id': 'ar_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Hasty generalisation =', 'options': ['Wide conclusion from few examples', 'Too many sources', 'Too brief', 'Too emotional'], 'answer': 'Wide conclusion from few examples', 'explanation': 'EN: Overgeneralising. | ZH: 以偏概全'},
    {'id': 'ar_010', 'type': 'choice', 'level': 'C1', 'prompt': 'Ethos refers to:', 'options': ['Emotional appeal', 'Logical evidence', 'Credibility', 'Statistical data'], 'answer': 'Credibility', 'explanation': 'EN: Appeal to credibility. | ZH: 人格诉求'},
]

QUESTIONS['upper.academic'] = [
    {'id': 'ac_001', 'type': 'choice', 'level': 'C1', 'prompt': 'Ubiquitous =', 'options': ['Rare', 'Found everywhere', 'Ancient', 'Complex'], 'answer': 'Found everywhere', 'explanation': 'EN: Present everywhere. | ZH: 无处不在'},
    {'id': 'ac_002', 'type': 'choice', 'level': 'C1', 'prompt': 'Empirical evidence based on:', 'options': ['Theory', 'Observation/experiment', 'Opinion', 'Logic alone'], 'answer': 'Observation/experiment', 'explanation': 'EN: Observed or tested. | ZH: 实证'},
    {'id': 'ac_003', 'type': 'choice', 'level': 'C1', 'prompt': 'Paradigm =', 'options': ['A conclusion', 'A model or framework', 'An exception', 'A bias'], 'answer': 'A model or framework', 'explanation': 'EN: Conceptual framework. | ZH: 范式'},
    {'id': 'ac_004', 'type': 'choice', 'level': 'C1', 'prompt': 'Corroborate =', 'options': ['Contradict', 'Confirm with evidence', 'Ignore', 'Simplify'], 'answer': 'Confirm with evidence', 'explanation': 'EN: Support with extra evidence. | ZH: 证实'},
    {'id': 'ac_005', 'type': 'choice', 'level': 'B2', 'prompt': 'Ambiguous =', 'options': ['Clear', 'Multiple meanings', 'False', 'Precise'], 'answer': 'Multiple meanings', 'explanation': 'EN: Open to multiple interpretations. | ZH: 含糊'},
    {'id': 'ac_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Mitigate =', 'options': ['Worsen', 'Ignore', 'Reduce severity', 'Celebrate'], 'answer': 'Reduce severity', 'explanation': 'EN: Lessen negative impact. | ZH: 减轻'},
    {'id': 'ac_007', 'type': 'choice', 'level': 'C1', 'prompt': 'Dichotomy =', 'options': ['A graph', 'Division into two parts', 'Complex argument', 'Research method'], 'answer': 'Division into two parts', 'explanation': 'EN: Split into two groups. | ZH: 二分法'},
    {'id': 'ac_008', 'type': 'choice', 'level': 'C1', 'prompt': 'Nuanced =', 'options': ['Black and white', 'Oversimplified', 'Subtle distinctions', 'Very obvious'], 'answer': 'Subtle distinctions', 'explanation': 'EN: Aware of fine differences. | ZH: 有细微差别'},
    {'id': 'ac_009', 'type': 'choice', 'level': 'C1', 'prompt': 'Substantiate =', 'options': ['Ignore', 'Provide evidence', 'Contradict', 'Exaggerate'], 'answer': 'Provide evidence', 'explanation': 'EN: Back up with proof. | ZH: 提供证据'},
    {'id': 'ac_010', 'type': 'choice', 'level': 'C1', 'prompt': 'Salient =', 'options': ['Hidden', 'Most noticeable', 'Old', 'Theoretical'], 'answer': 'Most noticeable', 'explanation': 'EN: Most prominent/relevant. | ZH: 最显著'},
]

QUESTIONS['upper.style'] = [
    {'id': 'sy_001', 'type': 'choice', 'level': 'B2', 'prompt': 'Wordy writing should:', 'options': ['Add adjectives', 'Remove unnecessary words', 'Use longer sentences', 'Add terms'], 'answer': 'Remove unnecessary words', 'explanation': 'EN: Concise = remove redundancy. | ZH: 简洁去冗'},
    {'id': 'sy_002', 'type': 'choice', 'level': 'B2', 'prompt': 'Active voice preferred because:', 'options': ['Sounds formal', 'Clearer and more direct', 'Fewer commas', 'Avoids pronouns'], 'answer': 'Clearer and more direct', 'explanation': 'EN: Active is direct and vivid. | ZH: 主动语态更直接'},
    {'id': 'sy_003', 'type': 'choice', 'level': 'B2', 'prompt': 'Most natural:', 'options': ['I am of the opinion that', 'I think', 'It is my contention that', 'In my humble opinion'], 'answer': 'I think', 'explanation': 'EN: I think is most natural. | ZH: I think最自然'},
    {'id': 'sy_004', 'type': 'choice', 'level': 'C1', 'prompt': 'At this point in time should be:', 'options': ['replaced with now', 'kept', 'made longer', 'removed'], 'answer': 'replaced with now', 'explanation': 'EN: Wordy phrases = replace with single words. | ZH: 冗余短语替换'},
    {'id': 'sy_005', 'type': 'choice', 'level': 'C1', 'prompt': 'Varying sentence length creates:', 'options': ['Confusion', 'Rhythm and emphasis', 'Errors', 'Redundancy'], 'answer': 'Rhythm and emphasis', 'explanation': 'EN: Mixed lengths create engaging rhythm. | ZH: 节奏感'},
    {'id': 'sy_006', 'type': 'choice', 'level': 'B2', 'prompt': 'Prefer simple verbs like:', 'options': ['Utilise', 'Use', 'Employ', 'Make utilisation of'], 'answer': 'Use', 'explanation': 'EN: Simple verbs beat jargon. | ZH: 简单动词'},
    {'id': 'sy_007', 'type': 'choice', 'level': 'C1', 'prompt': 'Absolutely essential is redundant because:', 'options': ['Essential is wrong', 'Essential already means absolute', 'Absolutely is wrong', 'Both rare'], 'answer': 'Essential already means absolute', 'explanation': 'EN: Essential = absolute necessity already. | ZH: essential本身含绝对之意'},
    {'id': 'sy_008', 'type': 'choice', 'level': 'B2', 'prompt': 'Parallel structure means:', 'options': ['Same grammar in a series', 'Using passive', 'Long sentences', 'Avoiding commas'], 'answer': 'Same grammar in a series', 'explanation': 'EN: Keep lists grammatically consistent. | ZH: 平行结构'},
    {'id': 'sy_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Parallel structure:', 'options': ['She likes reading, to swim, and dance.', 'She likes reading, swimming, and dancing.', 'She likes read, swim, dance.', 'She reads, to swim, dances.'], 'answer': 'She likes reading, swimming, and dancing.', 'explanation': 'EN: All gerunds = parallel. | ZH: 全用动名词'},
    {'id': 'sy_010', 'type': 'choice', 'level': 'B2', 'prompt': 'The reason is because should be:', 'options': ['kept as is', 'replaced with the reason is that', 'made longer', 'removed'], 'answer': 'replaced with the reason is that', 'explanation': 'EN: Avoids redundancy. | ZH: 避免重复'},
]

QUESTIONS['upper.presentation'] = [
    {'id': 'pe_001', 'type': 'choice', 'level': 'B2', 'prompt': 'Strong opening:', 'options': ['Lists all points', 'Story or striking fact', 'Summarises conclusion', 'Uses jargon'], 'answer': 'Story or striking fact', 'explanation': 'EN: Hook the audience. | ZH: 开场吸引注意'},
    {'id': 'pe_002', 'type': 'choice', 'level': 'C1', 'prompt': 'Signposting means:', 'options': ['Using slides', 'Telling audience your structure', 'Speaking slowly', 'Using terms'], 'answer': 'Telling audience your structure', 'explanation': 'EN: Guide audience through structure. | ZH: 路标语言'},
    {'id': 'pe_003', 'type': 'choice', 'level': 'B2', 'prompt': 'To sum up is used:', 'options': ['At start', 'In middle', 'At conclusion', 'When giving examples'], 'answer': 'At conclusion', 'explanation': 'EN: Summary at the end. | ZH: 总结用于结尾'},
    {'id': 'pe_004', 'type': 'choice', 'level': 'B2', 'prompt': 'Moving on to my next point is:', 'options': ['A hook', 'A transition phrase', 'A definition', 'A statistic'], 'answer': 'A transition phrase', 'explanation': 'EN: Links sections. | ZH: 过渡语'},
    {'id': 'pe_005', 'type': 'choice', 'level': 'B2', 'prompt': 'Eye contact:', 'options': ['Should be avoided', 'Builds connection', 'Slows speech', 'Only formal'], 'answer': 'Builds connection', 'explanation': 'EN: Shows confidence and engages. | ZH: 建立联系'},
    {'id': 'pe_006', 'type': 'choice', 'level': 'B2', 'prompt': 'Invites questions:', 'options': ['That is all.', 'Hold questions.', 'I would be happy to answer questions.', 'No questions.'], 'answer': 'I would be happy to answer questions.', 'explanation': 'EN: Open Q&A invitation. | ZH: 邀请提问'},
    {'id': 'pe_007', 'type': 'choice', 'level': 'B2', 'prompt': 'As you can see from this slide helps:', 'options': ['Hide info', 'Direct attention', 'Add humour', 'Slow pace'], 'answer': 'Direct attention', 'explanation': 'EN: Guide audience to visual. | ZH: 引导注意力'},
    {'id': 'pe_008', 'type': 'choice', 'level': 'B2', 'prompt': 'Speaking too fast causes:', 'options': ['Confidence', 'Audience loses track', 'Better timing', 'More questions'], 'answer': 'Audience loses track', 'explanation': 'EN: Hard to follow. | ZH: 听众跟不上'},
    {'id': 'pe_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Let me illustrate with an example introduces:', 'options': ['Conclusion', 'Example', 'Definition', 'Counterargument'], 'answer': 'Example', 'explanation': 'EN: Precedes an example. | ZH: 引入举例'},
    {'id': 'pe_010', 'type': 'choice', 'level': 'C1', 'prompt': 'Rule of three means:', 'options': ['3 slides only', 'Group ideas in threes', '3-minute limit', 'Use 3 statistics'], 'answer': 'Group ideas in threes', 'explanation': 'EN: Memorable pattern. | ZH: 三组信息增强效果'},
]

QUESTIONS['advanced.critical'] = [
    {'id': 'cr_001', 'type': 'choice', 'level': 'C1', 'prompt': 'Critical thinking involves:', 'options': ['Memorising facts', 'Evaluating evidence and reasoning', 'Writing neatly', 'Speaking quickly'], 'answer': 'Evaluating evidence and reasoning', 'explanation': 'EN: Analyse and evaluate. | ZH: 分析评估'},
    {'id': 'cr_002', 'type': 'choice', 'level': 'C1', 'prompt': 'False dichotomy presents:', 'options': ['Two true options', 'Only two when more exist', 'Three options', 'A dilemma'], 'answer': 'Only two when more exist', 'explanation': 'EN: Ignores alternatives. | ZH: 假二分法'},
    {'id': 'cr_003', 'type': 'choice', 'level': 'C1', 'prompt': 'Correlation does not imply causation means:', 'options': ['Related things are not cause-effect', 'Statistics are unreliable', 'Causes unknown', 'Research is flawed'], 'answer': 'Related things are not cause-effect', 'explanation': 'EN: A and B together does not mean A causes B. | ZH: 相关不等于因果'},
    {'id': 'cr_004', 'type': 'choice', 'level': 'C2', 'prompt': 'Cognitive bias refers to:', 'options': ['Language errors', 'Systematic errors in thinking', 'Memory problems', 'Vocab gaps'], 'answer': 'Systematic errors in thinking', 'explanation': 'EN: Mental shortcuts causing errors. | ZH: 认知偏见'},
    {'id': 'cr_005', 'type': 'choice', 'level': 'C1', 'prompt': 'Confirmation bias =', 'options': ['Seeking confirming evidence only', 'Doubting all evidence', 'Being logical', 'Avoiding bias'], 'answer': 'Seeking confirming evidence only', 'explanation': 'EN: Ignoring contradictory evidence. | ZH: 确认偏见'},
    {'id': 'cr_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Red herring is:', 'options': ['Strong evidence', 'Irrelevant distraction', 'Statistical error', 'Direct refutation'], 'answer': 'Irrelevant distraction', 'explanation': 'EN: Diverts from real issue. | ZH: 转移视线'},
    {'id': 'cr_007', 'type': 'choice', 'level': 'C2', 'prompt': 'Occam Razor suggests:', 'options': ['Complex explanations win', 'Simplest explanation usually correct', 'More evidence better', 'Avoid assumptions'], 'answer': 'Simplest explanation usually correct', 'explanation': 'EN: Prefer fewest assumptions. | ZH: 简单解释通常正确'},
    {'id': 'cr_008', 'type': 'choice', 'level': 'C1', 'prompt': 'Burden of proof lies with:', 'options': ['The audience', 'The person making the claim', 'The opponent', 'The judge'], 'answer': 'The person making the claim', 'explanation': 'EN: Claimant must provide evidence. | ZH: 举证责任'},
    {'id': 'cr_009', 'type': 'choice', 'level': 'C1', 'prompt': 'Critical evaluation:', 'options': ['I agree because it sounds right.', 'Data supports X but sample size is small.', 'The author must be wrong.', 'Everyone knows this.'], 'answer': 'Data supports X but sample size is small.', 'explanation': 'EN: Acknowledge strengths and limitations. | ZH: 认可优点指出局限'},
    {'id': 'cr_010', 'type': 'choice', 'level': 'C2', 'prompt': 'Intellectual humility means:', 'options': ['Pretending ignorance', 'Acknowledging limits of knowledge', 'Never sharing opinions', 'Always agreeing'], 'answer': 'Acknowledging limits of knowledge', 'explanation': 'EN: Recognise what you do not know. | ZH: 承认知识局限'},
]

QUESTIONS['advanced.complex'] = [
    {'id': 'cx_001', 'type': 'choice', 'level': 'C1', 'prompt': 'No sooner had she arrived ___ the meeting started.', 'options': ['when', 'than', 'that', 'as'], 'answer': 'than', 'explanation': 'EN: No sooner...than = fixed structure. | ZH: 固定搭配'},
    {'id': 'cx_002', 'type': 'choice', 'level': 'C1', 'prompt': 'It is not until midnight ___ he falls asleep.', 'options': ['when', 'that', 'which', 'than'], 'answer': 'that', 'explanation': 'EN: Cleft sentence structure. | ZH: 强调句'},
    {'id': 'cx_003', 'type': 'choice', 'level': 'C1', 'prompt': 'Seldom ___ such talent.', 'options': ['I have seen', 'have I seen', 'I saw', 'saw I'], 'answer': 'have I seen', 'explanation': 'EN: Inversion after negative adverb. | ZH: 否定副词后倒装'},
    {'id': 'cx_004', 'type': 'choice', 'level': 'C1', 'prompt': 'Were I in your position I would resign.', 'options': ['Present real', 'Past unreal', 'Present unreal subjunctive', 'Passive'], 'answer': 'Present unreal subjunctive', 'explanation': 'EN: Inverted conditional = subjunctive. | ZH: 倒装虚拟语气'},
    {'id': 'cx_005', 'type': 'choice', 'level': 'C2', 'prompt': 'Having submitted the report ___', 'options': ['it was reviewed', 'he waited for feedback', 'feedback was given', 'reviewing began'], 'answer': 'he waited for feedback', 'explanation': 'EN: Participial subject must match main clause. | ZH: 分词主语一致'},
    {'id': 'cx_006', 'type': 'choice', 'level': 'C1', 'prompt': 'The proposal ___ by all was adopted.', 'options': ['approved', 'approving', 'approve', 'to approve'], 'answer': 'approved', 'explanation': 'EN: Reduced relative clause. | ZH: 过去分词后置定语'},
    {'id': 'cx_007', 'type': 'choice', 'level': 'C2', 'prompt': 'Absolute phrase:', 'options': ['Running fast he won.', 'The job done we left.', 'Although tired she worked.', 'Having won she cheered.'], 'answer': 'The job done we left.', 'explanation': 'EN: Absolute phrase has its own subject. | ZH: 独立主格'},
    {'id': 'cx_008', 'type': 'choice', 'level': 'C1', 'prompt': 'Not only writes but ___ edits.', 'options': ['also', 'too', 'either', 'neither'], 'answer': 'also', 'explanation': 'EN: Not only...but also. | ZH: 关联连词'},
    {'id': 'cx_009', 'type': 'choice', 'level': 'C1', 'prompt': 'The harder you try ___', 'options': ['better you get', 'the better you get', 'you get better', 'get better'], 'answer': 'the better you get', 'explanation': 'EN: The + comparative the + comparative. | ZH: 越...越...'},
    {'id': 'cx_010', 'type': 'choice', 'level': 'C2', 'prompt': 'Little ___ her work would change history.', 'options': ['she knew', 'did she know', 'she did know', 'know she'], 'answer': 'did she know', 'explanation': 'EN: Inversion after little. | ZH: little后倒装'},
]

QUESTIONS['advanced.rhetoric'] = [
    {'id': 'rh_001', 'type': 'choice', 'level': 'C1', 'prompt': 'Anaphora is:', 'options': ['Repetition at end', 'Repetition at beginning', 'A metaphor', 'An antithesis'], 'answer': 'Repetition at beginning', 'explanation': 'EN: Repeat words at start of clauses. | ZH: 首语重复'},
    {'id': 'rh_002', 'type': 'choice', 'level': 'C1', 'prompt': 'I have a dream repeated is:', 'options': ['Epistrophe', 'Anaphora', 'Chiasmus', 'Hyperbole'], 'answer': 'Anaphora', 'explanation': 'EN: Classic anaphora. | ZH: 经典排比'},
    {'id': 'rh_003', 'type': 'choice', 'level': 'C2', 'prompt': 'Ask not what your country can do reversed structure is:', 'options': ['Anaphora', 'Chiasmus', 'Simile', 'Alliteration'], 'answer': 'Chiasmus', 'explanation': 'EN: Reversed grammatical structures. | ZH: 交叉配列'},
    {'id': 'rh_004', 'type': 'choice', 'level': 'C2', 'prompt': 'Epistrophe is repetition at:', 'options': ['Beginning', 'Middle', 'End', 'Random'], 'answer': 'End', 'explanation': 'EN: Repeat at end of clauses. | ZH: 结语重复'},
    {'id': 'rh_005', 'type': 'choice', 'level': 'B2', 'prompt': 'The pen is mightier than the sword is:', 'options': ['Simile', 'Metaphor', 'Alliteration', 'Irony'], 'answer': 'Metaphor', 'explanation': 'EN: Comparison without like/as. | ZH: 暗喻'},
    {'id': 'rh_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Logos means:', 'options': ['Emotional appeal', 'Credibility', 'Logical argument', 'Narrative'], 'answer': 'Logical argument', 'explanation': 'EN: Appeal to logic. | ZH: 逻辑诉求'},
    {'id': 'rh_007', 'type': 'choice', 'level': 'C1', 'prompt': 'Pathos means:', 'options': ['Logic', 'Emotional appeal', 'Authority', 'Evidence'], 'answer': 'Emotional appeal', 'explanation': 'EN: Appeal to emotions. | ZH: 情感诉求'},
    {'id': 'rh_008', 'type': 'choice', 'level': 'C1', 'prompt': 'Understatement deliberately:', 'options': ['Exaggerates', 'Minimises for ironic effect', 'Avoids metaphor', 'Uses statistics'], 'answer': 'Minimises for ironic effect', 'explanation': 'EN: Says less than you mean. | ZH: 轻描淡写'},
    {'id': 'rh_009', 'type': 'choice', 'level': 'C2', 'prompt': 'Synecdoche uses ___ to represent whole.', 'options': ['A metaphor', 'A part', 'An antonym', 'An example'], 'answer': 'A part', 'explanation': 'EN: Part for whole. | ZH: 提喻'},
    {'id': 'rh_010', 'type': 'choice', 'level': 'C1', 'prompt': 'Parallelism creates:', 'options': ['Confusion', 'Rhythm and balance', 'Long sentences', 'Multiple meanings'], 'answer': 'Rhythm and balance', 'explanation': 'EN: Balanced memorable sentences. | ZH: 节奏与平衡'},
]

QUESTIONS['advanced.synthesis'] = [
    {'id': 'sn_001', 'type': 'choice', 'level': 'C1', 'prompt': 'Synthesis writing requires:', 'options': ['Summarising one source', 'Integrating multiple sources', 'Copying directly', 'Listing sources'], 'answer': 'Integrating multiple sources', 'explanation': 'EN: Weave ideas from multiple sources. | ZH: 整合多个来源'},
    {'id': 'sn_002', 'type': 'choice', 'level': 'C1', 'prompt': 'According to Smith 2020 is:', 'options': ['Paraphrase', 'Direct quote', 'Citation', 'Summary'], 'answer': 'Citation', 'explanation': 'EN: Author + year = citation. | ZH: 引用格式'},
    {'id': 'sn_003', 'type': 'choice', 'level': 'B2', 'prompt': 'Paraphrasing means:', 'options': ['Copy word for word', 'Restate in your own words', 'Summarise briefly', 'Quote with citation'], 'answer': 'Restate in your own words', 'explanation': 'EN: Rewrite in different words. | ZH: 转述'},
    {'id': 'sn_004', 'type': 'choice', 'level': 'C1', 'prompt': 'NOT plagiarism:', 'options': ['Copying without citation', 'Paraphrasing with citation', 'Submitting others work', 'Self-plagiarism'], 'answer': 'Paraphrasing with citation', 'explanation': 'EN: Proper paraphrase + citation is fine. | ZH: 有引用的转述合规'},
    {'id': 'sn_005', 'type': 'choice', 'level': 'C1', 'prompt': 'Whereas Smith argues X Jones contends Y shows:', 'options': ['Agreement', 'Disagreement', 'Synthesis of contrasting views', 'Single viewpoint'], 'answer': 'Synthesis of contrasting views', 'explanation': 'EN: Contrasting views = synthesis. | ZH: 综合对立观点'},
    {'id': 'sn_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Annotated bibliography includes:', 'options': ['Only titles', 'Titles and evaluative summaries', 'Only summaries', 'Only dates'], 'answer': 'Titles and evaluative summaries', 'explanation': 'EN: Citation + description + evaluation. | ZH: 引用+描述+评价'},
    {'id': 'sn_007', 'type': 'choice', 'level': 'C1', 'prompt': 'The consensus among researchers signals:', 'options': ['One opinion', 'General field agreement', 'Controversial claim', 'Personal opinion'], 'answer': 'General field agreement', 'explanation': 'EN: Widespread scholarly agreement. | ZH: 学界共识'},
    {'id': 'sn_008', 'type': 'choice', 'level': 'C2', 'prompt': 'When sources conflict you should:', 'options': ['Ignore one', 'Choose the one that suits', 'Present both and evaluate', 'Use only newest'], 'answer': 'Present both and evaluate', 'explanation': 'EN: Acknowledge and evaluate conflicts. | ZH: 呈现并评估矛盾'},
    {'id': 'sn_009', 'type': 'choice', 'level': 'C1', 'prompt': 'Hedging language expresses:', 'options': ['Certainty', 'Caution/uncertainty', 'Emotion', 'Rhetoric'], 'answer': 'Caution/uncertainty', 'explanation': 'EN: May could suggests = academic caution. | ZH: 模糊限制语'},
    {'id': 'sn_010', 'type': 'choice', 'level': 'C2', 'prompt': 'Literature review purpose:', 'options': ['Summarise one book', 'Map existing research and gaps', 'Prove your point', 'Impress supervisors'], 'answer': 'Map existing research and gaps', 'explanation': 'EN: Map research and find gaps. | ZH: 梳理现有研究'},
]

QUESTIONS['ielts.listening'] = [
    {'id': 'il_001', 'type': 'choice', 'level': 'B2', 'prompt': 'IELTS Listening recordings play:', 'options': ['Twice', 'Once', 'Three times', 'As needed'], 'answer': 'Once', 'explanation': 'EN: Each recording plays once only. | ZH: 只播一遍'},
    {'id': 'il_002', 'type': 'choice', 'level': 'B2', 'prompt': 'Word limit for answers is usually:', 'options': ['No limit', 'One word', 'No more than three words or a number', 'Two words'], 'answer': 'No more than three words or a number', 'explanation': 'EN: Follow word limits exactly. | ZH: 严格遵守字数'},
    {'id': 'il_003', 'type': 'choice', 'level': 'B2', 'prompt': 'Note completion requires:', 'options': ['Full sentences', 'Filling gaps with specific info', 'Drawing', 'Giving opinions'], 'answer': 'Filling gaps with specific info', 'explanation': 'EN: Write words/numbers in blanks. | ZH: 填写具体信息'},
    {'id': 'il_004', 'type': 'choice', 'level': 'B2', 'prompt': 'Prediction before listening helps:', 'options': ['Wastes time', 'Prepares brain for vocabulary', 'Required by examiners', 'Replaces listening'], 'answer': 'Prepares brain for vocabulary', 'explanation': 'EN: Activates relevant knowledge. | ZH: 激活相关词汇知识'},
    {'id': 'il_005', 'type': 'choice', 'level': 'C1', 'prompt': 'Section 4 is usually:', 'options': ['A phone call', 'Social chat', 'Academic lecture or monologue', 'A job interview'], 'answer': 'Academic lecture or monologue', 'explanation': 'EN: Hardest section, academic monologue. | ZH: 最难，通常是学术独白'},
    {'id': 'il_006', 'type': 'choice', 'level': 'B2', 'prompt': 'If you miss an answer you should:', 'options': ['Stop and panic', 'Skip and continue', 'Go back immediately', 'Guess randomly'], 'answer': 'Skip and continue', 'explanation': 'EN: Do not dwell; keep listening. | ZH: 错过继续听'},
    {'id': 'il_007', 'type': 'choice', 'level': 'B2', 'prompt': 'Spelling mistakes:', 'options': ['Are acceptable', 'Lose marks', 'Do not matter', 'Are corrected'], 'answer': 'Lose marks', 'explanation': 'EN: Correct spelling is required. | ZH: 拼写错误会扣分'},
    {'id': 'il_008', 'type': 'choice', 'level': 'B2', 'prompt': 'Distractors are:', 'options': ['Wrong MCQ options', 'Helpful hints', 'Grammar clues', 'Background music'], 'answer': 'Wrong MCQ options', 'explanation': 'EN: Designed to mislead. | ZH: 干扰项'},
    {'id': 'il_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Map labelling requires:', 'options': ['Writing addresses', 'Identifying locations on diagram', 'Drawing a map', 'Describing routes'], 'answer': 'Identifying locations on diagram', 'explanation': 'EN: Label positions on given map. | ZH: 在地图上标注位置'},
    {'id': 'il_010', 'type': 'choice', 'level': 'B2', 'prompt': 'Multiple choice tests:', 'options': ['Writing ability', 'Identifying correct option from audio', 'Grammar', 'Vocabulary range'], 'answer': 'Identifying correct option from audio', 'explanation': 'EN: Careful listening and comprehension. | ZH: 仔细听并选正确答案'},
]

QUESTIONS['ielts.reading'] = [
    {'id': 'ir_001', 'type': 'choice', 'level': 'B2', 'prompt': 'IELTS Academic Reading has ___ sections.', 'options': ['2', '3', '4', '5'], 'answer': '3', 'explanation': 'EN: 3 sections each with a long text. | ZH: 三篇文章'},
    {'id': 'ir_002', 'type': 'choice', 'level': 'B2', 'prompt': 'Not Given means:', 'options': ['The statement is false', 'Information not in text', 'Writer disagrees', 'Irrelevant'], 'answer': 'Information not in text', 'explanation': 'EN: Text neither confirms nor denies. | ZH: 文章未提及'},
    {'id': 'ir_003', 'type': 'choice', 'level': 'C1', 'prompt': 'T/F/NG vs Y/N/NG:', 'options': ['Same thing', 'T/F is facts Y/N is writer opinion', 'Y/N is facts', 'No difference'], 'answer': 'T/F is facts Y/N is writer opinion', 'explanation': 'EN: True/False tests facts; Yes/No tests opinions. | ZH: 事实vs观点'},
    {'id': 'ir_004', 'type': 'choice', 'level': 'C1', 'prompt': 'Matching headings tests:', 'options': ['Spelling', 'Main idea of each paragraph', 'Specific facts', 'Grammar'], 'answer': 'Main idea of each paragraph', 'explanation': 'EN: Match headings to paragraph topics. | ZH: 段落大意匹配'},
    {'id': 'ir_005', 'type': 'choice', 'level': 'B2', 'prompt': 'Unknown word: you should:', 'options': ['Stop reading', 'Skip paragraph', 'Guess from context', 'Look it up'], 'answer': 'Guess from context', 'explanation': 'EN: Use context clues. | ZH: 利用上下文猜测'},
    {'id': 'ir_006', 'type': 'choice', 'level': 'B2', 'prompt': 'Sentence completion: you use words:', 'options': ['You write yourself', 'From the text', 'From other sources', 'From definitions'], 'answer': 'From the text', 'explanation': 'EN: Copy exact words from passage. | ZH: 从文中找原词'},
    {'id': 'ir_007', 'type': 'choice', 'level': 'C1', 'prompt': 'Skimming first helps:', 'options': ['Answer immediately', 'Get overall structure', 'Memorise', 'Skip difficult parts'], 'answer': 'Get overall structure', 'explanation': 'EN: Overview before detailed reading. | ZH: 先了解整体结构'},
    {'id': 'ir_008', 'type': 'choice', 'level': 'C1', 'prompt': 'In IELTS Reading answers are:', 'options': ['In order', 'Not necessarily in order', 'At end', 'Only in first paragraph'], 'answer': 'Not necessarily in order', 'explanation': 'EN: Most types do not follow text order. | ZH: 答案不一定按顺序'},
    {'id': 'ir_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Time per passage roughly:', 'options': ['30 min', '20 min', '10 min', '40 min'], 'answer': '20 min', 'explanation': 'EN: About 20 minutes per section. | ZH: 每篇约20分钟'},
    {'id': 'ir_010', 'type': 'choice', 'level': 'C1', 'prompt': 'Summary completion tests:', 'options': ['Writing', 'Key ideas in a section', 'Grammar', 'Vocab range'], 'answer': 'Key ideas in a section', 'explanation': 'EN: Comprehension of main ideas. | ZH: 理解主要内容'},
]

QUESTIONS['ielts.writing'] = [
    {'id': 'iw_001', 'type': 'choice', 'level': 'B2', 'prompt': 'Task 1 Academic requires describing:', 'options': ['An essay', 'A visual', 'A letter', 'Your opinion'], 'answer': 'A visual', 'explanation': 'EN: Describe graph chart diagram or map. | ZH: 描述图表'},
    {'id': 'iw_002', 'type': 'choice', 'level': 'B2', 'prompt': 'Task 2 minimum words:', 'options': ['150', '250', '200', '300'], 'answer': '250', 'explanation': 'EN: At least 250 words. | ZH: 至少250词'},
    {'id': 'iw_003', 'type': 'choice', 'level': 'B2', 'prompt': 'Dramatic increase means:', 'options': ['Theatrical', 'Very significant', 'Gradual', 'Slight'], 'answer': 'Very significant', 'explanation': 'EN: Dramatic = very large change. | ZH: 大幅度'},
    {'id': 'iw_004', 'type': 'choice', 'level': 'B2', 'prompt': 'Best describes downward trend:', 'options': ['Rose sharply', 'Fluctuated', 'Declined steadily', 'Remained stable'], 'answer': 'Declined steadily', 'explanation': 'EN: Consistent downward movement. | ZH: 持续下降'},
    {'id': 'iw_005', 'type': 'choice', 'level': 'C1', 'prompt': 'Thesis statement appears:', 'options': ['In conclusion', 'In body paragraph', 'End of introduction', 'Anywhere'], 'answer': 'End of introduction', 'explanation': 'EN: State position in introduction. | ZH: 论点在引言末'},
    {'id': 'iw_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Lexical resource is scored on:', 'options': ['Grammar', 'Vocabulary range and accuracy', 'Number of paragraphs', 'Word count'], 'answer': 'Vocabulary range and accuracy', 'explanation': 'EN: Appropriate and varied vocabulary. | ZH: 词汇多样性和准确性'},
    {'id': 'iw_007', 'type': 'choice', 'level': 'C1', 'prompt': 'Coherence and cohesion scores:', 'options': ['Vocabulary', 'Ideas', 'How logically ideas link', 'Grammar'], 'answer': 'How logically ideas link', 'explanation': 'EN: Logical flow and linking devices. | ZH: 逻辑流和连接词'},
    {'id': 'iw_008', 'type': 'choice', 'level': 'C1', 'prompt': 'To what extent do you agree requires:', 'options': ['Only agreeing', 'Only disagreeing', 'Nuanced position with support', 'Describing a graph'], 'answer': 'Nuanced position with support', 'explanation': 'EN: Express degree of agreement with reasons. | ZH: 表达程度并给理由'},
    {'id': 'iw_009', 'type': 'choice', 'level': 'C1', 'prompt': 'Introduces a counterargument:', 'options': ['Furthermore', 'In conclusion', 'Admittedly some argue that', 'The data shows'], 'answer': 'Admittedly some argue that', 'explanation': 'EN: Concession phrase. | ZH: 让步短语'},
    {'id': 'iw_010', 'type': 'choice', 'level': 'C1', 'prompt': 'Band 7 essays typically:', 'options': ['Use simple vocab', 'Have one body para', 'Show clear position with development', 'Repeat the question'], 'answer': 'Show clear position with development', 'explanation': 'EN: Clear well-supported argument. | ZH: 清晰立场和充分论证'},
]

QUESTIONS['ielts.speaking'] = [
    {'id': 'is_001', 'type': 'choice', 'level': 'B2', 'prompt': 'Speaking Part 1 is about:', 'options': ['Academic topics', 'Personal familiar topics', 'Complex issues', 'Describing graph'], 'answer': 'Personal familiar topics', 'explanation': 'EN: Everyday topics like family hobbies. | ZH: 熟悉的个人话题'},
    {'id': 'is_002', 'type': 'choice', 'level': 'B2', 'prompt': 'Cue card preparation time:', 'options': ['30 seconds', '1 minute', '2 minutes', '5 minutes'], 'answer': '1 minute', 'explanation': 'EN: 1 minute to prepare 2-minute talk. | ZH: 1分钟准备'},
    {'id': 'is_003', 'type': 'choice', 'level': 'B2', 'prompt': 'Fluency and coherence scored on:', 'options': ['Accent', 'Continuous connected speech', 'Grammar', 'Vocabulary'], 'answer': 'Continuous connected speech', 'explanation': 'EN: Speak without unnatural hesitation. | ZH: 连贯自然'},
    {'id': 'is_004', 'type': 'choice', 'level': 'B2', 'prompt': 'Extend Part 1 answer by:', 'options': ['Say yes or no', 'Give short answer', 'Add reason and example', 'Speak fast'], 'answer': 'Add reason and example', 'explanation': 'EN: Develop with because and for instance. | ZH: 用原因举例扩展'},
    {'id': 'is_005', 'type': 'choice', 'level': 'B2', 'prompt': 'Pronunciation scored on:', 'options': ['Native accent', 'Clear and understandable', 'Avoiding errors', 'British English'], 'answer': 'Clear and understandable', 'explanation': 'EN: Clarity matters more than accent. | ZH: 清晰易懂'},
    {'id': 'is_006', 'type': 'choice', 'level': 'C1', 'prompt': 'Part 3 is:', 'options': ['A monologue', 'Discussion of abstract ideas', 'Personal story', 'A description'], 'answer': 'Discussion of abstract ideas', 'explanation': 'EN: Two-way discussion of broader topics. | ZH: 双向讨论抽象话题'},
    {'id': 'is_007', 'type': 'choice', 'level': 'B2', 'prompt': 'Do not understand question:', 'options': ['Stay silent', 'Say I do not know', 'Ask for clarification politely', 'Repeat question'], 'answer': 'Ask for clarification politely', 'explanation': 'EN: Could you rephrase that is fine. | ZH: 礼貌要求澄清'},
    {'id': 'is_008', 'type': 'choice', 'level': 'C1', 'prompt': 'Grammatical range rewards:', 'options': ['Simple sentences only', 'Variety of complex structures', 'Avoiding grammar', 'Writing accurately'], 'answer': 'Variety of complex structures', 'explanation': 'EN: Mix of structures shows competence. | ZH: 多样结构'},
    {'id': 'is_009', 'type': 'choice', 'level': 'B2', 'prompt': 'Good Speaking answers use:', 'options': ['Constant fillers', 'Range of vocabulary and grammar', 'Memorised scripts', 'Very short answers'], 'answer': 'Range of vocabulary and grammar', 'explanation': 'EN: Natural varied language scores higher. | ZH: 自然多样的语言'},
    {'id': 'is_010', 'type': 'choice', 'level': 'B2', 'prompt': 'Lexical resource rewards:', 'options': ['Correct spelling', 'Precise and varied vocabulary', 'Speaking fast', 'Long answers'], 'answer': 'Precise and varied vocabulary', 'explanation': 'EN: Appropriate vocabulary boosts score. | ZH: 精准多样的词汇'},
]

