from __future__ import annotations

from typing import Protocol

from linguoos.core.domain import LearningRecord, Session


class Repository(Protocol):
    async def init(self) -> None: ...

    async def create_session(self, session: Session) -> None: ...

    async def get_session(self, session_id: str) -> Session | None: ...

    async def list_sessions_by_user(self, user_id: str) -> list[Session]: ...

    async def list_sessions(self) -> list[Session]: ...

    async def add_record(self, record: LearningRecord) -> None: ...

    async def list_records(self, session_id: str, limit: int = 20) -> list[LearningRecord]: ...

    async def update_session_status(self, session_id: str, status: str) -> None: ...

    async def create_intervention(self, session_id: str, reason: str, context: dict) -> int: ...

    async def list_interventions(self, status: str | None = None) -> list[dict]: ...

    async def resolve_intervention(self, intervention_id: int, teacher_response: str) -> None: ...
